// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"

	"github.com/wso2/ai-agent-management-platform/agent-manager-service/clients/apiplatformsvc/client"
)

// APIPlatformClientMock is a mock implementation of client.APIPlatformClient.
//
//	func TestSomethingThatUsesAPIPlatformClient(t *testing.T) {
//
//		// make and configure a mocked client.APIPlatformClient
//		mockedAPIPlatformClient := &APIPlatformClientMock{
//			CreateGatewayFunc: func(ctx context.Context, req client.CreateGatewayRequest) (*client.GatewayResponse, error) {
//				panic("mock out the CreateGateway method")
//			},
//			DeleteGatewayFunc: func(ctx context.Context, gatewayID string) error {
//				panic("mock out the DeleteGateway method")
//			},
//			GetGatewayFunc: func(ctx context.Context, gatewayID string) (*client.GatewayResponse, error) {
//				panic("mock out the GetGateway method")
//			},
//			GetOrganizationFunc: func(ctx context.Context) (*client.OrganizationResponse, error) {
//				panic("mock out the GetOrganization method")
//			},
//			ListGatewaysFunc: func(ctx context.Context) ([]*client.GatewayResponse, error) {
//				panic("mock out the ListGateways method")
//			},
//			RegisterOrganizationFunc: func(ctx context.Context, req client.RegisterOrganizationRequest) (*client.OrganizationResponse, error) {
//				panic("mock out the RegisterOrganization method")
//			},
//			RevokeGatewayTokenFunc: func(ctx context.Context, gatewayID string, tokenID string) error {
//				panic("mock out the RevokeGatewayToken method")
//			},
//			RotateGatewayTokenFunc: func(ctx context.Context, gatewayID string) (*client.GatewayTokenResponse, error) {
//				panic("mock out the RotateGatewayToken method")
//			},
//			UpdateGatewayFunc: func(ctx context.Context, gatewayID string, req client.UpdateGatewayRequest) (*client.GatewayResponse, error) {
//				panic("mock out the UpdateGateway method")
//			},
//		}
//
//		// use mockedAPIPlatformClient in code that requires client.APIPlatformClient
//		// and then make assertions.
//
//	}
type APIPlatformClientMock struct {
	// CreateGatewayFunc mocks the CreateGateway method.
	CreateGatewayFunc func(ctx context.Context, req client.CreateGatewayRequest) (*client.GatewayResponse, error)

	// DeleteGatewayFunc mocks the DeleteGateway method.
	DeleteGatewayFunc func(ctx context.Context, gatewayID string) error

	// GetGatewayFunc mocks the GetGateway method.
	GetGatewayFunc func(ctx context.Context, gatewayID string) (*client.GatewayResponse, error)

	// GetOrganizationFunc mocks the GetOrganization method.
	GetOrganizationFunc func(ctx context.Context) (*client.OrganizationResponse, error)

	// ListGatewaysFunc mocks the ListGateways method.
	ListGatewaysFunc func(ctx context.Context) ([]*client.GatewayResponse, error)

	// RegisterOrganizationFunc mocks the RegisterOrganization method.
	RegisterOrganizationFunc func(ctx context.Context, req client.RegisterOrganizationRequest) (*client.OrganizationResponse, error)

	// RevokeGatewayTokenFunc mocks the RevokeGatewayToken method.
	RevokeGatewayTokenFunc func(ctx context.Context, gatewayID string, tokenID string) error

	// RotateGatewayTokenFunc mocks the RotateGatewayToken method.
	RotateGatewayTokenFunc func(ctx context.Context, gatewayID string) (*client.GatewayTokenResponse, error)

	// UpdateGatewayFunc mocks the UpdateGateway method.
	UpdateGatewayFunc func(ctx context.Context, gatewayID string, req client.UpdateGatewayRequest) (*client.GatewayResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateGateway holds details about calls to the CreateGateway method.
		CreateGateway []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req client.CreateGatewayRequest
		}
		// DeleteGateway holds details about calls to the DeleteGateway method.
		DeleteGateway []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayID is the gatewayID argument value.
			GatewayID string
		}
		// GetGateway holds details about calls to the GetGateway method.
		GetGateway []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayID is the gatewayID argument value.
			GatewayID string
		}
		// GetOrganization holds details about calls to the GetOrganization method.
		GetOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListGateways holds details about calls to the ListGateways method.
		ListGateways []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// RegisterOrganization holds details about calls to the RegisterOrganization method.
		RegisterOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req client.RegisterOrganizationRequest
		}
		// RevokeGatewayToken holds details about calls to the RevokeGatewayToken method.
		RevokeGatewayToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// TokenID is the tokenID argument value.
			TokenID string
		}
		// RotateGatewayToken holds details about calls to the RotateGatewayToken method.
		RotateGatewayToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayID is the gatewayID argument value.
			GatewayID string
		}
		// UpdateGateway holds details about calls to the UpdateGateway method.
		UpdateGateway []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// Req is the req argument value.
			Req client.UpdateGatewayRequest
		}
	}
	lockCreateGateway        sync.RWMutex
	lockDeleteGateway        sync.RWMutex
	lockGetGateway           sync.RWMutex
	lockGetOrganization      sync.RWMutex
	lockListGateways         sync.RWMutex
	lockRegisterOrganization sync.RWMutex
	lockRevokeGatewayToken   sync.RWMutex
	lockRotateGatewayToken   sync.RWMutex
	lockUpdateGateway        sync.RWMutex
}

// CreateGateway calls CreateGatewayFunc.
func (mock *APIPlatformClientMock) CreateGateway(ctx context.Context, req client.CreateGatewayRequest) (*client.GatewayResponse, error) {
	if mock.CreateGatewayFunc == nil {
		panic("APIPlatformClientMock.CreateGatewayFunc: method is nil but APIPlatformClient.CreateGateway was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req client.CreateGatewayRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateGateway.Lock()
	mock.calls.CreateGateway = append(mock.calls.CreateGateway, callInfo)
	mock.lockCreateGateway.Unlock()
	return mock.CreateGatewayFunc(ctx, req)
}

// CreateGatewayCalls gets all the calls that were made to CreateGateway.
// Check the length with:
//
//	len(mockedAPIPlatformClient.CreateGatewayCalls())
func (mock *APIPlatformClientMock) CreateGatewayCalls() []struct {
	Ctx context.Context
	Req client.CreateGatewayRequest
} {
	var calls []struct {
		Ctx context.Context
		Req client.CreateGatewayRequest
	}
	mock.lockCreateGateway.RLock()
	calls = mock.calls.CreateGateway
	mock.lockCreateGateway.RUnlock()
	return calls
}

// DeleteGateway calls DeleteGatewayFunc.
func (mock *APIPlatformClientMock) DeleteGateway(ctx context.Context, gatewayID string) error {
	if mock.DeleteGatewayFunc == nil {
		panic("APIPlatformClientMock.DeleteGatewayFunc: method is nil but APIPlatformClient.DeleteGateway was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayID string
	}{
		Ctx:       ctx,
		GatewayID: gatewayID,
	}
	mock.lockDeleteGateway.Lock()
	mock.calls.DeleteGateway = append(mock.calls.DeleteGateway, callInfo)
	mock.lockDeleteGateway.Unlock()
	return mock.DeleteGatewayFunc(ctx, gatewayID)
}

// DeleteGatewayCalls gets all the calls that were made to DeleteGateway.
// Check the length with:
//
//	len(mockedAPIPlatformClient.DeleteGatewayCalls())
func (mock *APIPlatformClientMock) DeleteGatewayCalls() []struct {
	Ctx       context.Context
	GatewayID string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayID string
	}
	mock.lockDeleteGateway.RLock()
	calls = mock.calls.DeleteGateway
	mock.lockDeleteGateway.RUnlock()
	return calls
}

// GetGateway calls GetGatewayFunc.
func (mock *APIPlatformClientMock) GetGateway(ctx context.Context, gatewayID string) (*client.GatewayResponse, error) {
	if mock.GetGatewayFunc == nil {
		panic("APIPlatformClientMock.GetGatewayFunc: method is nil but APIPlatformClient.GetGateway was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayID string
	}{
		Ctx:       ctx,
		GatewayID: gatewayID,
	}
	mock.lockGetGateway.Lock()
	mock.calls.GetGateway = append(mock.calls.GetGateway, callInfo)
	mock.lockGetGateway.Unlock()
	return mock.GetGatewayFunc(ctx, gatewayID)
}

// GetGatewayCalls gets all the calls that were made to GetGateway.
// Check the length with:
//
//	len(mockedAPIPlatformClient.GetGatewayCalls())
func (mock *APIPlatformClientMock) GetGatewayCalls() []struct {
	Ctx       context.Context
	GatewayID string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayID string
	}
	mock.lockGetGateway.RLock()
	calls = mock.calls.GetGateway
	mock.lockGetGateway.RUnlock()
	return calls
}

// GetOrganization calls GetOrganizationFunc.
func (mock *APIPlatformClientMock) GetOrganization(ctx context.Context) (*client.OrganizationResponse, error) {
	if mock.GetOrganizationFunc == nil {
		panic("APIPlatformClientMock.GetOrganizationFunc: method is nil but APIPlatformClient.GetOrganization was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetOrganization.Lock()
	mock.calls.GetOrganization = append(mock.calls.GetOrganization, callInfo)
	mock.lockGetOrganization.Unlock()
	return mock.GetOrganizationFunc(ctx)
}

// GetOrganizationCalls gets all the calls that were made to GetOrganization.
// Check the length with:
//
//	len(mockedAPIPlatformClient.GetOrganizationCalls())
func (mock *APIPlatformClientMock) GetOrganizationCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetOrganization.RLock()
	calls = mock.calls.GetOrganization
	mock.lockGetOrganization.RUnlock()
	return calls
}

// ListGateways calls ListGatewaysFunc.
func (mock *APIPlatformClientMock) ListGateways(ctx context.Context) ([]*client.GatewayResponse, error) {
	if mock.ListGatewaysFunc == nil {
		panic("APIPlatformClientMock.ListGatewaysFunc: method is nil but APIPlatformClient.ListGateways was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListGateways.Lock()
	mock.calls.ListGateways = append(mock.calls.ListGateways, callInfo)
	mock.lockListGateways.Unlock()
	return mock.ListGatewaysFunc(ctx)
}

// ListGatewaysCalls gets all the calls that were made to ListGateways.
// Check the length with:
//
//	len(mockedAPIPlatformClient.ListGatewaysCalls())
func (mock *APIPlatformClientMock) ListGatewaysCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListGateways.RLock()
	calls = mock.calls.ListGateways
	mock.lockListGateways.RUnlock()
	return calls
}

// RegisterOrganization calls RegisterOrganizationFunc.
func (mock *APIPlatformClientMock) RegisterOrganization(ctx context.Context, req client.RegisterOrganizationRequest) (*client.OrganizationResponse, error) {
	if mock.RegisterOrganizationFunc == nil {
		panic("APIPlatformClientMock.RegisterOrganizationFunc: method is nil but APIPlatformClient.RegisterOrganization was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req client.RegisterOrganizationRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRegisterOrganization.Lock()
	mock.calls.RegisterOrganization = append(mock.calls.RegisterOrganization, callInfo)
	mock.lockRegisterOrganization.Unlock()
	return mock.RegisterOrganizationFunc(ctx, req)
}

// RegisterOrganizationCalls gets all the calls that were made to RegisterOrganization.
// Check the length with:
//
//	len(mockedAPIPlatformClient.RegisterOrganizationCalls())
func (mock *APIPlatformClientMock) RegisterOrganizationCalls() []struct {
	Ctx context.Context
	Req client.RegisterOrganizationRequest
} {
	var calls []struct {
		Ctx context.Context
		Req client.RegisterOrganizationRequest
	}
	mock.lockRegisterOrganization.RLock()
	calls = mock.calls.RegisterOrganization
	mock.lockRegisterOrganization.RUnlock()
	return calls
}

// RevokeGatewayToken calls RevokeGatewayTokenFunc.
func (mock *APIPlatformClientMock) RevokeGatewayToken(ctx context.Context, gatewayID string, tokenID string) error {
	if mock.RevokeGatewayTokenFunc == nil {
		panic("APIPlatformClientMock.RevokeGatewayTokenFunc: method is nil but APIPlatformClient.RevokeGatewayToken was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayID string
		TokenID   string
	}{
		Ctx:       ctx,
		GatewayID: gatewayID,
		TokenID:   tokenID,
	}
	mock.lockRevokeGatewayToken.Lock()
	mock.calls.RevokeGatewayToken = append(mock.calls.RevokeGatewayToken, callInfo)
	mock.lockRevokeGatewayToken.Unlock()
	return mock.RevokeGatewayTokenFunc(ctx, gatewayID, tokenID)
}

// RevokeGatewayTokenCalls gets all the calls that were made to RevokeGatewayToken.
// Check the length with:
//
//	len(mockedAPIPlatformClient.RevokeGatewayTokenCalls())
func (mock *APIPlatformClientMock) RevokeGatewayTokenCalls() []struct {
	Ctx       context.Context
	GatewayID string
	TokenID   string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayID string
		TokenID   string
	}
	mock.lockRevokeGatewayToken.RLock()
	calls = mock.calls.RevokeGatewayToken
	mock.lockRevokeGatewayToken.RUnlock()
	return calls
}

// RotateGatewayToken calls RotateGatewayTokenFunc.
func (mock *APIPlatformClientMock) RotateGatewayToken(ctx context.Context, gatewayID string) (*client.GatewayTokenResponse, error) {
	if mock.RotateGatewayTokenFunc == nil {
		panic("APIPlatformClientMock.RotateGatewayTokenFunc: method is nil but APIPlatformClient.RotateGatewayToken was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayID string
	}{
		Ctx:       ctx,
		GatewayID: gatewayID,
	}
	mock.lockRotateGatewayToken.Lock()
	mock.calls.RotateGatewayToken = append(mock.calls.RotateGatewayToken, callInfo)
	mock.lockRotateGatewayToken.Unlock()
	return mock.RotateGatewayTokenFunc(ctx, gatewayID)
}

// RotateGatewayTokenCalls gets all the calls that were made to RotateGatewayToken.
// Check the length with:
//
//	len(mockedAPIPlatformClient.RotateGatewayTokenCalls())
func (mock *APIPlatformClientMock) RotateGatewayTokenCalls() []struct {
	Ctx       context.Context
	GatewayID string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayID string
	}
	mock.lockRotateGatewayToken.RLock()
	calls = mock.calls.RotateGatewayToken
	mock.lockRotateGatewayToken.RUnlock()
	return calls
}

// UpdateGateway calls UpdateGatewayFunc.
func (mock *APIPlatformClientMock) UpdateGateway(ctx context.Context, gatewayID string, req client.UpdateGatewayRequest) (*client.GatewayResponse, error) {
	if mock.UpdateGatewayFunc == nil {
		panic("APIPlatformClientMock.UpdateGatewayFunc: method is nil but APIPlatformClient.UpdateGateway was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayID string
		Req       client.UpdateGatewayRequest
	}{
		Ctx:       ctx,
		GatewayID: gatewayID,
		Req:       req,
	}
	mock.lockUpdateGateway.Lock()
	mock.calls.UpdateGateway = append(mock.calls.UpdateGateway, callInfo)
	mock.lockUpdateGateway.Unlock()
	return mock.UpdateGatewayFunc(ctx, gatewayID, req)
}

// UpdateGatewayCalls gets all the calls that were made to UpdateGateway.
// Check the length with:
//
//	len(mockedAPIPlatformClient.UpdateGatewayCalls())
func (mock *APIPlatformClientMock) UpdateGatewayCalls() []struct {
	Ctx       context.Context
	GatewayID string
	Req       client.UpdateGatewayRequest
} {
	var calls []struct {
		Ctx       context.Context
		GatewayID string
		Req       client.UpdateGatewayRequest
	}
	mock.lockUpdateGateway.RLock()
	calls = mock.calls.UpdateGateway
	mock.lockUpdateGateway.RUnlock()
	return calls
}
