// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"

	"github.com/wso2/ai-agent-management-platform/agent-manager-service/models"
	"github.com/wso2/ai-agent-management-platform/agent-manager-service/spec"
)

// ObservabilitySvcClientMock is a mock implementation of observabilitysvc.ObservabilitySvcClient.
//
//	func TestSomethingThatUsesObservabilitySvcClient(t *testing.T) {
//
//		// make and configure a mocked observabilitysvc.ObservabilitySvcClient
//		mockedObservabilitySvcClient := &ObservabilitySvcClientMock{
//			GetBuildLogsFunc: func(ctx context.Context, buildName string) (*models.LogsResponse, error) {
//				panic("mock out the GetBuildLogs method")
//			},
//			GetComponentLogsFunc: func(ctx context.Context, agentComponentId string, envId string, payload spec.LogFilterRequest) (*models.LogsResponse, error) {
//				panic("mock out the GetComponentLogs method")
//			},
//			GetComponentMetricsFunc: func(ctx context.Context, agentComponentId string, envId string, projectId string, payload spec.MetricsFilterRequest) (*models.MetricsResponse, error) {
//				panic("mock out the GetComponentMetrics method")
//			},
//		}
//
//		// use mockedObservabilitySvcClient in code that requires observabilitysvc.ObservabilitySvcClient
//		// and then make assertions.
//
//	}
type ObservabilitySvcClientMock struct {
	// GetBuildLogsFunc mocks the GetBuildLogs method.
	GetBuildLogsFunc func(ctx context.Context, buildName string) (*models.LogsResponse, error)

	// GetComponentLogsFunc mocks the GetComponentLogs method.
	GetComponentLogsFunc func(ctx context.Context, agentComponentId string, envId string, payload spec.LogFilterRequest) (*models.LogsResponse, error)

	// GetComponentMetricsFunc mocks the GetComponentMetrics method.
	GetComponentMetricsFunc func(ctx context.Context, agentComponentId string, envId string, projectId string, payload spec.MetricsFilterRequest) (*models.MetricsResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetBuildLogs holds details about calls to the GetBuildLogs method.
		GetBuildLogs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BuildName is the buildName argument value.
			BuildName string
		}
		// GetComponentLogs holds details about calls to the GetComponentLogs method.
		GetComponentLogs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AgentComponentId is the agentComponentId argument value.
			AgentComponentId string
			// EnvId is the envId argument value.
			EnvId string
			// Payload is the payload argument value.
			Payload spec.LogFilterRequest
		}
		// GetComponentMetrics holds details about calls to the GetComponentMetrics method.
		GetComponentMetrics []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AgentComponentId is the agentComponentId argument value.
			AgentComponentId string
			// EnvId is the envId argument value.
			EnvId string
			// ProjectId is the projectId argument value.
			ProjectId string
			// Payload is the payload argument value.
			Payload spec.MetricsFilterRequest
		}
	}
	lockGetBuildLogs        sync.RWMutex
	lockGetComponentLogs    sync.RWMutex
	lockGetComponentMetrics sync.RWMutex
}

// GetBuildLogs calls GetBuildLogsFunc.
func (mock *ObservabilitySvcClientMock) GetBuildLogs(ctx context.Context, buildName string) (*models.LogsResponse, error) {
	if mock.GetBuildLogsFunc == nil {
		panic("ObservabilitySvcClientMock.GetBuildLogsFunc: method is nil but ObservabilitySvcClient.GetBuildLogs was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		BuildName string
	}{
		Ctx:       ctx,
		BuildName: buildName,
	}
	mock.lockGetBuildLogs.Lock()
	mock.calls.GetBuildLogs = append(mock.calls.GetBuildLogs, callInfo)
	mock.lockGetBuildLogs.Unlock()
	return mock.GetBuildLogsFunc(ctx, buildName)
}

// GetBuildLogsCalls gets all the calls that were made to GetBuildLogs.
// Check the length with:
//
//	len(mockedObservabilitySvcClient.GetBuildLogsCalls())
func (mock *ObservabilitySvcClientMock) GetBuildLogsCalls() []struct {
	Ctx       context.Context
	BuildName string
} {
	var calls []struct {
		Ctx       context.Context
		BuildName string
	}
	mock.lockGetBuildLogs.RLock()
	calls = mock.calls.GetBuildLogs
	mock.lockGetBuildLogs.RUnlock()
	return calls
}

// GetComponentLogs calls GetComponentLogsFunc.
func (mock *ObservabilitySvcClientMock) GetComponentLogs(ctx context.Context, agentComponentId string, envId string, payload spec.LogFilterRequest) (*models.LogsResponse, error) {
	if mock.GetComponentLogsFunc == nil {
		panic("ObservabilitySvcClientMock.GetComponentLogsFunc: method is nil but ObservabilitySvcClient.GetComponentLogs was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		AgentComponentId string
		EnvId            string
		Payload          spec.LogFilterRequest
	}{
		Ctx:              ctx,
		AgentComponentId: agentComponentId,
		EnvId:            envId,
		Payload:          payload,
	}
	mock.lockGetComponentLogs.Lock()
	mock.calls.GetComponentLogs = append(mock.calls.GetComponentLogs, callInfo)
	mock.lockGetComponentLogs.Unlock()
	return mock.GetComponentLogsFunc(ctx, agentComponentId, envId, payload)
}

// GetComponentLogsCalls gets all the calls that were made to GetComponentLogs.
// Check the length with:
//
//	len(mockedObservabilitySvcClient.GetComponentLogsCalls())
func (mock *ObservabilitySvcClientMock) GetComponentLogsCalls() []struct {
	Ctx              context.Context
	AgentComponentId string
	EnvId            string
	Payload          spec.LogFilterRequest
} {
	var calls []struct {
		Ctx              context.Context
		AgentComponentId string
		EnvId            string
		Payload          spec.LogFilterRequest
	}
	mock.lockGetComponentLogs.RLock()
	calls = mock.calls.GetComponentLogs
	mock.lockGetComponentLogs.RUnlock()
	return calls
}

// GetComponentMetrics calls GetComponentMetricsFunc.
func (mock *ObservabilitySvcClientMock) GetComponentMetrics(ctx context.Context, agentComponentId string, envId string, projectId string, payload spec.MetricsFilterRequest) (*models.MetricsResponse, error) {
	if mock.GetComponentMetricsFunc == nil {
		panic("ObservabilitySvcClientMock.GetComponentMetricsFunc: method is nil but ObservabilitySvcClient.GetComponentMetrics was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		AgentComponentId string
		EnvId            string
		ProjectId        string
		Payload          spec.MetricsFilterRequest
	}{
		Ctx:              ctx,
		AgentComponentId: agentComponentId,
		EnvId:            envId,
		ProjectId:        projectId,
		Payload:          payload,
	}
	mock.lockGetComponentMetrics.Lock()
	mock.calls.GetComponentMetrics = append(mock.calls.GetComponentMetrics, callInfo)
	mock.lockGetComponentMetrics.Unlock()
	return mock.GetComponentMetricsFunc(ctx, agentComponentId, envId, projectId, payload)
}

// GetComponentMetricsCalls gets all the calls that were made to GetComponentMetrics.
// Check the length with:
//
//	len(mockedObservabilitySvcClient.GetComponentMetricsCalls())
func (mock *ObservabilitySvcClientMock) GetComponentMetricsCalls() []struct {
	Ctx              context.Context
	AgentComponentId string
	EnvId            string
	ProjectId        string
	Payload          spec.MetricsFilterRequest
} {
	var calls []struct {
		Ctx              context.Context
		AgentComponentId string
		EnvId            string
		ProjectId        string
		Payload          spec.MetricsFilterRequest
	}
	mock.lockGetComponentMetrics.RLock()
	calls = mock.calls.GetComponentMetrics
	mock.lockGetComponentMetrics.RUnlock()
	return calls
}
