/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMProviderListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMProviderListResponse{}

// LLMProviderListResponse struct for LLMProviderListResponse
type LLMProviderListResponse struct {
	Providers []LLMProviderResponse `json:"providers"`
	Total     int32                 `json:"total"`
	Limit     int32                 `json:"limit"`
	Offset    int32                 `json:"offset"`
}

// NewLLMProviderListResponse instantiates a new LLMProviderListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMProviderListResponse(providers []LLMProviderResponse, total int32, limit int32, offset int32) *LLMProviderListResponse {
	this := LLMProviderListResponse{}
	this.Providers = providers
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewLLMProviderListResponseWithDefaults instantiates a new LLMProviderListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMProviderListResponseWithDefaults() *LLMProviderListResponse {
	this := LLMProviderListResponse{}
	return &this
}

// GetProviders returns the Providers field value
func (o *LLMProviderListResponse) GetProviders() []LLMProviderResponse {
	if o == nil {
		var ret []LLMProviderResponse
		return ret
	}

	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value
// and a boolean to check if the value has been set.
func (o *LLMProviderListResponse) GetProvidersOk() ([]LLMProviderResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Providers, true
}

// SetProviders sets field value
func (o *LLMProviderListResponse) SetProviders(v []LLMProviderResponse) {
	o.Providers = v
}

// GetTotal returns the Total field value
func (o *LLMProviderListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *LLMProviderListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *LLMProviderListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *LLMProviderListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *LLMProviderListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *LLMProviderListResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *LLMProviderListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *LLMProviderListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *LLMProviderListResponse) SetOffset(v int32) {
	o.Offset = v
}

func (o LLMProviderListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMProviderListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["providers"] = o.Providers
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

type NullableLLMProviderListResponse struct {
	value *LLMProviderListResponse
	isSet bool
}

func (v NullableLLMProviderListResponse) Get() *LLMProviderListResponse {
	return v.value
}

func (v *NullableLLMProviderListResponse) Set(val *LLMProviderListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMProviderListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMProviderListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMProviderListResponse(val *LLMProviderListResponse) *NullableLLMProviderListResponse {
	return &NullableLLMProviderListResponse{value: val, isSet: true}
}

func (v NullableLLMProviderListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMProviderListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
