/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateLLMProviderCatalogRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateLLMProviderCatalogRequest{}

// UpdateLLMProviderCatalogRequest struct for UpdateLLMProviderCatalogRequest
type UpdateLLMProviderCatalogRequest struct {
	// Whether the provider should be available in the catalog. - true: Add to catalog (makes it discoverable for agent configurations) - false: Remove from catalog (hides from catalog queries)
	InCatalog bool `json:"inCatalog"`
}

// NewUpdateLLMProviderCatalogRequest instantiates a new UpdateLLMProviderCatalogRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateLLMProviderCatalogRequest(inCatalog bool) *UpdateLLMProviderCatalogRequest {
	this := UpdateLLMProviderCatalogRequest{}
	this.InCatalog = inCatalog
	return &this
}

// NewUpdateLLMProviderCatalogRequestWithDefaults instantiates a new UpdateLLMProviderCatalogRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateLLMProviderCatalogRequestWithDefaults() *UpdateLLMProviderCatalogRequest {
	this := UpdateLLMProviderCatalogRequest{}
	return &this
}

// GetInCatalog returns the InCatalog field value
func (o *UpdateLLMProviderCatalogRequest) GetInCatalog() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InCatalog
}

// GetInCatalogOk returns a tuple with the InCatalog field value
// and a boolean to check if the value has been set.
func (o *UpdateLLMProviderCatalogRequest) GetInCatalogOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InCatalog, true
}

// SetInCatalog sets field value
func (o *UpdateLLMProviderCatalogRequest) SetInCatalog(v bool) {
	o.InCatalog = v
}

func (o UpdateLLMProviderCatalogRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateLLMProviderCatalogRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["inCatalog"] = o.InCatalog
	return toSerialize, nil
}

type NullableUpdateLLMProviderCatalogRequest struct {
	value *UpdateLLMProviderCatalogRequest
	isSet bool
}

func (v NullableUpdateLLMProviderCatalogRequest) Get() *UpdateLLMProviderCatalogRequest {
	return v.value
}

func (v *NullableUpdateLLMProviderCatalogRequest) Set(val *UpdateLLMProviderCatalogRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLLMProviderCatalogRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLLMProviderCatalogRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLLMProviderCatalogRequest(val *UpdateLLMProviderCatalogRequest) *NullableUpdateLLMProviderCatalogRequest {
	return &NullableUpdateLLMProviderCatalogRequest{value: val, isSet: true}
}

func (v NullableUpdateLLMProviderCatalogRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateLLMProviderCatalogRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
