/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the GatewayEnvironmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayEnvironmentResponse{}

// GatewayEnvironmentResponse struct for GatewayEnvironmentResponse
type GatewayEnvironmentResponse struct {
	// Unique identifier for the environment
	Id string `json:"id"`
	// Organization UUID
	OrganizationName string `json:"organizationName"`
	// Unique environment name (lowercase, alphanumeric with hyphens)
	Name string `json:"name"`
	// Human-readable display name
	DisplayName string `json:"displayName"`
	// Optional description of the environment
	Description *string `json:"description,omitempty"`
	// Timestamp when the environment was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the environment was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// NewGatewayEnvironmentResponse instantiates a new GatewayEnvironmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayEnvironmentResponse(id string, organizationName string, name string, displayName string, createdAt time.Time, updatedAt time.Time) *GatewayEnvironmentResponse {
	this := GatewayEnvironmentResponse{}
	this.Id = id
	this.OrganizationName = organizationName
	this.Name = name
	this.DisplayName = displayName
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGatewayEnvironmentResponseWithDefaults instantiates a new GatewayEnvironmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayEnvironmentResponseWithDefaults() *GatewayEnvironmentResponse {
	this := GatewayEnvironmentResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GatewayEnvironmentResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GatewayEnvironmentResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GatewayEnvironmentResponse) SetId(v string) {
	o.Id = v
}

// GetOrganizationName returns the OrganizationName field value
func (o *GatewayEnvironmentResponse) GetOrganizationName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationName
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value
// and a boolean to check if the value has been set.
func (o *GatewayEnvironmentResponse) GetOrganizationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationName, true
}

// SetOrganizationName sets field value
func (o *GatewayEnvironmentResponse) SetOrganizationName(v string) {
	o.OrganizationName = v
}

// GetName returns the Name field value
func (o *GatewayEnvironmentResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GatewayEnvironmentResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GatewayEnvironmentResponse) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *GatewayEnvironmentResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *GatewayEnvironmentResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *GatewayEnvironmentResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GatewayEnvironmentResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayEnvironmentResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GatewayEnvironmentResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GatewayEnvironmentResponse) SetDescription(v string) {
	o.Description = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GatewayEnvironmentResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GatewayEnvironmentResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GatewayEnvironmentResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GatewayEnvironmentResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GatewayEnvironmentResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GatewayEnvironmentResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o GatewayEnvironmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayEnvironmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["organizationName"] = o.OrganizationName
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

type NullableGatewayEnvironmentResponse struct {
	value *GatewayEnvironmentResponse
	isSet bool
}

func (v NullableGatewayEnvironmentResponse) Get() *GatewayEnvironmentResponse {
	return v.value
}

func (v *NullableGatewayEnvironmentResponse) Set(val *GatewayEnvironmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayEnvironmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayEnvironmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayEnvironmentResponse(val *GatewayEnvironmentResponse) *NullableGatewayEnvironmentResponse {
	return &NullableGatewayEnvironmentResponse{value: val, isSet: true}
}

func (v NullableGatewayEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayEnvironmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
