/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateMonitorRequestLlmProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMonitorRequestLlmProvider{}

// UpdateMonitorRequestLlmProvider struct for UpdateMonitorRequestLlmProvider
type UpdateMonitorRequestLlmProvider struct {
	// Handle of the org-level LLM provider to use for LLM-judge evaluators
	ProviderName string `json:"providerName"`
}

// NewUpdateMonitorRequestLlmProvider instantiates a new UpdateMonitorRequestLlmProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMonitorRequestLlmProvider(providerName string) *UpdateMonitorRequestLlmProvider {
	this := UpdateMonitorRequestLlmProvider{}
	this.ProviderName = providerName
	return &this
}

// NewUpdateMonitorRequestLlmProviderWithDefaults instantiates a new UpdateMonitorRequestLlmProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMonitorRequestLlmProviderWithDefaults() *UpdateMonitorRequestLlmProvider {
	this := UpdateMonitorRequestLlmProvider{}
	return &this
}

// GetProviderName returns the ProviderName field value
func (o *UpdateMonitorRequestLlmProvider) GetProviderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderName
}

// GetProviderNameOk returns a tuple with the ProviderName field value
// and a boolean to check if the value has been set.
func (o *UpdateMonitorRequestLlmProvider) GetProviderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderName, true
}

// SetProviderName sets field value
func (o *UpdateMonitorRequestLlmProvider) SetProviderName(v string) {
	o.ProviderName = v
}

func (o UpdateMonitorRequestLlmProvider) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMonitorRequestLlmProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["providerName"] = o.ProviderName
	return toSerialize, nil
}

type NullableUpdateMonitorRequestLlmProvider struct {
	value *UpdateMonitorRequestLlmProvider
	isSet bool
}

func (v NullableUpdateMonitorRequestLlmProvider) Get() *UpdateMonitorRequestLlmProvider {
	return v.value
}

func (v *NullableUpdateMonitorRequestLlmProvider) Set(val *UpdateMonitorRequestLlmProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMonitorRequestLlmProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMonitorRequestLlmProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMonitorRequestLlmProvider(val *UpdateMonitorRequestLlmProvider) *NullableUpdateMonitorRequestLlmProvider {
	return &NullableUpdateMonitorRequestLlmProvider{value: val, isSet: true}
}

func (v NullableUpdateMonitorRequestLlmProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMonitorRequestLlmProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
