/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the DockerConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerConfig{}

// DockerConfig struct for DockerConfig
type DockerConfig struct {
	// Path to the Dockerfile relative to the repository root
	DockerfilePath string `json:"dockerfilePath"`
	// Docker build context path
	ContextPath string `json:"contextPath"`
}

// NewDockerConfig instantiates a new DockerConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerConfig(dockerfilePath string, contextPath string) *DockerConfig {
	this := DockerConfig{}
	this.DockerfilePath = dockerfilePath
	this.ContextPath = contextPath
	return &this
}

// NewDockerConfigWithDefaults instantiates a new DockerConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerConfigWithDefaults() *DockerConfig {
	this := DockerConfig{}
	return &this
}

// GetDockerfilePath returns the DockerfilePath field value
func (o *DockerConfig) GetDockerfilePath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DockerfilePath
}

// GetDockerfilePathOk returns a tuple with the DockerfilePath field value
// and a boolean to check if the value has been set.
func (o *DockerConfig) GetDockerfilePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DockerfilePath, true
}

// SetDockerfilePath sets field value
func (o *DockerConfig) SetDockerfilePath(v string) {
	o.DockerfilePath = v
}

// GetContextPath returns the ContextPath field value
func (o *DockerConfig) GetContextPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContextPath
}

// GetContextPathOk returns a tuple with the ContextPath field value
// and a boolean to check if the value has been set.
func (o *DockerConfig) GetContextPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContextPath, true
}

// SetContextPath sets field value
func (o *DockerConfig) SetContextPath(v string) {
	o.ContextPath = v
}

func (o DockerConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dockerfilePath"] = o.DockerfilePath
	toSerialize["contextPath"] = o.ContextPath
	return toSerialize, nil
}

type NullableDockerConfig struct {
	value *DockerConfig
	isSet bool
}

func (v NullableDockerConfig) Get() *DockerConfig {
	return v.value
}

func (v *NullableDockerConfig) Set(val *DockerConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerConfig(val *DockerConfig) *NullableDockerConfig {
	return &NullableDockerConfig{value: val, isSet: true}
}

func (v NullableDockerConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
