/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the DockerBuild type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerBuild{}

// DockerBuild struct for DockerBuild
type DockerBuild struct {
	// Build method for the component
	Type   string       `json:"type"`
	Docker DockerConfig `json:"docker"`
}

// NewDockerBuild instantiates a new DockerBuild object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerBuild(type_ string, docker DockerConfig) *DockerBuild {
	this := DockerBuild{}
	this.Type = type_
	this.Docker = docker
	return &this
}

// NewDockerBuildWithDefaults instantiates a new DockerBuild object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerBuildWithDefaults() *DockerBuild {
	this := DockerBuild{}
	return &this
}

// GetType returns the Type field value
func (o *DockerBuild) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DockerBuild) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DockerBuild) SetType(v string) {
	o.Type = v
}

// GetDocker returns the Docker field value
func (o *DockerBuild) GetDocker() DockerConfig {
	if o == nil {
		var ret DockerConfig
		return ret
	}

	return o.Docker
}

// GetDockerOk returns a tuple with the Docker field value
// and a boolean to check if the value has been set.
func (o *DockerBuild) GetDockerOk() (*DockerConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Docker, true
}

// SetDocker sets field value
func (o *DockerBuild) SetDocker(v DockerConfig) {
	o.Docker = v
}

func (o DockerBuild) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerBuild) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["docker"] = o.Docker
	return toSerialize, nil
}

type NullableDockerBuild struct {
	value *DockerBuild
	isSet bool
}

func (v NullableDockerBuild) Get() *DockerBuild {
	return v.value
}

func (v *NullableDockerBuild) Set(val *DockerBuild) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerBuild) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerBuild) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerBuild(val *DockerBuild) *NullableDockerBuild {
	return &NullableDockerBuild{value: val, isSet: true}
}

func (v NullableDockerBuild) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerBuild) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
