/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the SpanContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpanContext{}

// SpanContext struct for SpanContext
type SpanContext struct {
	// Span ID within the trace
	SpanId *string `json:"spanId,omitempty"`
	// Agent name (for agent-level evaluations)
	AgentName *string `json:"agentName,omitempty"`
	// LLM model name (for agent/llm-level evaluations)
	Model *string `json:"model,omitempty"`
	// LLM vendor (for llm-level evaluations)
	Vendor *string `json:"vendor,omitempty"`
}

// NewSpanContext instantiates a new SpanContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpanContext() *SpanContext {
	this := SpanContext{}
	return &this
}

// NewSpanContextWithDefaults instantiates a new SpanContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpanContextWithDefaults() *SpanContext {
	this := SpanContext{}
	return &this
}

// GetSpanId returns the SpanId field value if set, zero value otherwise.
func (o *SpanContext) GetSpanId() string {
	if o == nil || IsNil(o.SpanId) {
		var ret string
		return ret
	}
	return *o.SpanId
}

// GetSpanIdOk returns a tuple with the SpanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpanContext) GetSpanIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpanId) {
		return nil, false
	}
	return o.SpanId, true
}

// HasSpanId returns a boolean if a field has been set.
func (o *SpanContext) HasSpanId() bool {
	if o != nil && !IsNil(o.SpanId) {
		return true
	}

	return false
}

// SetSpanId gets a reference to the given string and assigns it to the SpanId field.
func (o *SpanContext) SetSpanId(v string) {
	o.SpanId = &v
}

// GetAgentName returns the AgentName field value if set, zero value otherwise.
func (o *SpanContext) GetAgentName() string {
	if o == nil || IsNil(o.AgentName) {
		var ret string
		return ret
	}
	return *o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpanContext) GetAgentNameOk() (*string, bool) {
	if o == nil || IsNil(o.AgentName) {
		return nil, false
	}
	return o.AgentName, true
}

// HasAgentName returns a boolean if a field has been set.
func (o *SpanContext) HasAgentName() bool {
	if o != nil && !IsNil(o.AgentName) {
		return true
	}

	return false
}

// SetAgentName gets a reference to the given string and assigns it to the AgentName field.
func (o *SpanContext) SetAgentName(v string) {
	o.AgentName = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *SpanContext) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpanContext) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *SpanContext) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *SpanContext) SetModel(v string) {
	o.Model = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *SpanContext) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpanContext) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *SpanContext) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *SpanContext) SetVendor(v string) {
	o.Vendor = &v
}

func (o SpanContext) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpanContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SpanId) {
		toSerialize["spanId"] = o.SpanId
	}
	if !IsNil(o.AgentName) {
		toSerialize["agentName"] = o.AgentName
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	return toSerialize, nil
}

type NullableSpanContext struct {
	value *SpanContext
	isSet bool
}

func (v NullableSpanContext) Get() *SpanContext {
	return v.value
}

func (v *NullableSpanContext) Set(val *SpanContext) {
	v.value = val
	v.isSet = true
}

func (v NullableSpanContext) IsSet() bool {
	return v.isSet
}

func (v *NullableSpanContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpanContext(val *SpanContext) *NullableSpanContext {
	return &NullableSpanContext{value: val, isSet: true}
}

func (v NullableSpanContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpanContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
