/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMPolicyDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMPolicyDefinition{}

// LLMPolicyDefinition struct for LLMPolicyDefinition
type LLMPolicyDefinition struct {
	// Policy name
	Name string `json:"name"`
	// Policy version
	Version string `json:"version"`
	// Human-readable policy name
	DisplayName *string `json:"displayName,omitempty"`
	// Policy description
	Description *string `json:"description,omitempty"`
	// Policy hub categories; empty when the hub does not know the policy
	Categories []string `json:"categories,omitempty"`
	// Gateway config keys this policy reads with no default, so an operator must set them on the gateway for the policy to work. Empty when the policy needs no gateway configuration. Whether the keys are set on a given gateway is not known.
	RequiredSystemConfig []string `json:"requiredSystemConfig,omitempty"`
	// JSON-Schema describing the user-configurable parameters
	Parameters map[string]interface{} `json:"parameters,omitempty"`
	// JSON-Schema describing operator-level (gateway config) parameters
	SystemParameters map[string]interface{} `json:"systemParameters,omitempty"`
}

// NewLLMPolicyDefinition instantiates a new LLMPolicyDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMPolicyDefinition(name string, version string) *LLMPolicyDefinition {
	this := LLMPolicyDefinition{}
	this.Name = name
	this.Version = version
	return &this
}

// NewLLMPolicyDefinitionWithDefaults instantiates a new LLMPolicyDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMPolicyDefinitionWithDefaults() *LLMPolicyDefinition {
	this := LLMPolicyDefinition{}
	return &this
}

// GetName returns the Name field value
func (o *LLMPolicyDefinition) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LLMPolicyDefinition) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LLMPolicyDefinition) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *LLMPolicyDefinition) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *LLMPolicyDefinition) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *LLMPolicyDefinition) SetVersion(v string) {
	o.Version = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *LLMPolicyDefinition) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMPolicyDefinition) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *LLMPolicyDefinition) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *LLMPolicyDefinition) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *LLMPolicyDefinition) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMPolicyDefinition) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *LLMPolicyDefinition) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *LLMPolicyDefinition) SetDescription(v string) {
	o.Description = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *LLMPolicyDefinition) GetCategories() []string {
	if o == nil || IsNil(o.Categories) {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMPolicyDefinition) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *LLMPolicyDefinition) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *LLMPolicyDefinition) SetCategories(v []string) {
	o.Categories = v
}

// GetRequiredSystemConfig returns the RequiredSystemConfig field value if set, zero value otherwise.
func (o *LLMPolicyDefinition) GetRequiredSystemConfig() []string {
	if o == nil || IsNil(o.RequiredSystemConfig) {
		var ret []string
		return ret
	}
	return o.RequiredSystemConfig
}

// GetRequiredSystemConfigOk returns a tuple with the RequiredSystemConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMPolicyDefinition) GetRequiredSystemConfigOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredSystemConfig) {
		return nil, false
	}
	return o.RequiredSystemConfig, true
}

// HasRequiredSystemConfig returns a boolean if a field has been set.
func (o *LLMPolicyDefinition) HasRequiredSystemConfig() bool {
	if o != nil && !IsNil(o.RequiredSystemConfig) {
		return true
	}

	return false
}

// SetRequiredSystemConfig gets a reference to the given []string and assigns it to the RequiredSystemConfig field.
func (o *LLMPolicyDefinition) SetRequiredSystemConfig(v []string) {
	o.RequiredSystemConfig = v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *LLMPolicyDefinition) GetParameters() map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMPolicyDefinition) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *LLMPolicyDefinition) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *LLMPolicyDefinition) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

// GetSystemParameters returns the SystemParameters field value if set, zero value otherwise.
func (o *LLMPolicyDefinition) GetSystemParameters() map[string]interface{} {
	if o == nil || IsNil(o.SystemParameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.SystemParameters
}

// GetSystemParametersOk returns a tuple with the SystemParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMPolicyDefinition) GetSystemParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SystemParameters) {
		return map[string]interface{}{}, false
	}
	return o.SystemParameters, true
}

// HasSystemParameters returns a boolean if a field has been set.
func (o *LLMPolicyDefinition) HasSystemParameters() bool {
	if o != nil && !IsNil(o.SystemParameters) {
		return true
	}

	return false
}

// SetSystemParameters gets a reference to the given map[string]interface{} and assigns it to the SystemParameters field.
func (o *LLMPolicyDefinition) SetSystemParameters(v map[string]interface{}) {
	o.SystemParameters = v
}

func (o LLMPolicyDefinition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMPolicyDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.RequiredSystemConfig) {
		toSerialize["requiredSystemConfig"] = o.RequiredSystemConfig
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.SystemParameters) {
		toSerialize["systemParameters"] = o.SystemParameters
	}
	return toSerialize, nil
}

type NullableLLMPolicyDefinition struct {
	value *LLMPolicyDefinition
	isSet bool
}

func (v NullableLLMPolicyDefinition) Get() *LLMPolicyDefinition {
	return v.value
}

func (v *NullableLLMPolicyDefinition) Set(val *LLMPolicyDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMPolicyDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMPolicyDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMPolicyDefinition(val *LLMPolicyDefinition) *NullableLLMPolicyDefinition {
	return &NullableLLMPolicyDefinition{value: val, isSet: true}
}

func (v NullableLLMPolicyDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMPolicyDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
