/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the DeploymentSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentSummary{}

// DeploymentSummary struct for DeploymentSummary
type DeploymentSummary struct {
	// Gateway UUID
	GatewayId string `json:"gatewayId"`
	// Gateway name/identifier
	GatewayName string `json:"gatewayName"`
	// Environment name (from gateway name or properties)
	EnvironmentName *string `json:"environmentName,omitempty"`
	// Deployment status
	Status string `json:"status"`
	// Gateway virtual host
	Vhost *string `json:"vhost,omitempty"`
}

// NewDeploymentSummary instantiates a new DeploymentSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentSummary(gatewayId string, gatewayName string, status string) *DeploymentSummary {
	this := DeploymentSummary{}
	this.GatewayId = gatewayId
	this.GatewayName = gatewayName
	this.Status = status
	return &this
}

// NewDeploymentSummaryWithDefaults instantiates a new DeploymentSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentSummaryWithDefaults() *DeploymentSummary {
	this := DeploymentSummary{}
	return &this
}

// GetGatewayId returns the GatewayId field value
func (o *DeploymentSummary) GetGatewayId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value
// and a boolean to check if the value has been set.
func (o *DeploymentSummary) GetGatewayIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayId, true
}

// SetGatewayId sets field value
func (o *DeploymentSummary) SetGatewayId(v string) {
	o.GatewayId = v
}

// GetGatewayName returns the GatewayName field value
func (o *DeploymentSummary) GetGatewayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayName
}

// GetGatewayNameOk returns a tuple with the GatewayName field value
// and a boolean to check if the value has been set.
func (o *DeploymentSummary) GetGatewayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayName, true
}

// SetGatewayName sets field value
func (o *DeploymentSummary) SetGatewayName(v string) {
	o.GatewayName = v
}

// GetEnvironmentName returns the EnvironmentName field value if set, zero value otherwise.
func (o *DeploymentSummary) GetEnvironmentName() string {
	if o == nil || IsNil(o.EnvironmentName) {
		var ret string
		return ret
	}
	return *o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentSummary) GetEnvironmentNameOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentName) {
		return nil, false
	}
	return o.EnvironmentName, true
}

// HasEnvironmentName returns a boolean if a field has been set.
func (o *DeploymentSummary) HasEnvironmentName() bool {
	if o != nil && !IsNil(o.EnvironmentName) {
		return true
	}

	return false
}

// SetEnvironmentName gets a reference to the given string and assigns it to the EnvironmentName field.
func (o *DeploymentSummary) SetEnvironmentName(v string) {
	o.EnvironmentName = &v
}

// GetStatus returns the Status field value
func (o *DeploymentSummary) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DeploymentSummary) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DeploymentSummary) SetStatus(v string) {
	o.Status = v
}

// GetVhost returns the Vhost field value if set, zero value otherwise.
func (o *DeploymentSummary) GetVhost() string {
	if o == nil || IsNil(o.Vhost) {
		var ret string
		return ret
	}
	return *o.Vhost
}

// GetVhostOk returns a tuple with the Vhost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentSummary) GetVhostOk() (*string, bool) {
	if o == nil || IsNil(o.Vhost) {
		return nil, false
	}
	return o.Vhost, true
}

// HasVhost returns a boolean if a field has been set.
func (o *DeploymentSummary) HasVhost() bool {
	if o != nil && !IsNil(o.Vhost) {
		return true
	}

	return false
}

// SetVhost gets a reference to the given string and assigns it to the Vhost field.
func (o *DeploymentSummary) SetVhost(v string) {
	o.Vhost = &v
}

func (o DeploymentSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gatewayId"] = o.GatewayId
	toSerialize["gatewayName"] = o.GatewayName
	if !IsNil(o.EnvironmentName) {
		toSerialize["environmentName"] = o.EnvironmentName
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.Vhost) {
		toSerialize["vhost"] = o.Vhost
	}
	return toSerialize, nil
}

type NullableDeploymentSummary struct {
	value *DeploymentSummary
	isSet bool
}

func (v NullableDeploymentSummary) Get() *DeploymentSummary {
	return v.value
}

func (v *NullableDeploymentSummary) Set(val *DeploymentSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentSummary(val *DeploymentSummary) *NullableDeploymentSummary {
	return &NullableDeploymentSummary{value: val, isSet: true}
}

func (v NullableDeploymentSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
