/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the SpanStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpanStatus{}

// SpanStatus struct for SpanStatus
type SpanStatus struct {
	// Whether the span has an error
	Error bool `json:"error"`
	// Type of error if present
	ErrorType *string `json:"errorType,omitempty"`
}

// NewSpanStatus instantiates a new SpanStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpanStatus(error_ bool) *SpanStatus {
	this := SpanStatus{}
	this.Error = error_
	return &this
}

// NewSpanStatusWithDefaults instantiates a new SpanStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpanStatusWithDefaults() *SpanStatus {
	this := SpanStatus{}
	return &this
}

// GetError returns the Error field value
func (o *SpanStatus) GetError() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *SpanStatus) GetErrorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *SpanStatus) SetError(v bool) {
	o.Error = v
}

// GetErrorType returns the ErrorType field value if set, zero value otherwise.
func (o *SpanStatus) GetErrorType() string {
	if o == nil || IsNil(o.ErrorType) {
		var ret string
		return ret
	}
	return *o.ErrorType
}

// GetErrorTypeOk returns a tuple with the ErrorType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpanStatus) GetErrorTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorType) {
		return nil, false
	}
	return o.ErrorType, true
}

// HasErrorType returns a boolean if a field has been set.
func (o *SpanStatus) HasErrorType() bool {
	if o != nil && !IsNil(o.ErrorType) {
		return true
	}

	return false
}

// SetErrorType gets a reference to the given string and assigns it to the ErrorType field.
func (o *SpanStatus) SetErrorType(v string) {
	o.ErrorType = &v
}

func (o SpanStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpanStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	if !IsNil(o.ErrorType) {
		toSerialize["errorType"] = o.ErrorType
	}
	return toSerialize, nil
}

type NullableSpanStatus struct {
	value *SpanStatus
	isSet bool
}

func (v NullableSpanStatus) Get() *SpanStatus {
	return v.value
}

func (v *NullableSpanStatus) Set(val *SpanStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSpanStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSpanStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpanStatus(val *SpanStatus) *NullableSpanStatus {
	return &NullableSpanStatus{value: val, isSet: true}
}

func (v NullableSpanStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpanStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
