/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the WebhookDeliveryListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDeliveryListResponse{}

// WebhookDeliveryListResponse struct for WebhookDeliveryListResponse
type WebhookDeliveryListResponse struct {
	Deliveries []WebhookDeliveryResponse `json:"deliveries"`
}

// NewWebhookDeliveryListResponse instantiates a new WebhookDeliveryListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDeliveryListResponse(deliveries []WebhookDeliveryResponse) *WebhookDeliveryListResponse {
	this := WebhookDeliveryListResponse{}
	this.Deliveries = deliveries
	return &this
}

// NewWebhookDeliveryListResponseWithDefaults instantiates a new WebhookDeliveryListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveryListResponseWithDefaults() *WebhookDeliveryListResponse {
	this := WebhookDeliveryListResponse{}
	return &this
}

// GetDeliveries returns the Deliveries field value
func (o *WebhookDeliveryListResponse) GetDeliveries() []WebhookDeliveryResponse {
	if o == nil {
		var ret []WebhookDeliveryResponse
		return ret
	}

	return o.Deliveries
}

// GetDeliveriesOk returns a tuple with the Deliveries field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryListResponse) GetDeliveriesOk() ([]WebhookDeliveryResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deliveries, true
}

// SetDeliveries sets field value
func (o *WebhookDeliveryListResponse) SetDeliveries(v []WebhookDeliveryResponse) {
	o.Deliveries = v
}

func (o WebhookDeliveryListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDeliveryListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deliveries"] = o.Deliveries
	return toSerialize, nil
}

type NullableWebhookDeliveryListResponse struct {
	value *WebhookDeliveryListResponse
	isSet bool
}

func (v NullableWebhookDeliveryListResponse) Get() *WebhookDeliveryListResponse {
	return v.value
}

func (v *NullableWebhookDeliveryListResponse) Set(val *WebhookDeliveryListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDeliveryListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDeliveryListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDeliveryListResponse(val *WebhookDeliveryListResponse) *NullableWebhookDeliveryListResponse {
	return &NullableWebhookDeliveryListResponse{value: val, isSet: true}
}

func (v NullableWebhookDeliveryListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDeliveryListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
