/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpstreamAuth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpstreamAuth{}

// UpstreamAuth struct for UpstreamAuth
type UpstreamAuth struct {
	// Authentication type
	Type string `json:"type"`
	// Authentication header name
	Header *string `json:"header,omitempty"`
	// Authentication value/token
	Value *string `json:"value,omitempty"`
}

// NewUpstreamAuth instantiates a new UpstreamAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpstreamAuth(type_ string) *UpstreamAuth {
	this := UpstreamAuth{}
	this.Type = type_
	return &this
}

// NewUpstreamAuthWithDefaults instantiates a new UpstreamAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpstreamAuthWithDefaults() *UpstreamAuth {
	this := UpstreamAuth{}
	return &this
}

// GetType returns the Type field value
func (o *UpstreamAuth) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpstreamAuth) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpstreamAuth) SetType(v string) {
	o.Type = v
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *UpstreamAuth) GetHeader() string {
	if o == nil || IsNil(o.Header) {
		var ret string
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpstreamAuth) GetHeaderOk() (*string, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *UpstreamAuth) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given string and assigns it to the Header field.
func (o *UpstreamAuth) SetHeader(v string) {
	o.Header = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UpstreamAuth) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpstreamAuth) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *UpstreamAuth) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *UpstreamAuth) SetValue(v string) {
	o.Value = &v
}

func (o UpstreamAuth) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpstreamAuth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableUpstreamAuth struct {
	value *UpstreamAuth
	isSet bool
}

func (v NullableUpstreamAuth) Get() *UpstreamAuth {
	return v.value
}

func (v *NullableUpstreamAuth) Set(val *UpstreamAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableUpstreamAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableUpstreamAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpstreamAuth(val *UpstreamAuth) *NullableUpstreamAuth {
	return &NullableUpstreamAuth{value: val, isSet: true}
}

func (v NullableUpstreamAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpstreamAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
