/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMPolicyPath type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMPolicyPath{}

// LLMPolicyPath struct for LLMPolicyPath
type LLMPolicyPath struct {
	// Path pattern
	Path    string   `json:"path"`
	Methods []string `json:"methods"`
	// Policy parameters
	Params map[string]interface{} `json:"params,omitempty"`
}

// NewLLMPolicyPath instantiates a new LLMPolicyPath object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMPolicyPath(path string, methods []string) *LLMPolicyPath {
	this := LLMPolicyPath{}
	this.Path = path
	this.Methods = methods
	return &this
}

// NewLLMPolicyPathWithDefaults instantiates a new LLMPolicyPath object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMPolicyPathWithDefaults() *LLMPolicyPath {
	this := LLMPolicyPath{}
	return &this
}

// GetPath returns the Path field value
func (o *LLMPolicyPath) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *LLMPolicyPath) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *LLMPolicyPath) SetPath(v string) {
	o.Path = v
}

// GetMethods returns the Methods field value
func (o *LLMPolicyPath) GetMethods() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Methods
}

// GetMethodsOk returns a tuple with the Methods field value
// and a boolean to check if the value has been set.
func (o *LLMPolicyPath) GetMethodsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Methods, true
}

// SetMethods sets field value
func (o *LLMPolicyPath) SetMethods(v []string) {
	o.Methods = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *LLMPolicyPath) GetParams() map[string]interface{} {
	if o == nil || IsNil(o.Params) {
		var ret map[string]interface{}
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMPolicyPath) GetParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Params) {
		return map[string]interface{}{}, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *LLMPolicyPath) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given map[string]interface{} and assigns it to the Params field.
func (o *LLMPolicyPath) SetParams(v map[string]interface{}) {
	o.Params = v
}

func (o LLMPolicyPath) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMPolicyPath) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	toSerialize["methods"] = o.Methods
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	return toSerialize, nil
}

type NullableLLMPolicyPath struct {
	value *LLMPolicyPath
	isSet bool
}

func (v NullableLLMPolicyPath) Get() *LLMPolicyPath {
	return v.value
}

func (v *NullableLLMPolicyPath) Set(val *LLMPolicyPath) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMPolicyPath) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMPolicyPath) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMPolicyPath(val *LLMPolicyPath) *NullableLLMPolicyPath {
	return &NullableLLMPolicyPath{value: val, isSet: true}
}

func (v NullableLLMPolicyPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMPolicyPath) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
