/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RequestRateLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestRateLimit{}

// RequestRateLimit struct for RequestRateLimit
type RequestRateLimit struct {
	// Whether request rate limiting is enabled
	Enabled bool `json:"enabled"`
	// Maximum number of requests
	Count int32                `json:"count"`
	Reset RateLimitResetWindow `json:"reset"`
}

// NewRequestRateLimit instantiates a new RequestRateLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestRateLimit(enabled bool, count int32, reset RateLimitResetWindow) *RequestRateLimit {
	this := RequestRateLimit{}
	this.Enabled = enabled
	this.Count = count
	this.Reset = reset
	return &this
}

// NewRequestRateLimitWithDefaults instantiates a new RequestRateLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestRateLimitWithDefaults() *RequestRateLimit {
	this := RequestRateLimit{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *RequestRateLimit) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *RequestRateLimit) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *RequestRateLimit) SetEnabled(v bool) {
	o.Enabled = v
}

// GetCount returns the Count field value
func (o *RequestRateLimit) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *RequestRateLimit) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *RequestRateLimit) SetCount(v int32) {
	o.Count = v
}

// GetReset returns the Reset field value
func (o *RequestRateLimit) GetReset() RateLimitResetWindow {
	if o == nil {
		var ret RateLimitResetWindow
		return ret
	}

	return o.Reset
}

// GetResetOk returns a tuple with the Reset field value
// and a boolean to check if the value has been set.
func (o *RequestRateLimit) GetResetOk() (*RateLimitResetWindow, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reset, true
}

// SetReset sets field value
func (o *RequestRateLimit) SetReset(v RateLimitResetWindow) {
	o.Reset = v
}

func (o RequestRateLimit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestRateLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["count"] = o.Count
	toSerialize["reset"] = o.Reset
	return toSerialize, nil
}

type NullableRequestRateLimit struct {
	value *RequestRateLimit
	isSet bool
}

func (v NullableRequestRateLimit) Get() *RequestRateLimit {
	return v.value
}

func (v *NullableRequestRateLimit) Set(val *RequestRateLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestRateLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestRateLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestRateLimit(val *RequestRateLimit) *NullableRequestRateLimit {
	return &NullableRequestRateLimit{value: val, isSet: true}
}

func (v NullableRequestRateLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestRateLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
