/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RuntimeConfigurationWithoutEnv type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RuntimeConfigurationWithoutEnv{}

// RuntimeConfigurationWithoutEnv struct for RuntimeConfigurationWithoutEnv
type RuntimeConfigurationWithoutEnv struct {
	RunCommand      *string `json:"runCommand,omitempty"`
	LanguageVersion *string `json:"languageVersion,omitempty"`
	Language        string  `json:"language"`
}

// NewRuntimeConfigurationWithoutEnv instantiates a new RuntimeConfigurationWithoutEnv object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuntimeConfigurationWithoutEnv(language string) *RuntimeConfigurationWithoutEnv {
	this := RuntimeConfigurationWithoutEnv{}
	this.Language = language
	return &this
}

// NewRuntimeConfigurationWithoutEnvWithDefaults instantiates a new RuntimeConfigurationWithoutEnv object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuntimeConfigurationWithoutEnvWithDefaults() *RuntimeConfigurationWithoutEnv {
	this := RuntimeConfigurationWithoutEnv{}
	return &this
}

// GetRunCommand returns the RunCommand field value if set, zero value otherwise.
func (o *RuntimeConfigurationWithoutEnv) GetRunCommand() string {
	if o == nil || IsNil(o.RunCommand) {
		var ret string
		return ret
	}
	return *o.RunCommand
}

// GetRunCommandOk returns a tuple with the RunCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuntimeConfigurationWithoutEnv) GetRunCommandOk() (*string, bool) {
	if o == nil || IsNil(o.RunCommand) {
		return nil, false
	}
	return o.RunCommand, true
}

// HasRunCommand returns a boolean if a field has been set.
func (o *RuntimeConfigurationWithoutEnv) HasRunCommand() bool {
	if o != nil && !IsNil(o.RunCommand) {
		return true
	}

	return false
}

// SetRunCommand gets a reference to the given string and assigns it to the RunCommand field.
func (o *RuntimeConfigurationWithoutEnv) SetRunCommand(v string) {
	o.RunCommand = &v
}

// GetLanguageVersion returns the LanguageVersion field value if set, zero value otherwise.
func (o *RuntimeConfigurationWithoutEnv) GetLanguageVersion() string {
	if o == nil || IsNil(o.LanguageVersion) {
		var ret string
		return ret
	}
	return *o.LanguageVersion
}

// GetLanguageVersionOk returns a tuple with the LanguageVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuntimeConfigurationWithoutEnv) GetLanguageVersionOk() (*string, bool) {
	if o == nil || IsNil(o.LanguageVersion) {
		return nil, false
	}
	return o.LanguageVersion, true
}

// HasLanguageVersion returns a boolean if a field has been set.
func (o *RuntimeConfigurationWithoutEnv) HasLanguageVersion() bool {
	if o != nil && !IsNil(o.LanguageVersion) {
		return true
	}

	return false
}

// SetLanguageVersion gets a reference to the given string and assigns it to the LanguageVersion field.
func (o *RuntimeConfigurationWithoutEnv) SetLanguageVersion(v string) {
	o.LanguageVersion = &v
}

// GetLanguage returns the Language field value
func (o *RuntimeConfigurationWithoutEnv) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *RuntimeConfigurationWithoutEnv) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *RuntimeConfigurationWithoutEnv) SetLanguage(v string) {
	o.Language = v
}

func (o RuntimeConfigurationWithoutEnv) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RuntimeConfigurationWithoutEnv) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RunCommand) {
		toSerialize["runCommand"] = o.RunCommand
	}
	if !IsNil(o.LanguageVersion) {
		toSerialize["languageVersion"] = o.LanguageVersion
	}
	toSerialize["language"] = o.Language
	return toSerialize, nil
}

type NullableRuntimeConfigurationWithoutEnv struct {
	value *RuntimeConfigurationWithoutEnv
	isSet bool
}

func (v NullableRuntimeConfigurationWithoutEnv) Get() *RuntimeConfigurationWithoutEnv {
	return v.value
}

func (v *NullableRuntimeConfigurationWithoutEnv) Set(val *RuntimeConfigurationWithoutEnv) {
	v.value = val
	v.isSet = true
}

func (v NullableRuntimeConfigurationWithoutEnv) IsSet() bool {
	return v.isSet
}

func (v *NullableRuntimeConfigurationWithoutEnv) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuntimeConfigurationWithoutEnv(val *RuntimeConfigurationWithoutEnv) *NullableRuntimeConfigurationWithoutEnv {
	return &NullableRuntimeConfigurationWithoutEnv{value: val, isSet: true}
}

func (v NullableRuntimeConfigurationWithoutEnv) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuntimeConfigurationWithoutEnv) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
