/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RateLimitingResourceLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RateLimitingResourceLimit{}

// RateLimitingResourceLimit struct for RateLimitingResourceLimit
type RateLimitingResourceLimit struct {
	// Resource identifier
	Resource string                  `json:"resource"`
	Limit    RateLimitingLimitConfig `json:"limit"`
}

// NewRateLimitingResourceLimit instantiates a new RateLimitingResourceLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRateLimitingResourceLimit(resource string, limit RateLimitingLimitConfig) *RateLimitingResourceLimit {
	this := RateLimitingResourceLimit{}
	this.Resource = resource
	this.Limit = limit
	return &this
}

// NewRateLimitingResourceLimitWithDefaults instantiates a new RateLimitingResourceLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRateLimitingResourceLimitWithDefaults() *RateLimitingResourceLimit {
	this := RateLimitingResourceLimit{}
	return &this
}

// GetResource returns the Resource field value
func (o *RateLimitingResourceLimit) GetResource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *RateLimitingResourceLimit) GetResourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *RateLimitingResourceLimit) SetResource(v string) {
	o.Resource = v
}

// GetLimit returns the Limit field value
func (o *RateLimitingResourceLimit) GetLimit() RateLimitingLimitConfig {
	if o == nil {
		var ret RateLimitingLimitConfig
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *RateLimitingResourceLimit) GetLimitOk() (*RateLimitingLimitConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *RateLimitingResourceLimit) SetLimit(v RateLimitingLimitConfig) {
	o.Limit = v
}

func (o RateLimitingResourceLimit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RateLimitingResourceLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource"] = o.Resource
	toSerialize["limit"] = o.Limit
	return toSerialize, nil
}

type NullableRateLimitingResourceLimit struct {
	value *RateLimitingResourceLimit
	isSet bool
}

func (v NullableRateLimitingResourceLimit) Get() *RateLimitingResourceLimit {
	return v.value
}

func (v *NullableRateLimitingResourceLimit) Set(val *RateLimitingResourceLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableRateLimitingResourceLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableRateLimitingResourceLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRateLimitingResourceLimit(val *RateLimitingResourceLimit) *NullableRateLimitingResourceLimit {
	return &NullableRateLimitingResourceLimit{value: val, isSet: true}
}

func (v NullableRateLimitingResourceLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRateLimitingResourceLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
