/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the CostRateLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CostRateLimit{}

// CostRateLimit struct for CostRateLimit
type CostRateLimit struct {
	// Whether cost rate limiting is enabled
	Enabled bool `json:"enabled"`
	// Maximum cost amount
	Amount float64              `json:"amount"`
	Reset  RateLimitResetWindow `json:"reset"`
}

// NewCostRateLimit instantiates a new CostRateLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCostRateLimit(enabled bool, amount float64, reset RateLimitResetWindow) *CostRateLimit {
	this := CostRateLimit{}
	this.Enabled = enabled
	this.Amount = amount
	this.Reset = reset
	return &this
}

// NewCostRateLimitWithDefaults instantiates a new CostRateLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCostRateLimitWithDefaults() *CostRateLimit {
	this := CostRateLimit{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *CostRateLimit) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CostRateLimit) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *CostRateLimit) SetEnabled(v bool) {
	o.Enabled = v
}

// GetAmount returns the Amount field value
func (o *CostRateLimit) GetAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CostRateLimit) GetAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CostRateLimit) SetAmount(v float64) {
	o.Amount = v
}

// GetReset returns the Reset field value
func (o *CostRateLimit) GetReset() RateLimitResetWindow {
	if o == nil {
		var ret RateLimitResetWindow
		return ret
	}

	return o.Reset
}

// GetResetOk returns a tuple with the Reset field value
// and a boolean to check if the value has been set.
func (o *CostRateLimit) GetResetOk() (*RateLimitResetWindow, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reset, true
}

// SetReset sets field value
func (o *CostRateLimit) SetReset(v RateLimitResetWindow) {
	o.Reset = v
}

func (o CostRateLimit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CostRateLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["amount"] = o.Amount
	toSerialize["reset"] = o.Reset
	return toSerialize, nil
}

type NullableCostRateLimit struct {
	value *CostRateLimit
	isSet bool
}

func (v NullableCostRateLimit) Get() *CostRateLimit {
	return v.value
}

func (v *NullableCostRateLimit) Set(val *CostRateLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableCostRateLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableCostRateLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCostRateLimit(val *CostRateLimit) *NullableCostRateLimit {
	return &NullableCostRateLimit{value: val, isSet: true}
}

func (v NullableCostRateLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCostRateLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
