/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the CreateGitSecretRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateGitSecretRequest{}

// CreateGitSecretRequest struct for CreateGitSecretRequest
type CreateGitSecretRequest struct {
	// User-provided name for the git secret
	Name string `json:"name"`
	// Authentication type
	Type        string         `json:"type"`
	Credentials GitCredentials `json:"credentials"`
}

// NewCreateGitSecretRequest instantiates a new CreateGitSecretRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGitSecretRequest(name string, type_ string, credentials GitCredentials) *CreateGitSecretRequest {
	this := CreateGitSecretRequest{}
	this.Name = name
	this.Type = type_
	this.Credentials = credentials
	return &this
}

// NewCreateGitSecretRequestWithDefaults instantiates a new CreateGitSecretRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGitSecretRequestWithDefaults() *CreateGitSecretRequest {
	this := CreateGitSecretRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateGitSecretRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateGitSecretRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateGitSecretRequest) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *CreateGitSecretRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateGitSecretRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateGitSecretRequest) SetType(v string) {
	o.Type = v
}

// GetCredentials returns the Credentials field value
func (o *CreateGitSecretRequest) GetCredentials() GitCredentials {
	if o == nil {
		var ret GitCredentials
		return ret
	}

	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *CreateGitSecretRequest) GetCredentialsOk() (*GitCredentials, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credentials, true
}

// SetCredentials sets field value
func (o *CreateGitSecretRequest) SetCredentials(v GitCredentials) {
	o.Credentials = v
}

func (o CreateGitSecretRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateGitSecretRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["credentials"] = o.Credentials
	return toSerialize, nil
}

type NullableCreateGitSecretRequest struct {
	value *CreateGitSecretRequest
	isSet bool
}

func (v NullableCreateGitSecretRequest) Get() *CreateGitSecretRequest {
	return v.value
}

func (v *NullableCreateGitSecretRequest) Set(val *CreateGitSecretRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGitSecretRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGitSecretRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGitSecretRequest(val *CreateGitSecretRequest) *NullableCreateGitSecretRequest {
	return &NullableCreateGitSecretRequest{value: val, isSet: true}
}

func (v NullableCreateGitSecretRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGitSecretRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
