/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the GatewayTokenInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayTokenInfo{}

// GatewayTokenInfo struct for GatewayTokenInfo
type GatewayTokenInfo struct {
	// Unique token identifier (UUID)
	Id string `json:"id"`
	// Current token status
	Status string `json:"status"`
	// Timestamp when the token was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the token was revoked (null if still active)
	RevokedAt NullableTime `json:"revokedAt,omitempty"`
}

// NewGatewayTokenInfo instantiates a new GatewayTokenInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayTokenInfo(id string, status string, createdAt time.Time) *GatewayTokenInfo {
	this := GatewayTokenInfo{}
	this.Id = id
	this.Status = status
	this.CreatedAt = createdAt
	return &this
}

// NewGatewayTokenInfoWithDefaults instantiates a new GatewayTokenInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayTokenInfoWithDefaults() *GatewayTokenInfo {
	this := GatewayTokenInfo{}
	return &this
}

// GetId returns the Id field value
func (o *GatewayTokenInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GatewayTokenInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GatewayTokenInfo) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *GatewayTokenInfo) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GatewayTokenInfo) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GatewayTokenInfo) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GatewayTokenInfo) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GatewayTokenInfo) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GatewayTokenInfo) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewayTokenInfo) GetRevokedAt() time.Time {
	if o == nil || IsNil(o.RevokedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RevokedAt.Get()
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewayTokenInfo) GetRevokedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevokedAt.Get(), o.RevokedAt.IsSet()
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *GatewayTokenInfo) HasRevokedAt() bool {
	if o != nil && o.RevokedAt.IsSet() {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given NullableTime and assigns it to the RevokedAt field.
func (o *GatewayTokenInfo) SetRevokedAt(v time.Time) {
	o.RevokedAt.Set(&v)
}

// SetRevokedAtNil sets the value for RevokedAt to be an explicit nil
func (o *GatewayTokenInfo) SetRevokedAtNil() {
	o.RevokedAt.Set(nil)
}

// UnsetRevokedAt ensures that no value is present for RevokedAt, not even an explicit nil
func (o *GatewayTokenInfo) UnsetRevokedAt() {
	o.RevokedAt.Unset()
}

func (o GatewayTokenInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayTokenInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["createdAt"] = o.CreatedAt
	if o.RevokedAt.IsSet() {
		toSerialize["revokedAt"] = o.RevokedAt.Get()
	}
	return toSerialize, nil
}

type NullableGatewayTokenInfo struct {
	value *GatewayTokenInfo
	isSet bool
}

func (v NullableGatewayTokenInfo) Get() *GatewayTokenInfo {
	return v.value
}

func (v *NullableGatewayTokenInfo) Set(val *GatewayTokenInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayTokenInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayTokenInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayTokenInfo(val *GatewayTokenInfo) *NullableGatewayTokenInfo {
	return &NullableGatewayTokenInfo{value: val, isSet: true}
}

func (v NullableGatewayTokenInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayTokenInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
