/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ResourceConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceConfig{}

// ResourceConfig struct for ResourceConfig
type ResourceConfig struct {
	Requests *ResourceRequests `json:"requests,omitempty"`
	Limits   *ResourceLimits   `json:"limits,omitempty"`
}

// NewResourceConfig instantiates a new ResourceConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceConfig() *ResourceConfig {
	this := ResourceConfig{}
	return &this
}

// NewResourceConfigWithDefaults instantiates a new ResourceConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceConfigWithDefaults() *ResourceConfig {
	this := ResourceConfig{}
	return &this
}

// GetRequests returns the Requests field value if set, zero value otherwise.
func (o *ResourceConfig) GetRequests() ResourceRequests {
	if o == nil || IsNil(o.Requests) {
		var ret ResourceRequests
		return ret
	}
	return *o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceConfig) GetRequestsOk() (*ResourceRequests, bool) {
	if o == nil || IsNil(o.Requests) {
		return nil, false
	}
	return o.Requests, true
}

// HasRequests returns a boolean if a field has been set.
func (o *ResourceConfig) HasRequests() bool {
	if o != nil && !IsNil(o.Requests) {
		return true
	}

	return false
}

// SetRequests gets a reference to the given ResourceRequests and assigns it to the Requests field.
func (o *ResourceConfig) SetRequests(v ResourceRequests) {
	o.Requests = &v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *ResourceConfig) GetLimits() ResourceLimits {
	if o == nil || IsNil(o.Limits) {
		var ret ResourceLimits
		return ret
	}
	return *o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceConfig) GetLimitsOk() (*ResourceLimits, bool) {
	if o == nil || IsNil(o.Limits) {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *ResourceConfig) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given ResourceLimits and assigns it to the Limits field.
func (o *ResourceConfig) SetLimits(v ResourceLimits) {
	o.Limits = &v
}

func (o ResourceConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Requests) {
		toSerialize["requests"] = o.Requests
	}
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	return toSerialize, nil
}

type NullableResourceConfig struct {
	value *ResourceConfig
	isSet bool
}

func (v NullableResourceConfig) Get() *ResourceConfig {
	return v.value
}

func (v *NullableResourceConfig) Set(val *ResourceConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceConfig(val *ResourceConfig) *NullableResourceConfig {
	return &NullableResourceConfig{value: val, isSet: true}
}

func (v NullableResourceConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
