/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the WebhookDeliveryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDeliveryResponse{}

// WebhookDeliveryResponse struct for WebhookDeliveryResponse
type WebhookDeliveryResponse struct {
	Id           string     `json:"id"`
	EventId      string     `json:"eventId"`
	EventType    string     `json:"eventType"`
	Status       string     `json:"status"`
	Attempts     int32      `json:"attempts"`
	ResponseCode *int32     `json:"responseCode,omitempty"`
	LastError    *string    `json:"lastError,omitempty"`
	DeliveredAt  *time.Time `json:"deliveredAt,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
}

// NewWebhookDeliveryResponse instantiates a new WebhookDeliveryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDeliveryResponse(id string, eventId string, eventType string, status string, attempts int32, createdAt time.Time, updatedAt time.Time) *WebhookDeliveryResponse {
	this := WebhookDeliveryResponse{}
	this.Id = id
	this.EventId = eventId
	this.EventType = eventType
	this.Status = status
	this.Attempts = attempts
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewWebhookDeliveryResponseWithDefaults instantiates a new WebhookDeliveryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveryResponseWithDefaults() *WebhookDeliveryResponse {
	this := WebhookDeliveryResponse{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookDeliveryResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookDeliveryResponse) SetId(v string) {
	o.Id = v
}

// GetEventId returns the EventId field value
func (o *WebhookDeliveryResponse) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *WebhookDeliveryResponse) SetEventId(v string) {
	o.EventId = v
}

// GetEventType returns the EventType field value
func (o *WebhookDeliveryResponse) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *WebhookDeliveryResponse) SetEventType(v string) {
	o.EventType = v
}

// GetStatus returns the Status field value
func (o *WebhookDeliveryResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WebhookDeliveryResponse) SetStatus(v string) {
	o.Status = v
}

// GetAttempts returns the Attempts field value
func (o *WebhookDeliveryResponse) GetAttempts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Attempts
}

// GetAttemptsOk returns a tuple with the Attempts field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attempts, true
}

// SetAttempts sets field value
func (o *WebhookDeliveryResponse) SetAttempts(v int32) {
	o.Attempts = v
}

// GetResponseCode returns the ResponseCode field value if set, zero value otherwise.
func (o *WebhookDeliveryResponse) GetResponseCode() int32 {
	if o == nil || IsNil(o.ResponseCode) {
		var ret int32
		return ret
	}
	return *o.ResponseCode
}

// GetResponseCodeOk returns a tuple with the ResponseCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetResponseCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.ResponseCode) {
		return nil, false
	}
	return o.ResponseCode, true
}

// HasResponseCode returns a boolean if a field has been set.
func (o *WebhookDeliveryResponse) HasResponseCode() bool {
	if o != nil && !IsNil(o.ResponseCode) {
		return true
	}

	return false
}

// SetResponseCode gets a reference to the given int32 and assigns it to the ResponseCode field.
func (o *WebhookDeliveryResponse) SetResponseCode(v int32) {
	o.ResponseCode = &v
}

// GetLastError returns the LastError field value if set, zero value otherwise.
func (o *WebhookDeliveryResponse) GetLastError() string {
	if o == nil || IsNil(o.LastError) {
		var ret string
		return ret
	}
	return *o.LastError
}

// GetLastErrorOk returns a tuple with the LastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetLastErrorOk() (*string, bool) {
	if o == nil || IsNil(o.LastError) {
		return nil, false
	}
	return o.LastError, true
}

// HasLastError returns a boolean if a field has been set.
func (o *WebhookDeliveryResponse) HasLastError() bool {
	if o != nil && !IsNil(o.LastError) {
		return true
	}

	return false
}

// SetLastError gets a reference to the given string and assigns it to the LastError field.
func (o *WebhookDeliveryResponse) SetLastError(v string) {
	o.LastError = &v
}

// GetDeliveredAt returns the DeliveredAt field value if set, zero value otherwise.
func (o *WebhookDeliveryResponse) GetDeliveredAt() time.Time {
	if o == nil || IsNil(o.DeliveredAt) {
		var ret time.Time
		return ret
	}
	return *o.DeliveredAt
}

// GetDeliveredAtOk returns a tuple with the DeliveredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetDeliveredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeliveredAt) {
		return nil, false
	}
	return o.DeliveredAt, true
}

// HasDeliveredAt returns a boolean if a field has been set.
func (o *WebhookDeliveryResponse) HasDeliveredAt() bool {
	if o != nil && !IsNil(o.DeliveredAt) {
		return true
	}

	return false
}

// SetDeliveredAt gets a reference to the given time.Time and assigns it to the DeliveredAt field.
func (o *WebhookDeliveryResponse) SetDeliveredAt(v time.Time) {
	o.DeliveredAt = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WebhookDeliveryResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WebhookDeliveryResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *WebhookDeliveryResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *WebhookDeliveryResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o WebhookDeliveryResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDeliveryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["eventId"] = o.EventId
	toSerialize["eventType"] = o.EventType
	toSerialize["status"] = o.Status
	toSerialize["attempts"] = o.Attempts
	if !IsNil(o.ResponseCode) {
		toSerialize["responseCode"] = o.ResponseCode
	}
	if !IsNil(o.LastError) {
		toSerialize["lastError"] = o.LastError
	}
	if !IsNil(o.DeliveredAt) {
		toSerialize["deliveredAt"] = o.DeliveredAt
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

type NullableWebhookDeliveryResponse struct {
	value *WebhookDeliveryResponse
	isSet bool
}

func (v NullableWebhookDeliveryResponse) Get() *WebhookDeliveryResponse {
	return v.value
}

func (v *NullableWebhookDeliveryResponse) Set(val *WebhookDeliveryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDeliveryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDeliveryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDeliveryResponse(val *WebhookDeliveryResponse) *NullableWebhookDeliveryResponse {
	return &NullableWebhookDeliveryResponse{value: val, isSet: true}
}

func (v NullableWebhookDeliveryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDeliveryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
