/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the TraceExportResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TraceExportResponse{}

// TraceExportResponse struct for TraceExportResponse
type TraceExportResponse struct {
	// List of complete trace objects with all span details
	Traces []FullTrace `json:"traces"`
	// Total number of traces available for export
	TotalCount int32 `json:"totalCount"`
}

// NewTraceExportResponse instantiates a new TraceExportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTraceExportResponse(traces []FullTrace, totalCount int32) *TraceExportResponse {
	this := TraceExportResponse{}
	this.Traces = traces
	this.TotalCount = totalCount
	return &this
}

// NewTraceExportResponseWithDefaults instantiates a new TraceExportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTraceExportResponseWithDefaults() *TraceExportResponse {
	this := TraceExportResponse{}
	return &this
}

// GetTraces returns the Traces field value
func (o *TraceExportResponse) GetTraces() []FullTrace {
	if o == nil {
		var ret []FullTrace
		return ret
	}

	return o.Traces
}

// GetTracesOk returns a tuple with the Traces field value
// and a boolean to check if the value has been set.
func (o *TraceExportResponse) GetTracesOk() ([]FullTrace, bool) {
	if o == nil {
		return nil, false
	}
	return o.Traces, true
}

// SetTraces sets field value
func (o *TraceExportResponse) SetTraces(v []FullTrace) {
	o.Traces = v
}

// GetTotalCount returns the TotalCount field value
func (o *TraceExportResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *TraceExportResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *TraceExportResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

func (o TraceExportResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TraceExportResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["traces"] = o.Traces
	toSerialize["totalCount"] = o.TotalCount
	return toSerialize, nil
}

type NullableTraceExportResponse struct {
	value *TraceExportResponse
	isSet bool
}

func (v NullableTraceExportResponse) Get() *TraceExportResponse {
	return v.value
}

func (v *NullableTraceExportResponse) Set(val *TraceExportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTraceExportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTraceExportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTraceExportResponse(val *TraceExportResponse) *NullableTraceExportResponse {
	return &NullableTraceExportResponse{value: val, isSet: true}
}

func (v NullableTraceExportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTraceExportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
