/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GroupedScoresResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupedScoresResponse{}

// GroupedScoresResponse struct for GroupedScoresResponse
type GroupedScoresResponse struct {
	MonitorName string            `json:"monitorName"`
	Level       string            `json:"level"`
	TimeRange   TimeRange         `json:"timeRange"`
	Groups      []ScoreLabelGroup `json:"groups"`
}

// NewGroupedScoresResponse instantiates a new GroupedScoresResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupedScoresResponse(monitorName string, level string, timeRange TimeRange, groups []ScoreLabelGroup) *GroupedScoresResponse {
	this := GroupedScoresResponse{}
	this.MonitorName = monitorName
	this.Level = level
	this.TimeRange = timeRange
	this.Groups = groups
	return &this
}

// NewGroupedScoresResponseWithDefaults instantiates a new GroupedScoresResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupedScoresResponseWithDefaults() *GroupedScoresResponse {
	this := GroupedScoresResponse{}
	return &this
}

// GetMonitorName returns the MonitorName field value
func (o *GroupedScoresResponse) GetMonitorName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MonitorName
}

// GetMonitorNameOk returns a tuple with the MonitorName field value
// and a boolean to check if the value has been set.
func (o *GroupedScoresResponse) GetMonitorNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MonitorName, true
}

// SetMonitorName sets field value
func (o *GroupedScoresResponse) SetMonitorName(v string) {
	o.MonitorName = v
}

// GetLevel returns the Level field value
func (o *GroupedScoresResponse) GetLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *GroupedScoresResponse) GetLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *GroupedScoresResponse) SetLevel(v string) {
	o.Level = v
}

// GetTimeRange returns the TimeRange field value
func (o *GroupedScoresResponse) GetTimeRange() TimeRange {
	if o == nil {
		var ret TimeRange
		return ret
	}

	return o.TimeRange
}

// GetTimeRangeOk returns a tuple with the TimeRange field value
// and a boolean to check if the value has been set.
func (o *GroupedScoresResponse) GetTimeRangeOk() (*TimeRange, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeRange, true
}

// SetTimeRange sets field value
func (o *GroupedScoresResponse) SetTimeRange(v TimeRange) {
	o.TimeRange = v
}

// GetGroups returns the Groups field value
func (o *GroupedScoresResponse) GetGroups() []ScoreLabelGroup {
	if o == nil {
		var ret []ScoreLabelGroup
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *GroupedScoresResponse) GetGroupsOk() ([]ScoreLabelGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *GroupedScoresResponse) SetGroups(v []ScoreLabelGroup) {
	o.Groups = v
}

func (o GroupedScoresResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupedScoresResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["monitorName"] = o.MonitorName
	toSerialize["level"] = o.Level
	toSerialize["timeRange"] = o.TimeRange
	toSerialize["groups"] = o.Groups
	return toSerialize, nil
}

type NullableGroupedScoresResponse struct {
	value *GroupedScoresResponse
	isSet bool
}

func (v NullableGroupedScoresResponse) Get() *GroupedScoresResponse {
	return v.value
}

func (v *NullableGroupedScoresResponse) Set(val *GroupedScoresResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupedScoresResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupedScoresResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupedScoresResponse(val *GroupedScoresResponse) *NullableGroupedScoresResponse {
	return &NullableGroupedScoresResponse{value: val, isSet: true}
}

func (v NullableGroupedScoresResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupedScoresResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
