/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the EmbeddingData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmbeddingData{}

// EmbeddingData struct for EmbeddingData
type EmbeddingData struct {
	// Embedding model name
	Model *string `json:"model,omitempty"`
	// Embedding vendor/provider
	Vendor     *string        `json:"vendor,omitempty"`
	TokenUsage *LLMTokenUsage `json:"tokenUsage,omitempty"`
}

// NewEmbeddingData instantiates a new EmbeddingData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddingData() *EmbeddingData {
	this := EmbeddingData{}
	return &this
}

// NewEmbeddingDataWithDefaults instantiates a new EmbeddingData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddingDataWithDefaults() *EmbeddingData {
	this := EmbeddingData{}
	return &this
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *EmbeddingData) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddingData) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *EmbeddingData) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *EmbeddingData) SetModel(v string) {
	o.Model = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *EmbeddingData) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddingData) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *EmbeddingData) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *EmbeddingData) SetVendor(v string) {
	o.Vendor = &v
}

// GetTokenUsage returns the TokenUsage field value if set, zero value otherwise.
func (o *EmbeddingData) GetTokenUsage() LLMTokenUsage {
	if o == nil || IsNil(o.TokenUsage) {
		var ret LLMTokenUsage
		return ret
	}
	return *o.TokenUsage
}

// GetTokenUsageOk returns a tuple with the TokenUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddingData) GetTokenUsageOk() (*LLMTokenUsage, bool) {
	if o == nil || IsNil(o.TokenUsage) {
		return nil, false
	}
	return o.TokenUsage, true
}

// HasTokenUsage returns a boolean if a field has been set.
func (o *EmbeddingData) HasTokenUsage() bool {
	if o != nil && !IsNil(o.TokenUsage) {
		return true
	}

	return false
}

// SetTokenUsage gets a reference to the given LLMTokenUsage and assigns it to the TokenUsage field.
func (o *EmbeddingData) SetTokenUsage(v LLMTokenUsage) {
	o.TokenUsage = &v
}

func (o EmbeddingData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmbeddingData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.TokenUsage) {
		toSerialize["tokenUsage"] = o.TokenUsage
	}
	return toSerialize, nil
}

type NullableEmbeddingData struct {
	value *EmbeddingData
	isSet bool
}

func (v NullableEmbeddingData) Get() *EmbeddingData {
	return v.value
}

func (v *NullableEmbeddingData) Set(val *EmbeddingData) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddingData) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddingData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddingData(val *EmbeddingData) *NullableEmbeddingData {
	return &NullableEmbeddingData{value: val, isSet: true}
}

func (v NullableEmbeddingData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddingData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
