/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentModelConfigListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentModelConfigListResponse{}

// AgentModelConfigListResponse struct for AgentModelConfigListResponse
type AgentModelConfigListResponse struct {
	// List of agent model configurations
	Configs    []AgentModelConfigListItem `json:"configs"`
	Pagination PaginationInfo             `json:"pagination"`
}

// NewAgentModelConfigListResponse instantiates a new AgentModelConfigListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentModelConfigListResponse(configs []AgentModelConfigListItem, pagination PaginationInfo) *AgentModelConfigListResponse {
	this := AgentModelConfigListResponse{}
	this.Configs = configs
	this.Pagination = pagination
	return &this
}

// NewAgentModelConfigListResponseWithDefaults instantiates a new AgentModelConfigListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentModelConfigListResponseWithDefaults() *AgentModelConfigListResponse {
	this := AgentModelConfigListResponse{}
	return &this
}

// GetConfigs returns the Configs field value
func (o *AgentModelConfigListResponse) GetConfigs() []AgentModelConfigListItem {
	if o == nil {
		var ret []AgentModelConfigListItem
		return ret
	}

	return o.Configs
}

// GetConfigsOk returns a tuple with the Configs field value
// and a boolean to check if the value has been set.
func (o *AgentModelConfigListResponse) GetConfigsOk() ([]AgentModelConfigListItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Configs, true
}

// SetConfigs sets field value
func (o *AgentModelConfigListResponse) SetConfigs(v []AgentModelConfigListItem) {
	o.Configs = v
}

// GetPagination returns the Pagination field value
func (o *AgentModelConfigListResponse) GetPagination() PaginationInfo {
	if o == nil {
		var ret PaginationInfo
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *AgentModelConfigListResponse) GetPaginationOk() (*PaginationInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *AgentModelConfigListResponse) SetPagination(v PaginationInfo) {
	o.Pagination = v
}

func (o AgentModelConfigListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentModelConfigListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["configs"] = o.Configs
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

type NullableAgentModelConfigListResponse struct {
	value *AgentModelConfigListResponse
	isSet bool
}

func (v NullableAgentModelConfigListResponse) Get() *AgentModelConfigListResponse {
	return v.value
}

func (v *NullableAgentModelConfigListResponse) Set(val *AgentModelConfigListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentModelConfigListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentModelConfigListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentModelConfigListResponse(val *AgentModelConfigListResponse) *NullableAgentModelConfigListResponse {
	return &NullableAgentModelConfigListResponse{value: val, isSet: true}
}

func (v NullableAgentModelConfigListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentModelConfigListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
