/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the DataPlane type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataPlane{}

// DataPlane struct for DataPlane
type DataPlane struct {
	// Name of the data plane
	Name string `json:"name"`
	// Human-readable display name
	DisplayName string `json:"displayName"`
	// Description of the data plane
	Description string `json:"description"`
	// Organization name
	OrgName string `json:"orgName"`
	// Timestamp when the data plane was created
	CreatedAt time.Time `json:"createdAt"`
}

// NewDataPlane instantiates a new DataPlane object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataPlane(name string, displayName string, description string, orgName string, createdAt time.Time) *DataPlane {
	this := DataPlane{}
	this.Name = name
	this.DisplayName = displayName
	this.Description = description
	this.OrgName = orgName
	this.CreatedAt = createdAt
	return &this
}

// NewDataPlaneWithDefaults instantiates a new DataPlane object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataPlaneWithDefaults() *DataPlane {
	this := DataPlane{}
	return &this
}

// GetName returns the Name field value
func (o *DataPlane) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataPlane) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataPlane) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *DataPlane) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *DataPlane) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *DataPlane) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value
func (o *DataPlane) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *DataPlane) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *DataPlane) SetDescription(v string) {
	o.Description = v
}

// GetOrgName returns the OrgName field value
func (o *DataPlane) GetOrgName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value
// and a boolean to check if the value has been set.
func (o *DataPlane) GetOrgNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgName, true
}

// SetOrgName sets field value
func (o *DataPlane) SetOrgName(v string) {
	o.OrgName = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DataPlane) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DataPlane) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DataPlane) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o DataPlane) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataPlane) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	toSerialize["description"] = o.Description
	toSerialize["orgName"] = o.OrgName
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

type NullableDataPlane struct {
	value *DataPlane
	isSet bool
}

func (v NullableDataPlane) Get() *DataPlane {
	return v.value
}

func (v *NullableDataPlane) Set(val *DataPlane) {
	v.value = val
	v.isSet = true
}

func (v NullableDataPlane) IsSet() bool {
	return v.isSet
}

func (v *NullableDataPlane) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataPlane(val *DataPlane) *NullableDataPlane {
	return &NullableDataPlane{value: val, isSet: true}
}

func (v NullableDataPlane) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataPlane) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
