/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMProxyInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMProxyInfo{}

// LLMProxyInfo struct for LLMProxyInfo
type LLMProxyInfo struct {
	// UUID of the LLM proxy
	ProxyUuid string `json:"proxyUuid"`
	// Name of the LLM proxy
	ProxyName string `json:"proxyName"`
	// API context path
	Context string `json:"context"`
	// Status of the proxy
	Status string `json:"status"`
}

// NewLLMProxyInfo instantiates a new LLMProxyInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMProxyInfo(proxyUuid string, proxyName string, context string, status string) *LLMProxyInfo {
	this := LLMProxyInfo{}
	this.ProxyUuid = proxyUuid
	this.ProxyName = proxyName
	this.Context = context
	this.Status = status
	return &this
}

// NewLLMProxyInfoWithDefaults instantiates a new LLMProxyInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMProxyInfoWithDefaults() *LLMProxyInfo {
	this := LLMProxyInfo{}
	return &this
}

// GetProxyUuid returns the ProxyUuid field value
func (o *LLMProxyInfo) GetProxyUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProxyUuid
}

// GetProxyUuidOk returns a tuple with the ProxyUuid field value
// and a boolean to check if the value has been set.
func (o *LLMProxyInfo) GetProxyUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProxyUuid, true
}

// SetProxyUuid sets field value
func (o *LLMProxyInfo) SetProxyUuid(v string) {
	o.ProxyUuid = v
}

// GetProxyName returns the ProxyName field value
func (o *LLMProxyInfo) GetProxyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProxyName
}

// GetProxyNameOk returns a tuple with the ProxyName field value
// and a boolean to check if the value has been set.
func (o *LLMProxyInfo) GetProxyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProxyName, true
}

// SetProxyName sets field value
func (o *LLMProxyInfo) SetProxyName(v string) {
	o.ProxyName = v
}

// GetContext returns the Context field value
func (o *LLMProxyInfo) GetContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *LLMProxyInfo) GetContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *LLMProxyInfo) SetContext(v string) {
	o.Context = v
}

// GetStatus returns the Status field value
func (o *LLMProxyInfo) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *LLMProxyInfo) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *LLMProxyInfo) SetStatus(v string) {
	o.Status = v
}

func (o LLMProxyInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMProxyInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["proxyUuid"] = o.ProxyUuid
	toSerialize["proxyName"] = o.ProxyName
	toSerialize["context"] = o.Context
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

type NullableLLMProxyInfo struct {
	value *LLMProxyInfo
	isSet bool
}

func (v NullableLLMProxyInfo) Get() *LLMProxyInfo {
	return v.value
}

func (v *NullableLLMProxyInfo) Set(val *LLMProxyInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMProxyInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMProxyInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMProxyInfo(val *LLMProxyInfo) *NullableLLMProxyInfo {
	return &NullableLLMProxyInfo{value: val, isSet: true}
}

func (v NullableLLMProxyInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMProxyInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
