/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the ConsoleAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsoleAction{}

// ConsoleAction One thing a user did in the console UI.
type ConsoleAction struct {
	// Action name from the console taxonomy, e.g. \"amp.console.navigation.page-view\". Validated against a server-side allowlist; an unrecognized name is dropped.
	Action string `json:"action"`
	// When the user did this, per the browser clock. The server uses it as-is so the ordering within a buffered flush survives, and falls back to receipt time when it is absent. A value present but not RFC 3339 fails decoding and makes the whole batch malformed (400) — the client controls this field, so a bad value is a client bug worth surfacing rather than silently rewriting.
	OccurredAt *time.Time `json:"occurredAt,omitempty"`
	// The console route the action happened on, e.g. \"/orgs/acme/projects/p1/agents/a1/deploy\". Path only — the client must not send query strings, which can carry identifiers.
	Page *string `json:"page,omitempty"`
	// Opaque per-tab identifier generated by the console, used to group an individual browsing session. Not a credential and not derived from one.
	SessionId *string `json:"sessionId,omitempty"`
	// Taxonomy dimensions for this action, e.g. {\"entity\": \"agent\"}. Keys are validated per action against the server-side allowlist; unknown keys are dropped. Values must be scalars — never request bodies, secrets, or free-form user input.
	Dimensions map[string]interface{} `json:"dimensions,omitempty"`
}

// NewConsoleAction instantiates a new ConsoleAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsoleAction(action string) *ConsoleAction {
	this := ConsoleAction{}
	this.Action = action
	return &this
}

// NewConsoleActionWithDefaults instantiates a new ConsoleAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsoleActionWithDefaults() *ConsoleAction {
	this := ConsoleAction{}
	return &this
}

// GetAction returns the Action field value
func (o *ConsoleAction) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ConsoleAction) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ConsoleAction) SetAction(v string) {
	o.Action = v
}

// GetOccurredAt returns the OccurredAt field value if set, zero value otherwise.
func (o *ConsoleAction) GetOccurredAt() time.Time {
	if o == nil || IsNil(o.OccurredAt) {
		var ret time.Time
		return ret
	}
	return *o.OccurredAt
}

// GetOccurredAtOk returns a tuple with the OccurredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsoleAction) GetOccurredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OccurredAt) {
		return nil, false
	}
	return o.OccurredAt, true
}

// HasOccurredAt returns a boolean if a field has been set.
func (o *ConsoleAction) HasOccurredAt() bool {
	if o != nil && !IsNil(o.OccurredAt) {
		return true
	}

	return false
}

// SetOccurredAt gets a reference to the given time.Time and assigns it to the OccurredAt field.
func (o *ConsoleAction) SetOccurredAt(v time.Time) {
	o.OccurredAt = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ConsoleAction) GetPage() string {
	if o == nil || IsNil(o.Page) {
		var ret string
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsoleAction) GetPageOk() (*string, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ConsoleAction) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given string and assigns it to the Page field.
func (o *ConsoleAction) SetPage(v string) {
	o.Page = &v
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *ConsoleAction) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsoleAction) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *ConsoleAction) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *ConsoleAction) SetSessionId(v string) {
	o.SessionId = &v
}

// GetDimensions returns the Dimensions field value if set, zero value otherwise.
func (o *ConsoleAction) GetDimensions() map[string]interface{} {
	if o == nil || IsNil(o.Dimensions) {
		var ret map[string]interface{}
		return ret
	}
	return o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsoleAction) GetDimensionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Dimensions) {
		return map[string]interface{}{}, false
	}
	return o.Dimensions, true
}

// HasDimensions returns a boolean if a field has been set.
func (o *ConsoleAction) HasDimensions() bool {
	if o != nil && !IsNil(o.Dimensions) {
		return true
	}

	return false
}

// SetDimensions gets a reference to the given map[string]interface{} and assigns it to the Dimensions field.
func (o *ConsoleAction) SetDimensions(v map[string]interface{}) {
	o.Dimensions = v
}

func (o ConsoleAction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsoleAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.OccurredAt) {
		toSerialize["occurredAt"] = o.OccurredAt
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.SessionId) {
		toSerialize["sessionId"] = o.SessionId
	}
	if !IsNil(o.Dimensions) {
		toSerialize["dimensions"] = o.Dimensions
	}
	return toSerialize, nil
}

type NullableConsoleAction struct {
	value *ConsoleAction
	isSet bool
}

func (v NullableConsoleAction) Get() *ConsoleAction {
	return v.value
}

func (v *NullableConsoleAction) Set(val *ConsoleAction) {
	v.value = val
	v.isSet = true
}

func (v NullableConsoleAction) IsSet() bool {
	return v.isSet
}

func (v *NullableConsoleAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsoleAction(val *ConsoleAction) *NullableConsoleAction {
	return &NullableConsoleAction{value: val, isSet: true}
}

func (v NullableConsoleAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsoleAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
