/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AlertTestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertTestResponse{}

// AlertTestResponse struct for AlertTestResponse
type AlertTestResponse struct {
	Delivered  bool    `json:"delivered"`
	StatusCode *int32  `json:"statusCode,omitempty"`
	Error      *string `json:"error,omitempty"`
}

// NewAlertTestResponse instantiates a new AlertTestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertTestResponse(delivered bool) *AlertTestResponse {
	this := AlertTestResponse{}
	this.Delivered = delivered
	return &this
}

// NewAlertTestResponseWithDefaults instantiates a new AlertTestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertTestResponseWithDefaults() *AlertTestResponse {
	this := AlertTestResponse{}
	return &this
}

// GetDelivered returns the Delivered field value
func (o *AlertTestResponse) GetDelivered() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Delivered
}

// GetDeliveredOk returns a tuple with the Delivered field value
// and a boolean to check if the value has been set.
func (o *AlertTestResponse) GetDeliveredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delivered, true
}

// SetDelivered sets field value
func (o *AlertTestResponse) SetDelivered(v bool) {
	o.Delivered = v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *AlertTestResponse) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertTestResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *AlertTestResponse) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *AlertTestResponse) SetStatusCode(v int32) {
	o.StatusCode = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *AlertTestResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertTestResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *AlertTestResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *AlertTestResponse) SetError(v string) {
	o.Error = &v
}

func (o AlertTestResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertTestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["delivered"] = o.Delivered
	if !IsNil(o.StatusCode) {
		toSerialize["statusCode"] = o.StatusCode
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableAlertTestResponse struct {
	value *AlertTestResponse
	isSet bool
}

func (v NullableAlertTestResponse) Get() *AlertTestResponse {
	return v.value
}

func (v *NullableAlertTestResponse) Set(val *AlertTestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertTestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertTestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertTestResponse(val *AlertTestResponse) *NullableAlertTestResponse {
	return &NullableAlertTestResponse{value: val, isSet: true}
}

func (v NullableAlertTestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertTestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
