/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RateLimitResetWindow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RateLimitResetWindow{}

// RateLimitResetWindow struct for RateLimitResetWindow
type RateLimitResetWindow struct {
	// Reset window duration
	Duration int32 `json:"duration"`
	// Time unit
	Unit string `json:"unit"`
}

// NewRateLimitResetWindow instantiates a new RateLimitResetWindow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRateLimitResetWindow(duration int32, unit string) *RateLimitResetWindow {
	this := RateLimitResetWindow{}
	this.Duration = duration
	this.Unit = unit
	return &this
}

// NewRateLimitResetWindowWithDefaults instantiates a new RateLimitResetWindow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRateLimitResetWindowWithDefaults() *RateLimitResetWindow {
	this := RateLimitResetWindow{}
	return &this
}

// GetDuration returns the Duration field value
func (o *RateLimitResetWindow) GetDuration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *RateLimitResetWindow) GetDurationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *RateLimitResetWindow) SetDuration(v int32) {
	o.Duration = v
}

// GetUnit returns the Unit field value
func (o *RateLimitResetWindow) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *RateLimitResetWindow) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *RateLimitResetWindow) SetUnit(v string) {
	o.Unit = v
}

func (o RateLimitResetWindow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RateLimitResetWindow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration
	toSerialize["unit"] = o.Unit
	return toSerialize, nil
}

type NullableRateLimitResetWindow struct {
	value *RateLimitResetWindow
	isSet bool
}

func (v NullableRateLimitResetWindow) Get() *RateLimitResetWindow {
	return v.value
}

func (v *NullableRateLimitResetWindow) Set(val *RateLimitResetWindow) {
	v.value = val
	v.isSet = true
}

func (v NullableRateLimitResetWindow) IsSet() bool {
	return v.isSet
}

func (v *NullableRateLimitResetWindow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRateLimitResetWindow(val *RateLimitResetWindow) *NullableRateLimitResetWindow {
	return &NullableRateLimitResetWindow{value: val, isSet: true}
}

func (v NullableRateLimitResetWindow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRateLimitResetWindow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
