/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMProxyConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMProxyConfig{}

// LLMProxyConfig struct for LLMProxyConfig
type LLMProxyConfig struct {
	// Proxy name
	Name *string `json:"name,omitempty"`
	// Proxy version
	Version *string `json:"version,omitempty"`
	// API context path
	Context *string `json:"context,omitempty"`
	// Virtual host
	Vhost *string `json:"vhost,omitempty"`
	// Provider reference
	Provider *string         `json:"provider,omitempty"`
	Policies []LLMPolicy     `json:"policies,omitempty"`
	Security *SecurityConfig `json:"security,omitempty"`
}

// NewLLMProxyConfig instantiates a new LLMProxyConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMProxyConfig() *LLMProxyConfig {
	this := LLMProxyConfig{}
	return &this
}

// NewLLMProxyConfigWithDefaults instantiates a new LLMProxyConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMProxyConfigWithDefaults() *LLMProxyConfig {
	this := LLMProxyConfig{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LLMProxyConfig) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProxyConfig) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LLMProxyConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LLMProxyConfig) SetName(v string) {
	o.Name = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *LLMProxyConfig) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProxyConfig) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *LLMProxyConfig) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *LLMProxyConfig) SetVersion(v string) {
	o.Version = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *LLMProxyConfig) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProxyConfig) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *LLMProxyConfig) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *LLMProxyConfig) SetContext(v string) {
	o.Context = &v
}

// GetVhost returns the Vhost field value if set, zero value otherwise.
func (o *LLMProxyConfig) GetVhost() string {
	if o == nil || IsNil(o.Vhost) {
		var ret string
		return ret
	}
	return *o.Vhost
}

// GetVhostOk returns a tuple with the Vhost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProxyConfig) GetVhostOk() (*string, bool) {
	if o == nil || IsNil(o.Vhost) {
		return nil, false
	}
	return o.Vhost, true
}

// HasVhost returns a boolean if a field has been set.
func (o *LLMProxyConfig) HasVhost() bool {
	if o != nil && !IsNil(o.Vhost) {
		return true
	}

	return false
}

// SetVhost gets a reference to the given string and assigns it to the Vhost field.
func (o *LLMProxyConfig) SetVhost(v string) {
	o.Vhost = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *LLMProxyConfig) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProxyConfig) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *LLMProxyConfig) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *LLMProxyConfig) SetProvider(v string) {
	o.Provider = &v
}

// GetPolicies returns the Policies field value if set, zero value otherwise.
func (o *LLMProxyConfig) GetPolicies() []LLMPolicy {
	if o == nil || IsNil(o.Policies) {
		var ret []LLMPolicy
		return ret
	}
	return o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProxyConfig) GetPoliciesOk() ([]LLMPolicy, bool) {
	if o == nil || IsNil(o.Policies) {
		return nil, false
	}
	return o.Policies, true
}

// HasPolicies returns a boolean if a field has been set.
func (o *LLMProxyConfig) HasPolicies() bool {
	if o != nil && !IsNil(o.Policies) {
		return true
	}

	return false
}

// SetPolicies gets a reference to the given []LLMPolicy and assigns it to the Policies field.
func (o *LLMProxyConfig) SetPolicies(v []LLMPolicy) {
	o.Policies = v
}

// GetSecurity returns the Security field value if set, zero value otherwise.
func (o *LLMProxyConfig) GetSecurity() SecurityConfig {
	if o == nil || IsNil(o.Security) {
		var ret SecurityConfig
		return ret
	}
	return *o.Security
}

// GetSecurityOk returns a tuple with the Security field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProxyConfig) GetSecurityOk() (*SecurityConfig, bool) {
	if o == nil || IsNil(o.Security) {
		return nil, false
	}
	return o.Security, true
}

// HasSecurity returns a boolean if a field has been set.
func (o *LLMProxyConfig) HasSecurity() bool {
	if o != nil && !IsNil(o.Security) {
		return true
	}

	return false
}

// SetSecurity gets a reference to the given SecurityConfig and assigns it to the Security field.
func (o *LLMProxyConfig) SetSecurity(v SecurityConfig) {
	o.Security = &v
}

func (o LLMProxyConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMProxyConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Vhost) {
		toSerialize["vhost"] = o.Vhost
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Policies) {
		toSerialize["policies"] = o.Policies
	}
	if !IsNil(o.Security) {
		toSerialize["security"] = o.Security
	}
	return toSerialize, nil
}

type NullableLLMProxyConfig struct {
	value *LLMProxyConfig
	isSet bool
}

func (v NullableLLMProxyConfig) Get() *LLMProxyConfig {
	return v.value
}

func (v *NullableLLMProxyConfig) Set(val *LLMProxyConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMProxyConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMProxyConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMProxyConfig(val *LLMProxyConfig) *NullableLLMProxyConfig {
	return &NullableLLMProxyConfig{value: val, isSet: true}
}

func (v NullableLLMProxyConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMProxyConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
