/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the LLMProviderListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMProviderListItem{}

// LLMProviderListItem struct for LLMProviderListItem
type LLMProviderListItem struct {
	// Provider UUID
	Uuid string `json:"uuid"`
	// Unique identifier for the LLM provider
	Id string `json:"id"`
	// Human-readable name of the LLM provider
	Name string `json:"name"`
	// User who created the provider
	CreatedBy *string `json:"createdBy,omitempty"`
	// Template identifier
	Template string `json:"template"`
	// Provider status
	Status   string   `json:"status"`
	Gateways []string `json:"gateways,omitempty"`
	// Timestamp when the resource was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Timestamp when the resource was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewLLMProviderListItem instantiates a new LLMProviderListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMProviderListItem(uuid string, id string, name string, template string, status string) *LLMProviderListItem {
	this := LLMProviderListItem{}
	this.Uuid = uuid
	this.Id = id
	this.Name = name
	this.Template = template
	this.Status = status
	return &this
}

// NewLLMProviderListItemWithDefaults instantiates a new LLMProviderListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMProviderListItemWithDefaults() *LLMProviderListItem {
	this := LLMProviderListItem{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *LLMProviderListItem) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *LLMProviderListItem) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *LLMProviderListItem) SetUuid(v string) {
	o.Uuid = v
}

// GetId returns the Id field value
func (o *LLMProviderListItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LLMProviderListItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LLMProviderListItem) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *LLMProviderListItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LLMProviderListItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LLMProviderListItem) SetName(v string) {
	o.Name = v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *LLMProviderListItem) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderListItem) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *LLMProviderListItem) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *LLMProviderListItem) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetTemplate returns the Template field value
func (o *LLMProviderListItem) GetTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *LLMProviderListItem) GetTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *LLMProviderListItem) SetTemplate(v string) {
	o.Template = v
}

// GetStatus returns the Status field value
func (o *LLMProviderListItem) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *LLMProviderListItem) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *LLMProviderListItem) SetStatus(v string) {
	o.Status = v
}

// GetGateways returns the Gateways field value if set, zero value otherwise.
func (o *LLMProviderListItem) GetGateways() []string {
	if o == nil || IsNil(o.Gateways) {
		var ret []string
		return ret
	}
	return o.Gateways
}

// GetGatewaysOk returns a tuple with the Gateways field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderListItem) GetGatewaysOk() ([]string, bool) {
	if o == nil || IsNil(o.Gateways) {
		return nil, false
	}
	return o.Gateways, true
}

// HasGateways returns a boolean if a field has been set.
func (o *LLMProviderListItem) HasGateways() bool {
	if o != nil && !IsNil(o.Gateways) {
		return true
	}

	return false
}

// SetGateways gets a reference to the given []string and assigns it to the Gateways field.
func (o *LLMProviderListItem) SetGateways(v []string) {
	o.Gateways = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *LLMProviderListItem) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderListItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *LLMProviderListItem) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *LLMProviderListItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *LLMProviderListItem) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderListItem) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *LLMProviderListItem) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *LLMProviderListItem) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o LLMProviderListItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMProviderListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	toSerialize["template"] = o.Template
	toSerialize["status"] = o.Status
	if !IsNil(o.Gateways) {
		toSerialize["gateways"] = o.Gateways
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableLLMProviderListItem struct {
	value *LLMProviderListItem
	isSet bool
}

func (v NullableLLMProviderListItem) Get() *LLMProviderListItem {
	return v.value
}

func (v *NullableLLMProviderListItem) Set(val *LLMProviderListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMProviderListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMProviderListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMProviderListItem(val *LLMProviderListItem) *NullableLLMProviderListItem {
	return &NullableLLMProviderListItem{value: val, isSet: true}
}

func (v NullableLLMProviderListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMProviderListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
