/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"fmt"
)

// Build - struct for Build
type Build struct {
	BuildpackBuild *BuildpackBuild
	DockerBuild    *DockerBuild
}

// BuildpackBuildAsBuild is a convenience function that returns BuildpackBuild wrapped in Build
func BuildpackBuildAsBuild(v *BuildpackBuild) Build {
	return Build{
		BuildpackBuild: v,
	}
}

// DockerBuildAsBuild is a convenience function that returns DockerBuild wrapped in Build
func DockerBuildAsBuild(v *DockerBuild) Build {
	return Build{
		DockerBuild: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *Build) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BuildpackBuild
	err = newStrictDecoder(data).Decode(&dst.BuildpackBuild)
	if err == nil {
		jsonBuildpackBuild, _ := json.Marshal(dst.BuildpackBuild)
		if string(jsonBuildpackBuild) == "{}" { // empty struct
			dst.BuildpackBuild = nil
		} else {
			match++
		}
	} else {
		dst.BuildpackBuild = nil
	}

	// try to unmarshal data into DockerBuild
	err = newStrictDecoder(data).Decode(&dst.DockerBuild)
	if err == nil {
		jsonDockerBuild, _ := json.Marshal(dst.DockerBuild)
		if string(jsonDockerBuild) == "{}" { // empty struct
			dst.DockerBuild = nil
		} else {
			match++
		}
	} else {
		dst.DockerBuild = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BuildpackBuild = nil
		dst.DockerBuild = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Build)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Build)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Build) MarshalJSON() ([]byte, error) {
	if src.BuildpackBuild != nil {
		return json.Marshal(&src.BuildpackBuild)
	}

	if src.DockerBuild != nil {
		return json.Marshal(&src.DockerBuild)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Build) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BuildpackBuild != nil {
		return obj.BuildpackBuild
	}

	if obj.DockerBuild != nil {
		return obj.DockerBuild
	}

	// all schemas are nil
	return nil
}

type NullableBuild struct {
	value *Build
	isSet bool
}

func (v NullableBuild) Get() *Build {
	return v.value
}

func (v *NullableBuild) Set(val *Build) {
	v.value = val
	v.isSet = true
}

func (v NullableBuild) IsSet() bool {
	return v.isSet
}

func (v *NullableBuild) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuild(val *Build) *NullableBuild {
	return &NullableBuild{value: val, isSet: true}
}

func (v NullableBuild) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuild) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
