/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UndeployLLMProviderDeployment200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UndeployLLMProviderDeployment200Response{}

// UndeployLLMProviderDeployment200Response struct for UndeployLLMProviderDeployment200Response
type UndeployLLMProviderDeployment200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewUndeployLLMProviderDeployment200Response instantiates a new UndeployLLMProviderDeployment200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUndeployLLMProviderDeployment200Response() *UndeployLLMProviderDeployment200Response {
	this := UndeployLLMProviderDeployment200Response{}
	return &this
}

// NewUndeployLLMProviderDeployment200ResponseWithDefaults instantiates a new UndeployLLMProviderDeployment200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUndeployLLMProviderDeployment200ResponseWithDefaults() *UndeployLLMProviderDeployment200Response {
	this := UndeployLLMProviderDeployment200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UndeployLLMProviderDeployment200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UndeployLLMProviderDeployment200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UndeployLLMProviderDeployment200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UndeployLLMProviderDeployment200Response) SetMessage(v string) {
	o.Message = &v
}

func (o UndeployLLMProviderDeployment200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UndeployLLMProviderDeployment200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableUndeployLLMProviderDeployment200Response struct {
	value *UndeployLLMProviderDeployment200Response
	isSet bool
}

func (v NullableUndeployLLMProviderDeployment200Response) Get() *UndeployLLMProviderDeployment200Response {
	return v.value
}

func (v *NullableUndeployLLMProviderDeployment200Response) Set(val *UndeployLLMProviderDeployment200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUndeployLLMProviderDeployment200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUndeployLLMProviderDeployment200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUndeployLLMProviderDeployment200Response(val *UndeployLLMProviderDeployment200Response) *NullableUndeployLLMProviderDeployment200Response {
	return &NullableUndeployLLMProviderDeployment200Response{value: val, isSet: true}
}

func (v NullableUndeployLLMProviderDeployment200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUndeployLLMProviderDeployment200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
