/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateLLMProviderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateLLMProviderRequest{}

// UpdateLLMProviderRequest struct for UpdateLLMProviderRequest
type UpdateLLMProviderRequest struct {
	// Updated description
	Description *string `json:"description,omitempty"`
	// Updated template handle
	TemplateHandle *string `json:"templateHandle,omitempty"`
	// Updated OpenAPI specification
	Openapi *string `json:"openapi,omitempty"`
	// Updated model list
	ModelList     []LLMModelProvider `json:"modelList,omitempty"`
	Configuration *LLMProviderConfig `json:"configuration,omitempty"`
	Gateways      []string           `json:"gateways,omitempty"`
}

// NewUpdateLLMProviderRequest instantiates a new UpdateLLMProviderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateLLMProviderRequest() *UpdateLLMProviderRequest {
	this := UpdateLLMProviderRequest{}
	return &this
}

// NewUpdateLLMProviderRequestWithDefaults instantiates a new UpdateLLMProviderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateLLMProviderRequestWithDefaults() *UpdateLLMProviderRequest {
	this := UpdateLLMProviderRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateLLMProviderRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLLMProviderRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateLLMProviderRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateLLMProviderRequest) SetDescription(v string) {
	o.Description = &v
}

// GetTemplateHandle returns the TemplateHandle field value if set, zero value otherwise.
func (o *UpdateLLMProviderRequest) GetTemplateHandle() string {
	if o == nil || IsNil(o.TemplateHandle) {
		var ret string
		return ret
	}
	return *o.TemplateHandle
}

// GetTemplateHandleOk returns a tuple with the TemplateHandle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLLMProviderRequest) GetTemplateHandleOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateHandle) {
		return nil, false
	}
	return o.TemplateHandle, true
}

// HasTemplateHandle returns a boolean if a field has been set.
func (o *UpdateLLMProviderRequest) HasTemplateHandle() bool {
	if o != nil && !IsNil(o.TemplateHandle) {
		return true
	}

	return false
}

// SetTemplateHandle gets a reference to the given string and assigns it to the TemplateHandle field.
func (o *UpdateLLMProviderRequest) SetTemplateHandle(v string) {
	o.TemplateHandle = &v
}

// GetOpenapi returns the Openapi field value if set, zero value otherwise.
func (o *UpdateLLMProviderRequest) GetOpenapi() string {
	if o == nil || IsNil(o.Openapi) {
		var ret string
		return ret
	}
	return *o.Openapi
}

// GetOpenapiOk returns a tuple with the Openapi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLLMProviderRequest) GetOpenapiOk() (*string, bool) {
	if o == nil || IsNil(o.Openapi) {
		return nil, false
	}
	return o.Openapi, true
}

// HasOpenapi returns a boolean if a field has been set.
func (o *UpdateLLMProviderRequest) HasOpenapi() bool {
	if o != nil && !IsNil(o.Openapi) {
		return true
	}

	return false
}

// SetOpenapi gets a reference to the given string and assigns it to the Openapi field.
func (o *UpdateLLMProviderRequest) SetOpenapi(v string) {
	o.Openapi = &v
}

// GetModelList returns the ModelList field value if set, zero value otherwise.
func (o *UpdateLLMProviderRequest) GetModelList() []LLMModelProvider {
	if o == nil || IsNil(o.ModelList) {
		var ret []LLMModelProvider
		return ret
	}
	return o.ModelList
}

// GetModelListOk returns a tuple with the ModelList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLLMProviderRequest) GetModelListOk() ([]LLMModelProvider, bool) {
	if o == nil || IsNil(o.ModelList) {
		return nil, false
	}
	return o.ModelList, true
}

// HasModelList returns a boolean if a field has been set.
func (o *UpdateLLMProviderRequest) HasModelList() bool {
	if o != nil && !IsNil(o.ModelList) {
		return true
	}

	return false
}

// SetModelList gets a reference to the given []LLMModelProvider and assigns it to the ModelList field.
func (o *UpdateLLMProviderRequest) SetModelList(v []LLMModelProvider) {
	o.ModelList = v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *UpdateLLMProviderRequest) GetConfiguration() LLMProviderConfig {
	if o == nil || IsNil(o.Configuration) {
		var ret LLMProviderConfig
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLLMProviderRequest) GetConfigurationOk() (*LLMProviderConfig, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *UpdateLLMProviderRequest) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given LLMProviderConfig and assigns it to the Configuration field.
func (o *UpdateLLMProviderRequest) SetConfiguration(v LLMProviderConfig) {
	o.Configuration = &v
}

// GetGateways returns the Gateways field value if set, zero value otherwise.
func (o *UpdateLLMProviderRequest) GetGateways() []string {
	if o == nil || IsNil(o.Gateways) {
		var ret []string
		return ret
	}
	return o.Gateways
}

// GetGatewaysOk returns a tuple with the Gateways field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLLMProviderRequest) GetGatewaysOk() ([]string, bool) {
	if o == nil || IsNil(o.Gateways) {
		return nil, false
	}
	return o.Gateways, true
}

// HasGateways returns a boolean if a field has been set.
func (o *UpdateLLMProviderRequest) HasGateways() bool {
	if o != nil && !IsNil(o.Gateways) {
		return true
	}

	return false
}

// SetGateways gets a reference to the given []string and assigns it to the Gateways field.
func (o *UpdateLLMProviderRequest) SetGateways(v []string) {
	o.Gateways = v
}

func (o UpdateLLMProviderRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateLLMProviderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.TemplateHandle) {
		toSerialize["templateHandle"] = o.TemplateHandle
	}
	if !IsNil(o.Openapi) {
		toSerialize["openapi"] = o.Openapi
	}
	if !IsNil(o.ModelList) {
		toSerialize["modelList"] = o.ModelList
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.Gateways) {
		toSerialize["gateways"] = o.Gateways
	}
	return toSerialize, nil
}

type NullableUpdateLLMProviderRequest struct {
	value *UpdateLLMProviderRequest
	isSet bool
}

func (v NullableUpdateLLMProviderRequest) Get() *UpdateLLMProviderRequest {
	return v.value
}

func (v *NullableUpdateLLMProviderRequest) Set(val *UpdateLLMProviderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLLMProviderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLLMProviderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLLMProviderRequest(val *UpdateLLMProviderRequest) *NullableUpdateLLMProviderRequest {
	return &NullableUpdateLLMProviderRequest{value: val, isSet: true}
}

func (v NullableUpdateLLMProviderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateLLMProviderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
