/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMAccessControl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMAccessControl{}

// LLMAccessControl struct for LLMAccessControl
type LLMAccessControl struct {
	// Access control mode
	Mode       string           `json:"mode"`
	Exceptions []RouteException `json:"exceptions,omitempty"`
}

// NewLLMAccessControl instantiates a new LLMAccessControl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMAccessControl(mode string) *LLMAccessControl {
	this := LLMAccessControl{}
	this.Mode = mode
	return &this
}

// NewLLMAccessControlWithDefaults instantiates a new LLMAccessControl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMAccessControlWithDefaults() *LLMAccessControl {
	this := LLMAccessControl{}
	return &this
}

// GetMode returns the Mode field value
func (o *LLMAccessControl) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *LLMAccessControl) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *LLMAccessControl) SetMode(v string) {
	o.Mode = v
}

// GetExceptions returns the Exceptions field value if set, zero value otherwise.
func (o *LLMAccessControl) GetExceptions() []RouteException {
	if o == nil || IsNil(o.Exceptions) {
		var ret []RouteException
		return ret
	}
	return o.Exceptions
}

// GetExceptionsOk returns a tuple with the Exceptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMAccessControl) GetExceptionsOk() ([]RouteException, bool) {
	if o == nil || IsNil(o.Exceptions) {
		return nil, false
	}
	return o.Exceptions, true
}

// HasExceptions returns a boolean if a field has been set.
func (o *LLMAccessControl) HasExceptions() bool {
	if o != nil && !IsNil(o.Exceptions) {
		return true
	}

	return false
}

// SetExceptions gets a reference to the given []RouteException and assigns it to the Exceptions field.
func (o *LLMAccessControl) SetExceptions(v []RouteException) {
	o.Exceptions = v
}

func (o LLMAccessControl) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMAccessControl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mode"] = o.Mode
	if !IsNil(o.Exceptions) {
		toSerialize["exceptions"] = o.Exceptions
	}
	return toSerialize, nil
}

type NullableLLMAccessControl struct {
	value *LLMAccessControl
	isSet bool
}

func (v NullableLLMAccessControl) Get() *LLMAccessControl {
	return v.value
}

func (v *NullableLLMAccessControl) Set(val *LLMAccessControl) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMAccessControl) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMAccessControl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMAccessControl(val *LLMAccessControl) *NullableLLMAccessControl {
	return &NullableLLMAccessControl{value: val, isSet: true}
}

func (v NullableLLMAccessControl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMAccessControl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
