/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MonitorEvaluator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonitorEvaluator{}

// MonitorEvaluator struct for MonitorEvaluator
type MonitorEvaluator struct {
	// Evaluator identifier (e.g., \"latency\", \"answer_relevancy\", \"deepeval/plan-quality\")
	Name string `json:"name"`
	// Optional evaluator-specific configuration parameters
	Config map[string]interface{} `json:"config,omitempty"`
}

// NewMonitorEvaluator instantiates a new MonitorEvaluator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonitorEvaluator(name string) *MonitorEvaluator {
	this := MonitorEvaluator{}
	this.Name = name
	return &this
}

// NewMonitorEvaluatorWithDefaults instantiates a new MonitorEvaluator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonitorEvaluatorWithDefaults() *MonitorEvaluator {
	this := MonitorEvaluator{}
	return &this
}

// GetName returns the Name field value
func (o *MonitorEvaluator) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MonitorEvaluator) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MonitorEvaluator) SetName(v string) {
	o.Name = v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *MonitorEvaluator) GetConfig() map[string]interface{} {
	if o == nil || IsNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitorEvaluator) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *MonitorEvaluator) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *MonitorEvaluator) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o MonitorEvaluator) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonitorEvaluator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableMonitorEvaluator struct {
	value *MonitorEvaluator
	isSet bool
}

func (v NullableMonitorEvaluator) Get() *MonitorEvaluator {
	return v.value
}

func (v *NullableMonitorEvaluator) Set(val *MonitorEvaluator) {
	v.value = val
	v.isSet = true
}

func (v NullableMonitorEvaluator) IsSet() bool {
	return v.isSet
}

func (v *NullableMonitorEvaluator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonitorEvaluator(val *MonitorEvaluator) *NullableMonitorEvaluator {
	return &NullableMonitorEvaluator{value: val, isSet: true}
}

func (v NullableMonitorEvaluator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonitorEvaluator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
