/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateAgentResourceConfigsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAgentResourceConfigsRequest{}

// UpdateAgentResourceConfigsRequest struct for UpdateAgentResourceConfigsRequest
type UpdateAgentResourceConfigsRequest struct {
	// Number of replicas to run
	Replicas  *int32          `json:"replicas,omitempty"`
	Resources *ResourceConfig `json:"resources,omitempty"`
}

// NewUpdateAgentResourceConfigsRequest instantiates a new UpdateAgentResourceConfigsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAgentResourceConfigsRequest() *UpdateAgentResourceConfigsRequest {
	this := UpdateAgentResourceConfigsRequest{}
	return &this
}

// NewUpdateAgentResourceConfigsRequestWithDefaults instantiates a new UpdateAgentResourceConfigsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAgentResourceConfigsRequestWithDefaults() *UpdateAgentResourceConfigsRequest {
	this := UpdateAgentResourceConfigsRequest{}
	return &this
}

// GetReplicas returns the Replicas field value if set, zero value otherwise.
func (o *UpdateAgentResourceConfigsRequest) GetReplicas() int32 {
	if o == nil || IsNil(o.Replicas) {
		var ret int32
		return ret
	}
	return *o.Replicas
}

// GetReplicasOk returns a tuple with the Replicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentResourceConfigsRequest) GetReplicasOk() (*int32, bool) {
	if o == nil || IsNil(o.Replicas) {
		return nil, false
	}
	return o.Replicas, true
}

// HasReplicas returns a boolean if a field has been set.
func (o *UpdateAgentResourceConfigsRequest) HasReplicas() bool {
	if o != nil && !IsNil(o.Replicas) {
		return true
	}

	return false
}

// SetReplicas gets a reference to the given int32 and assigns it to the Replicas field.
func (o *UpdateAgentResourceConfigsRequest) SetReplicas(v int32) {
	o.Replicas = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *UpdateAgentResourceConfigsRequest) GetResources() ResourceConfig {
	if o == nil || IsNil(o.Resources) {
		var ret ResourceConfig
		return ret
	}
	return *o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentResourceConfigsRequest) GetResourcesOk() (*ResourceConfig, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *UpdateAgentResourceConfigsRequest) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given ResourceConfig and assigns it to the Resources field.
func (o *UpdateAgentResourceConfigsRequest) SetResources(v ResourceConfig) {
	o.Resources = &v
}

func (o UpdateAgentResourceConfigsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAgentResourceConfigsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Replicas) {
		toSerialize["replicas"] = o.Replicas
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	return toSerialize, nil
}

type NullableUpdateAgentResourceConfigsRequest struct {
	value *UpdateAgentResourceConfigsRequest
	isSet bool
}

func (v NullableUpdateAgentResourceConfigsRequest) Get() *UpdateAgentResourceConfigsRequest {
	return v.value
}

func (v *NullableUpdateAgentResourceConfigsRequest) Set(val *UpdateAgentResourceConfigsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAgentResourceConfigsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAgentResourceConfigsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAgentResourceConfigsRequest(val *UpdateAgentResourceConfigsRequest) *NullableUpdateAgentResourceConfigsRequest {
	return &NullableUpdateAgentResourceConfigsRequest{value: val, isSet: true}
}

func (v NullableUpdateAgentResourceConfigsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAgentResourceConfigsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
