/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the CreateLLMAPIKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLLMAPIKeyRequest{}

// CreateLLMAPIKeyRequest struct for CreateLLMAPIKeyRequest
type CreateLLMAPIKeyRequest struct {
	// Unique identifier for the API key. If omitted, generated from displayName.
	Name *string `json:"name,omitempty"`
	// Human-readable display name for the API key.
	DisplayName *string `json:"displayName,omitempty"`
	// Optional expiration time in ISO 8601 format (e.g. 2026-12-31T23:59:59Z).
	ExpiresAt *string `json:"expiresAt,omitempty"`
}

// NewCreateLLMAPIKeyRequest instantiates a new CreateLLMAPIKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLLMAPIKeyRequest() *CreateLLMAPIKeyRequest {
	this := CreateLLMAPIKeyRequest{}
	return &this
}

// NewCreateLLMAPIKeyRequestWithDefaults instantiates a new CreateLLMAPIKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLLMAPIKeyRequestWithDefaults() *CreateLLMAPIKeyRequest {
	this := CreateLLMAPIKeyRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateLLMAPIKeyRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLLMAPIKeyRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateLLMAPIKeyRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateLLMAPIKeyRequest) SetName(v string) {
	o.Name = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *CreateLLMAPIKeyRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLLMAPIKeyRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *CreateLLMAPIKeyRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *CreateLLMAPIKeyRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *CreateLLMAPIKeyRequest) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLLMAPIKeyRequest) GetExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *CreateLLMAPIKeyRequest) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *CreateLLMAPIKeyRequest) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

func (o CreateLLMAPIKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLLMAPIKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	return toSerialize, nil
}

type NullableCreateLLMAPIKeyRequest struct {
	value *CreateLLMAPIKeyRequest
	isSet bool
}

func (v NullableCreateLLMAPIKeyRequest) Get() *CreateLLMAPIKeyRequest {
	return v.value
}

func (v *NullableCreateLLMAPIKeyRequest) Set(val *CreateLLMAPIKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLLMAPIKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLLMAPIKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLLMAPIKeyRequest(val *CreateLLMAPIKeyRequest) *NullableCreateLLMAPIKeyRequest {
	return &NullableCreateLLMAPIKeyRequest{value: val, isSet: true}
}

func (v NullableCreateLLMAPIKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLLMAPIKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
