/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMProviderConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMProviderConfig{}

// LLMProviderConfig struct for LLMProviderConfig
type LLMProviderConfig struct {
	// Configuration name
	Name *string `json:"name,omitempty"`
	// Configuration version
	Version *string `json:"version,omitempty"`
	// API context path
	Context *string `json:"context,omitempty"`
	// Virtual host
	Vhost *string `json:"vhost,omitempty"`
	// Template name
	Template      *string                `json:"template,omitempty"`
	Upstream      *UpstreamConfig        `json:"upstream,omitempty"`
	AccessControl *LLMAccessControl      `json:"accessControl,omitempty"`
	RateLimiting  *LLMRateLimitingConfig `json:"rateLimiting,omitempty"`
	Policies      []LLMPolicy            `json:"policies,omitempty"`
	Security      *SecurityConfig        `json:"security,omitempty"`
}

// NewLLMProviderConfig instantiates a new LLMProviderConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMProviderConfig() *LLMProviderConfig {
	this := LLMProviderConfig{}
	return &this
}

// NewLLMProviderConfigWithDefaults instantiates a new LLMProviderConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMProviderConfigWithDefaults() *LLMProviderConfig {
	this := LLMProviderConfig{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LLMProviderConfig) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderConfig) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LLMProviderConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LLMProviderConfig) SetName(v string) {
	o.Name = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *LLMProviderConfig) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderConfig) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *LLMProviderConfig) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *LLMProviderConfig) SetVersion(v string) {
	o.Version = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *LLMProviderConfig) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderConfig) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *LLMProviderConfig) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *LLMProviderConfig) SetContext(v string) {
	o.Context = &v
}

// GetVhost returns the Vhost field value if set, zero value otherwise.
func (o *LLMProviderConfig) GetVhost() string {
	if o == nil || IsNil(o.Vhost) {
		var ret string
		return ret
	}
	return *o.Vhost
}

// GetVhostOk returns a tuple with the Vhost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderConfig) GetVhostOk() (*string, bool) {
	if o == nil || IsNil(o.Vhost) {
		return nil, false
	}
	return o.Vhost, true
}

// HasVhost returns a boolean if a field has been set.
func (o *LLMProviderConfig) HasVhost() bool {
	if o != nil && !IsNil(o.Vhost) {
		return true
	}

	return false
}

// SetVhost gets a reference to the given string and assigns it to the Vhost field.
func (o *LLMProviderConfig) SetVhost(v string) {
	o.Vhost = &v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *LLMProviderConfig) GetTemplate() string {
	if o == nil || IsNil(o.Template) {
		var ret string
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderConfig) GetTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *LLMProviderConfig) HasTemplate() bool {
	if o != nil && !IsNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given string and assigns it to the Template field.
func (o *LLMProviderConfig) SetTemplate(v string) {
	o.Template = &v
}

// GetUpstream returns the Upstream field value if set, zero value otherwise.
func (o *LLMProviderConfig) GetUpstream() UpstreamConfig {
	if o == nil || IsNil(o.Upstream) {
		var ret UpstreamConfig
		return ret
	}
	return *o.Upstream
}

// GetUpstreamOk returns a tuple with the Upstream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderConfig) GetUpstreamOk() (*UpstreamConfig, bool) {
	if o == nil || IsNil(o.Upstream) {
		return nil, false
	}
	return o.Upstream, true
}

// HasUpstream returns a boolean if a field has been set.
func (o *LLMProviderConfig) HasUpstream() bool {
	if o != nil && !IsNil(o.Upstream) {
		return true
	}

	return false
}

// SetUpstream gets a reference to the given UpstreamConfig and assigns it to the Upstream field.
func (o *LLMProviderConfig) SetUpstream(v UpstreamConfig) {
	o.Upstream = &v
}

// GetAccessControl returns the AccessControl field value if set, zero value otherwise.
func (o *LLMProviderConfig) GetAccessControl() LLMAccessControl {
	if o == nil || IsNil(o.AccessControl) {
		var ret LLMAccessControl
		return ret
	}
	return *o.AccessControl
}

// GetAccessControlOk returns a tuple with the AccessControl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderConfig) GetAccessControlOk() (*LLMAccessControl, bool) {
	if o == nil || IsNil(o.AccessControl) {
		return nil, false
	}
	return o.AccessControl, true
}

// HasAccessControl returns a boolean if a field has been set.
func (o *LLMProviderConfig) HasAccessControl() bool {
	if o != nil && !IsNil(o.AccessControl) {
		return true
	}

	return false
}

// SetAccessControl gets a reference to the given LLMAccessControl and assigns it to the AccessControl field.
func (o *LLMProviderConfig) SetAccessControl(v LLMAccessControl) {
	o.AccessControl = &v
}

// GetRateLimiting returns the RateLimiting field value if set, zero value otherwise.
func (o *LLMProviderConfig) GetRateLimiting() LLMRateLimitingConfig {
	if o == nil || IsNil(o.RateLimiting) {
		var ret LLMRateLimitingConfig
		return ret
	}
	return *o.RateLimiting
}

// GetRateLimitingOk returns a tuple with the RateLimiting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderConfig) GetRateLimitingOk() (*LLMRateLimitingConfig, bool) {
	if o == nil || IsNil(o.RateLimiting) {
		return nil, false
	}
	return o.RateLimiting, true
}

// HasRateLimiting returns a boolean if a field has been set.
func (o *LLMProviderConfig) HasRateLimiting() bool {
	if o != nil && !IsNil(o.RateLimiting) {
		return true
	}

	return false
}

// SetRateLimiting gets a reference to the given LLMRateLimitingConfig and assigns it to the RateLimiting field.
func (o *LLMProviderConfig) SetRateLimiting(v LLMRateLimitingConfig) {
	o.RateLimiting = &v
}

// GetPolicies returns the Policies field value if set, zero value otherwise.
func (o *LLMProviderConfig) GetPolicies() []LLMPolicy {
	if o == nil || IsNil(o.Policies) {
		var ret []LLMPolicy
		return ret
	}
	return o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderConfig) GetPoliciesOk() ([]LLMPolicy, bool) {
	if o == nil || IsNil(o.Policies) {
		return nil, false
	}
	return o.Policies, true
}

// HasPolicies returns a boolean if a field has been set.
func (o *LLMProviderConfig) HasPolicies() bool {
	if o != nil && !IsNil(o.Policies) {
		return true
	}

	return false
}

// SetPolicies gets a reference to the given []LLMPolicy and assigns it to the Policies field.
func (o *LLMProviderConfig) SetPolicies(v []LLMPolicy) {
	o.Policies = v
}

// GetSecurity returns the Security field value if set, zero value otherwise.
func (o *LLMProviderConfig) GetSecurity() SecurityConfig {
	if o == nil || IsNil(o.Security) {
		var ret SecurityConfig
		return ret
	}
	return *o.Security
}

// GetSecurityOk returns a tuple with the Security field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderConfig) GetSecurityOk() (*SecurityConfig, bool) {
	if o == nil || IsNil(o.Security) {
		return nil, false
	}
	return o.Security, true
}

// HasSecurity returns a boolean if a field has been set.
func (o *LLMProviderConfig) HasSecurity() bool {
	if o != nil && !IsNil(o.Security) {
		return true
	}

	return false
}

// SetSecurity gets a reference to the given SecurityConfig and assigns it to the Security field.
func (o *LLMProviderConfig) SetSecurity(v SecurityConfig) {
	o.Security = &v
}

func (o LLMProviderConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMProviderConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Vhost) {
		toSerialize["vhost"] = o.Vhost
	}
	if !IsNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	if !IsNil(o.Upstream) {
		toSerialize["upstream"] = o.Upstream
	}
	if !IsNil(o.AccessControl) {
		toSerialize["accessControl"] = o.AccessControl
	}
	if !IsNil(o.RateLimiting) {
		toSerialize["rateLimiting"] = o.RateLimiting
	}
	if !IsNil(o.Policies) {
		toSerialize["policies"] = o.Policies
	}
	if !IsNil(o.Security) {
		toSerialize["security"] = o.Security
	}
	return toSerialize, nil
}

type NullableLLMProviderConfig struct {
	value *LLMProviderConfig
	isSet bool
}

func (v NullableLLMProviderConfig) Get() *LLMProviderConfig {
	return v.value
}

func (v *NullableLLMProviderConfig) Set(val *LLMProviderConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMProviderConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMProviderConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMProviderConfig(val *LLMProviderConfig) *NullableLLMProviderConfig {
	return &NullableLLMProviderConfig{value: val, isSet: true}
}

func (v NullableLLMProviderConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMProviderConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
