/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ConsoleActionBatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsoleActionBatchRequest{}

// ConsoleActionBatchRequest A flush of console actions buffered by the browser.
type ConsoleActionBatchRequest struct {
	// The buffered actions, oldest first. Capped so a single flush cannot be used to push an unbounded payload through to the collector.
	Actions []ConsoleAction `json:"actions"`
}

// NewConsoleActionBatchRequest instantiates a new ConsoleActionBatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsoleActionBatchRequest(actions []ConsoleAction) *ConsoleActionBatchRequest {
	this := ConsoleActionBatchRequest{}
	this.Actions = actions
	return &this
}

// NewConsoleActionBatchRequestWithDefaults instantiates a new ConsoleActionBatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsoleActionBatchRequestWithDefaults() *ConsoleActionBatchRequest {
	this := ConsoleActionBatchRequest{}
	return &this
}

// GetActions returns the Actions field value
func (o *ConsoleActionBatchRequest) GetActions() []ConsoleAction {
	if o == nil {
		var ret []ConsoleAction
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *ConsoleActionBatchRequest) GetActionsOk() ([]ConsoleAction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *ConsoleActionBatchRequest) SetActions(v []ConsoleAction) {
	o.Actions = v
}

func (o ConsoleActionBatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsoleActionBatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["actions"] = o.Actions
	return toSerialize, nil
}

type NullableConsoleActionBatchRequest struct {
	value *ConsoleActionBatchRequest
	isSet bool
}

func (v NullableConsoleActionBatchRequest) Get() *ConsoleActionBatchRequest {
	return v.value
}

func (v *NullableConsoleActionBatchRequest) Set(val *ConsoleActionBatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConsoleActionBatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConsoleActionBatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsoleActionBatchRequest(val *ConsoleActionBatchRequest) *NullableConsoleActionBatchRequest {
	return &NullableConsoleActionBatchRequest{value: val, isSet: true}
}

func (v NullableConsoleActionBatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsoleActionBatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
