/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MonitorAlertThreshold type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonitorAlertThreshold{}

// MonitorAlertThreshold struct for MonitorAlertThreshold
type MonitorAlertThreshold struct {
	// Display name of one of the monitor's evaluators.
	Evaluator string `json:"evaluator"`
	// Aggregation key reported for the evaluator (e.g. mean, median, min, p50).
	Aggregation string `json:"aggregation"`
	// Alert when the aggregated score is below (lt) or at-or-below (lte) the value.
	Operator *string `json:"operator,omitempty"`
	Value    float64 `json:"value"`
}

// NewMonitorAlertThreshold instantiates a new MonitorAlertThreshold object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonitorAlertThreshold(evaluator string, aggregation string, value float64) *MonitorAlertThreshold {
	this := MonitorAlertThreshold{}
	this.Evaluator = evaluator
	this.Aggregation = aggregation
	var operator string = "lt"
	this.Operator = &operator
	this.Value = value
	return &this
}

// NewMonitorAlertThresholdWithDefaults instantiates a new MonitorAlertThreshold object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonitorAlertThresholdWithDefaults() *MonitorAlertThreshold {
	this := MonitorAlertThreshold{}
	var operator string = "lt"
	this.Operator = &operator
	return &this
}

// GetEvaluator returns the Evaluator field value
func (o *MonitorAlertThreshold) GetEvaluator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Evaluator
}

// GetEvaluatorOk returns a tuple with the Evaluator field value
// and a boolean to check if the value has been set.
func (o *MonitorAlertThreshold) GetEvaluatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Evaluator, true
}

// SetEvaluator sets field value
func (o *MonitorAlertThreshold) SetEvaluator(v string) {
	o.Evaluator = v
}

// GetAggregation returns the Aggregation field value
func (o *MonitorAlertThreshold) GetAggregation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Aggregation
}

// GetAggregationOk returns a tuple with the Aggregation field value
// and a boolean to check if the value has been set.
func (o *MonitorAlertThreshold) GetAggregationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aggregation, true
}

// SetAggregation sets field value
func (o *MonitorAlertThreshold) SetAggregation(v string) {
	o.Aggregation = v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *MonitorAlertThreshold) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitorAlertThreshold) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *MonitorAlertThreshold) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *MonitorAlertThreshold) SetOperator(v string) {
	o.Operator = &v
}

// GetValue returns the Value field value
func (o *MonitorAlertThreshold) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *MonitorAlertThreshold) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *MonitorAlertThreshold) SetValue(v float64) {
	o.Value = v
}

func (o MonitorAlertThreshold) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonitorAlertThreshold) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["evaluator"] = o.Evaluator
	toSerialize["aggregation"] = o.Aggregation
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableMonitorAlertThreshold struct {
	value *MonitorAlertThreshold
	isSet bool
}

func (v NullableMonitorAlertThreshold) Get() *MonitorAlertThreshold {
	return v.value
}

func (v *NullableMonitorAlertThreshold) Set(val *MonitorAlertThreshold) {
	v.value = val
	v.isSet = true
}

func (v NullableMonitorAlertThreshold) IsSet() bool {
	return v.isSet
}

func (v *NullableMonitorAlertThreshold) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonitorAlertThreshold(val *MonitorAlertThreshold) *NullableMonitorAlertThreshold {
	return &NullableMonitorAlertThreshold{value: val, isSet: true}
}

func (v NullableMonitorAlertThreshold) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonitorAlertThreshold) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
