/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateEnvironmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEnvironmentRequest{}

// UpdateEnvironmentRequest struct for UpdateEnvironmentRequest
type UpdateEnvironmentRequest struct {
	// Updated display name
	DisplayName *string `json:"displayName,omitempty"`
	// Updated description
	Description NullableString `json:"description,omitempty"`
}

// NewUpdateEnvironmentRequest instantiates a new UpdateEnvironmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEnvironmentRequest() *UpdateEnvironmentRequest {
	this := UpdateEnvironmentRequest{}
	return &this
}

// NewUpdateEnvironmentRequestWithDefaults instantiates a new UpdateEnvironmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEnvironmentRequestWithDefaults() *UpdateEnvironmentRequest {
	this := UpdateEnvironmentRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *UpdateEnvironmentRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEnvironmentRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UpdateEnvironmentRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *UpdateEnvironmentRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateEnvironmentRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateEnvironmentRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateEnvironmentRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *UpdateEnvironmentRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *UpdateEnvironmentRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *UpdateEnvironmentRequest) UnsetDescription() {
	o.Description.Unset()
}

func (o UpdateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEnvironmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	return toSerialize, nil
}

type NullableUpdateEnvironmentRequest struct {
	value *UpdateEnvironmentRequest
	isSet bool
}

func (v NullableUpdateEnvironmentRequest) Get() *UpdateEnvironmentRequest {
	return v.value
}

func (v *NullableUpdateEnvironmentRequest) Set(val *UpdateEnvironmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEnvironmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEnvironmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEnvironmentRequest(val *UpdateEnvironmentRequest) *NullableUpdateEnvironmentRequest {
	return &NullableUpdateEnvironmentRequest{value: val, isSet: true}
}

func (v NullableUpdateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEnvironmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
