/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RotateLLMAPIKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateLLMAPIKeyResponse{}

// RotateLLMAPIKeyResponse struct for RotateLLMAPIKeyResponse
type RotateLLMAPIKeyResponse struct {
	// Result of the operation (\"success\" or \"error\").
	Status string `json:"status"`
	// Additional details about the operation result.
	Message string `json:"message"`
	// Unique identifier of the rotated key.
	KeyId *string `json:"keyId,omitempty"`
	// New API key value. Returned only once; store it securely.
	ApiKey *string `json:"apiKey,omitempty"`
}

// NewRotateLLMAPIKeyResponse instantiates a new RotateLLMAPIKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateLLMAPIKeyResponse(status string, message string) *RotateLLMAPIKeyResponse {
	this := RotateLLMAPIKeyResponse{}
	this.Status = status
	this.Message = message
	return &this
}

// NewRotateLLMAPIKeyResponseWithDefaults instantiates a new RotateLLMAPIKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateLLMAPIKeyResponseWithDefaults() *RotateLLMAPIKeyResponse {
	this := RotateLLMAPIKeyResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *RotateLLMAPIKeyResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RotateLLMAPIKeyResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RotateLLMAPIKeyResponse) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *RotateLLMAPIKeyResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *RotateLLMAPIKeyResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *RotateLLMAPIKeyResponse) SetMessage(v string) {
	o.Message = v
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *RotateLLMAPIKeyResponse) GetKeyId() string {
	if o == nil || IsNil(o.KeyId) {
		var ret string
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotateLLMAPIKeyResponse) GetKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.KeyId) {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *RotateLLMAPIKeyResponse) HasKeyId() bool {
	if o != nil && !IsNil(o.KeyId) {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given string and assigns it to the KeyId field.
func (o *RotateLLMAPIKeyResponse) SetKeyId(v string) {
	o.KeyId = &v
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *RotateLLMAPIKeyResponse) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey) {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotateLLMAPIKeyResponse) GetApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *RotateLLMAPIKeyResponse) HasApiKey() bool {
	if o != nil && !IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *RotateLLMAPIKeyResponse) SetApiKey(v string) {
	o.ApiKey = &v
}

func (o RotateLLMAPIKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateLLMAPIKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	if !IsNil(o.KeyId) {
		toSerialize["keyId"] = o.KeyId
	}
	if !IsNil(o.ApiKey) {
		toSerialize["apiKey"] = o.ApiKey
	}
	return toSerialize, nil
}

type NullableRotateLLMAPIKeyResponse struct {
	value *RotateLLMAPIKeyResponse
	isSet bool
}

func (v NullableRotateLLMAPIKeyResponse) Get() *RotateLLMAPIKeyResponse {
	return v.value
}

func (v *NullableRotateLLMAPIKeyResponse) Set(val *RotateLLMAPIKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateLLMAPIKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateLLMAPIKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateLLMAPIKeyResponse(val *RotateLLMAPIKeyResponse) *NullableRotateLLMAPIKeyResponse {
	return &NullableRotateLLMAPIKeyResponse{value: val, isSet: true}
}

func (v NullableRotateLLMAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateLLMAPIKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
