/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ExtractionIdentifier type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtractionIdentifier{}

// ExtractionIdentifier struct for ExtractionIdentifier
type ExtractionIdentifier struct {
	// Where to find the token information
	Location string `json:"location"`
	// JSONPath or other identifier to extract the value
	Identifier string `json:"identifier"`
}

// NewExtractionIdentifier instantiates a new ExtractionIdentifier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtractionIdentifier(location string, identifier string) *ExtractionIdentifier {
	this := ExtractionIdentifier{}
	this.Location = location
	this.Identifier = identifier
	return &this
}

// NewExtractionIdentifierWithDefaults instantiates a new ExtractionIdentifier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtractionIdentifierWithDefaults() *ExtractionIdentifier {
	this := ExtractionIdentifier{}
	return &this
}

// GetLocation returns the Location field value
func (o *ExtractionIdentifier) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *ExtractionIdentifier) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *ExtractionIdentifier) SetLocation(v string) {
	o.Location = v
}

// GetIdentifier returns the Identifier field value
func (o *ExtractionIdentifier) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *ExtractionIdentifier) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *ExtractionIdentifier) SetIdentifier(v string) {
	o.Identifier = v
}

func (o ExtractionIdentifier) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtractionIdentifier) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["location"] = o.Location
	toSerialize["identifier"] = o.Identifier
	return toSerialize, nil
}

type NullableExtractionIdentifier struct {
	value *ExtractionIdentifier
	isSet bool
}

func (v NullableExtractionIdentifier) Get() *ExtractionIdentifier {
	return v.value
}

func (v *NullableExtractionIdentifier) Set(val *ExtractionIdentifier) {
	v.value = val
	v.isSet = true
}

func (v NullableExtractionIdentifier) IsSet() bool {
	return v.isSet
}

func (v *NullableExtractionIdentifier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtractionIdentifier(val *ExtractionIdentifier) *NullableExtractionIdentifier {
	return &NullableExtractionIdentifier{value: val, isSet: true}
}

func (v NullableExtractionIdentifier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtractionIdentifier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
