/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the HealthStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthStatusResponse{}

// HealthStatusResponse struct for HealthStatusResponse
type HealthStatusResponse struct {
	// UUID of the gateway that was checked
	GatewayId string `json:"gatewayId"`
	// Health check result status
	Status string `json:"status"`
	// Response time from the gateway (if reachable)
	ResponseTime *string `json:"responseTime,omitempty"`
	// Error message if health check failed
	ErrorMessage *string `json:"errorMessage,omitempty"`
	// Timestamp when the health check was performed
	CheckedAt time.Time `json:"checkedAt"`
}

// NewHealthStatusResponse instantiates a new HealthStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthStatusResponse(gatewayId string, status string, checkedAt time.Time) *HealthStatusResponse {
	this := HealthStatusResponse{}
	this.GatewayId = gatewayId
	this.Status = status
	this.CheckedAt = checkedAt
	return &this
}

// NewHealthStatusResponseWithDefaults instantiates a new HealthStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthStatusResponseWithDefaults() *HealthStatusResponse {
	this := HealthStatusResponse{}
	return &this
}

// GetGatewayId returns the GatewayId field value
func (o *HealthStatusResponse) GetGatewayId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value
// and a boolean to check if the value has been set.
func (o *HealthStatusResponse) GetGatewayIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayId, true
}

// SetGatewayId sets field value
func (o *HealthStatusResponse) SetGatewayId(v string) {
	o.GatewayId = v
}

// GetStatus returns the Status field value
func (o *HealthStatusResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HealthStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HealthStatusResponse) SetStatus(v string) {
	o.Status = v
}

// GetResponseTime returns the ResponseTime field value if set, zero value otherwise.
func (o *HealthStatusResponse) GetResponseTime() string {
	if o == nil || IsNil(o.ResponseTime) {
		var ret string
		return ret
	}
	return *o.ResponseTime
}

// GetResponseTimeOk returns a tuple with the ResponseTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthStatusResponse) GetResponseTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseTime) {
		return nil, false
	}
	return o.ResponseTime, true
}

// HasResponseTime returns a boolean if a field has been set.
func (o *HealthStatusResponse) HasResponseTime() bool {
	if o != nil && !IsNil(o.ResponseTime) {
		return true
	}

	return false
}

// SetResponseTime gets a reference to the given string and assigns it to the ResponseTime field.
func (o *HealthStatusResponse) SetResponseTime(v string) {
	o.ResponseTime = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *HealthStatusResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthStatusResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *HealthStatusResponse) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *HealthStatusResponse) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetCheckedAt returns the CheckedAt field value
func (o *HealthStatusResponse) GetCheckedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CheckedAt
}

// GetCheckedAtOk returns a tuple with the CheckedAt field value
// and a boolean to check if the value has been set.
func (o *HealthStatusResponse) GetCheckedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CheckedAt, true
}

// SetCheckedAt sets field value
func (o *HealthStatusResponse) SetCheckedAt(v time.Time) {
	o.CheckedAt = v
}

func (o HealthStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gatewayId"] = o.GatewayId
	toSerialize["status"] = o.Status
	if !IsNil(o.ResponseTime) {
		toSerialize["responseTime"] = o.ResponseTime
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	toSerialize["checkedAt"] = o.CheckedAt
	return toSerialize, nil
}

type NullableHealthStatusResponse struct {
	value *HealthStatusResponse
	isSet bool
}

func (v NullableHealthStatusResponse) Get() *HealthStatusResponse {
	return v.value
}

func (v *NullableHealthStatusResponse) Set(val *HealthStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthStatusResponse(val *HealthStatusResponse) *NullableHealthStatusResponse {
	return &NullableHealthStatusResponse{value: val, isSet: true}
}

func (v NullableHealthStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
