/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMProviderTemplateAuth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMProviderTemplateAuth{}

// LLMProviderTemplateAuth struct for LLMProviderTemplateAuth
type LLMProviderTemplateAuth struct {
	// Authentication type
	Type *string `json:"type,omitempty"`
	// Header name for authentication
	Header *string `json:"header,omitempty"`
	// Prefix for the authentication value
	ValuePrefix *string `json:"valuePrefix,omitempty"`
}

// NewLLMProviderTemplateAuth instantiates a new LLMProviderTemplateAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMProviderTemplateAuth() *LLMProviderTemplateAuth {
	this := LLMProviderTemplateAuth{}
	return &this
}

// NewLLMProviderTemplateAuthWithDefaults instantiates a new LLMProviderTemplateAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMProviderTemplateAuthWithDefaults() *LLMProviderTemplateAuth {
	this := LLMProviderTemplateAuth{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *LLMProviderTemplateAuth) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderTemplateAuth) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *LLMProviderTemplateAuth) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *LLMProviderTemplateAuth) SetType(v string) {
	o.Type = &v
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *LLMProviderTemplateAuth) GetHeader() string {
	if o == nil || IsNil(o.Header) {
		var ret string
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderTemplateAuth) GetHeaderOk() (*string, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *LLMProviderTemplateAuth) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given string and assigns it to the Header field.
func (o *LLMProviderTemplateAuth) SetHeader(v string) {
	o.Header = &v
}

// GetValuePrefix returns the ValuePrefix field value if set, zero value otherwise.
func (o *LLMProviderTemplateAuth) GetValuePrefix() string {
	if o == nil || IsNil(o.ValuePrefix) {
		var ret string
		return ret
	}
	return *o.ValuePrefix
}

// GetValuePrefixOk returns a tuple with the ValuePrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderTemplateAuth) GetValuePrefixOk() (*string, bool) {
	if o == nil || IsNil(o.ValuePrefix) {
		return nil, false
	}
	return o.ValuePrefix, true
}

// HasValuePrefix returns a boolean if a field has been set.
func (o *LLMProviderTemplateAuth) HasValuePrefix() bool {
	if o != nil && !IsNil(o.ValuePrefix) {
		return true
	}

	return false
}

// SetValuePrefix gets a reference to the given string and assigns it to the ValuePrefix field.
func (o *LLMProviderTemplateAuth) SetValuePrefix(v string) {
	o.ValuePrefix = &v
}

func (o LLMProviderTemplateAuth) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMProviderTemplateAuth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	if !IsNil(o.ValuePrefix) {
		toSerialize["valuePrefix"] = o.ValuePrefix
	}
	return toSerialize, nil
}

type NullableLLMProviderTemplateAuth struct {
	value *LLMProviderTemplateAuth
	isSet bool
}

func (v NullableLLMProviderTemplateAuth) Get() *LLMProviderTemplateAuth {
	return v.value
}

func (v *NullableLLMProviderTemplateAuth) Set(val *LLMProviderTemplateAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMProviderTemplateAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMProviderTemplateAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMProviderTemplateAuth(val *LLMProviderTemplateAuth) *NullableLLMProviderTemplateAuth {
	return &NullableLLMProviderTemplateAuth{value: val, isSet: true}
}

func (v NullableLLMProviderTemplateAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMProviderTemplateAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
