/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the MonitorListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonitorListResponse{}

// MonitorListResponse struct for MonitorListResponse
type MonitorListResponse struct {
	// List of monitors
	Monitors []MonitorResponse `json:"monitors"`
	// Total number of monitors
	Total int32 `json:"total"`
}

// NewMonitorListResponse instantiates a new MonitorListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonitorListResponse(monitors []MonitorResponse, total int32) *MonitorListResponse {
	this := MonitorListResponse{}
	this.Monitors = monitors
	this.Total = total
	return &this
}

// NewMonitorListResponseWithDefaults instantiates a new MonitorListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonitorListResponseWithDefaults() *MonitorListResponse {
	this := MonitorListResponse{}
	return &this
}

// GetMonitors returns the Monitors field value
func (o *MonitorListResponse) GetMonitors() []MonitorResponse {
	if o == nil {
		var ret []MonitorResponse
		return ret
	}

	return o.Monitors
}

// GetMonitorsOk returns a tuple with the Monitors field value
// and a boolean to check if the value has been set.
func (o *MonitorListResponse) GetMonitorsOk() ([]MonitorResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Monitors, true
}

// SetMonitors sets field value
func (o *MonitorListResponse) SetMonitors(v []MonitorResponse) {
	o.Monitors = v
}

// GetTotal returns the Total field value
func (o *MonitorListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *MonitorListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *MonitorListResponse) SetTotal(v int32) {
	o.Total = v
}

func (o MonitorListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonitorListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["monitors"] = o.Monitors
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

type NullableMonitorListResponse struct {
	value *MonitorListResponse
	isSet bool
}

func (v NullableMonitorListResponse) Get() *MonitorListResponse {
	return v.value
}

func (v *NullableMonitorListResponse) Set(val *MonitorListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMonitorListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMonitorListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonitorListResponse(val *MonitorListResponse) *NullableMonitorListResponse {
	return &NullableMonitorListResponse{value: val, isSet: true}
}

func (v NullableMonitorListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonitorListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
