/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMTokenUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMTokenUsage{}

// LLMTokenUsage struct for LLMTokenUsage
type LLMTokenUsage struct {
	// Number of input tokens
	InputTokens int32 `json:"inputTokens"`
	// Number of output tokens
	OutputTokens int32 `json:"outputTokens"`
	// Number of cached input tokens read
	CacheReadInputTokens *int32 `json:"cacheReadInputTokens,omitempty"`
	// Total tokens used
	TotalTokens int32 `json:"totalTokens"`
}

// NewLLMTokenUsage instantiates a new LLMTokenUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMTokenUsage(inputTokens int32, outputTokens int32, totalTokens int32) *LLMTokenUsage {
	this := LLMTokenUsage{}
	this.InputTokens = inputTokens
	this.OutputTokens = outputTokens
	this.TotalTokens = totalTokens
	return &this
}

// NewLLMTokenUsageWithDefaults instantiates a new LLMTokenUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMTokenUsageWithDefaults() *LLMTokenUsage {
	this := LLMTokenUsage{}
	return &this
}

// GetInputTokens returns the InputTokens field value
func (o *LLMTokenUsage) GetInputTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InputTokens
}

// GetInputTokensOk returns a tuple with the InputTokens field value
// and a boolean to check if the value has been set.
func (o *LLMTokenUsage) GetInputTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InputTokens, true
}

// SetInputTokens sets field value
func (o *LLMTokenUsage) SetInputTokens(v int32) {
	o.InputTokens = v
}

// GetOutputTokens returns the OutputTokens field value
func (o *LLMTokenUsage) GetOutputTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OutputTokens
}

// GetOutputTokensOk returns a tuple with the OutputTokens field value
// and a boolean to check if the value has been set.
func (o *LLMTokenUsage) GetOutputTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutputTokens, true
}

// SetOutputTokens sets field value
func (o *LLMTokenUsage) SetOutputTokens(v int32) {
	o.OutputTokens = v
}

// GetCacheReadInputTokens returns the CacheReadInputTokens field value if set, zero value otherwise.
func (o *LLMTokenUsage) GetCacheReadInputTokens() int32 {
	if o == nil || IsNil(o.CacheReadInputTokens) {
		var ret int32
		return ret
	}
	return *o.CacheReadInputTokens
}

// GetCacheReadInputTokensOk returns a tuple with the CacheReadInputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMTokenUsage) GetCacheReadInputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.CacheReadInputTokens) {
		return nil, false
	}
	return o.CacheReadInputTokens, true
}

// HasCacheReadInputTokens returns a boolean if a field has been set.
func (o *LLMTokenUsage) HasCacheReadInputTokens() bool {
	if o != nil && !IsNil(o.CacheReadInputTokens) {
		return true
	}

	return false
}

// SetCacheReadInputTokens gets a reference to the given int32 and assigns it to the CacheReadInputTokens field.
func (o *LLMTokenUsage) SetCacheReadInputTokens(v int32) {
	o.CacheReadInputTokens = &v
}

// GetTotalTokens returns the TotalTokens field value
func (o *LLMTokenUsage) GetTotalTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalTokens
}

// GetTotalTokensOk returns a tuple with the TotalTokens field value
// and a boolean to check if the value has been set.
func (o *LLMTokenUsage) GetTotalTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalTokens, true
}

// SetTotalTokens sets field value
func (o *LLMTokenUsage) SetTotalTokens(v int32) {
	o.TotalTokens = v
}

func (o LLMTokenUsage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMTokenUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["inputTokens"] = o.InputTokens
	toSerialize["outputTokens"] = o.OutputTokens
	if !IsNil(o.CacheReadInputTokens) {
		toSerialize["cacheReadInputTokens"] = o.CacheReadInputTokens
	}
	toSerialize["totalTokens"] = o.TotalTokens
	return toSerialize, nil
}

type NullableLLMTokenUsage struct {
	value *LLMTokenUsage
	isSet bool
}

func (v NullableLLMTokenUsage) Get() *LLMTokenUsage {
	return v.value
}

func (v *NullableLLMTokenUsage) Set(val *LLMTokenUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMTokenUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMTokenUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMTokenUsage(val *LLMTokenUsage) *NullableLLMTokenUsage {
	return &NullableLLMTokenUsage{value: val, isSet: true}
}

func (v NullableLLMTokenUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMTokenUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
