/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the TraceOverview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TraceOverview{}

// TraceOverview struct for TraceOverview
type TraceOverview struct {
	// Unique identifier for the trace
	TraceId string `json:"traceId"`
	// ID of the root span in the trace
	RootSpanId string `json:"rootSpanId"`
	// Name of the root span
	RootSpanName string `json:"rootSpanName"`
	// Semantic kind of the root span (llm, tool, embedding, etc.)
	RootSpanKind *string `json:"rootSpanKind,omitempty"`
	// Trace start time
	StartTime time.Time `json:"startTime"`
	// Trace end time
	EndTime time.Time `json:"endTime"`
	// Trace duration in nanoseconds
	DurationInNanos int64 `json:"durationInNanos"`
	// Number of spans in the trace
	SpanCount  int32        `json:"spanCount"`
	TokenUsage *TokenUsage  `json:"tokenUsage,omitempty"`
	Status     *TraceStatus `json:"status,omitempty"`
	// Input from root span's traceloop.entity.input
	Input *string `json:"input,omitempty"`
	// Output from root span's traceloop.entity.output
	Output *string `json:"output,omitempty"`
}

// NewTraceOverview instantiates a new TraceOverview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTraceOverview(traceId string, rootSpanId string, rootSpanName string, startTime time.Time, endTime time.Time, durationInNanos int64, spanCount int32) *TraceOverview {
	this := TraceOverview{}
	this.TraceId = traceId
	this.RootSpanId = rootSpanId
	this.RootSpanName = rootSpanName
	this.StartTime = startTime
	this.EndTime = endTime
	this.DurationInNanos = durationInNanos
	this.SpanCount = spanCount
	return &this
}

// NewTraceOverviewWithDefaults instantiates a new TraceOverview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTraceOverviewWithDefaults() *TraceOverview {
	this := TraceOverview{}
	return &this
}

// GetTraceId returns the TraceId field value
func (o *TraceOverview) GetTraceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraceId, true
}

// SetTraceId sets field value
func (o *TraceOverview) SetTraceId(v string) {
	o.TraceId = v
}

// GetRootSpanId returns the RootSpanId field value
func (o *TraceOverview) GetRootSpanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RootSpanId
}

// GetRootSpanIdOk returns a tuple with the RootSpanId field value
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetRootSpanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RootSpanId, true
}

// SetRootSpanId sets field value
func (o *TraceOverview) SetRootSpanId(v string) {
	o.RootSpanId = v
}

// GetRootSpanName returns the RootSpanName field value
func (o *TraceOverview) GetRootSpanName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RootSpanName
}

// GetRootSpanNameOk returns a tuple with the RootSpanName field value
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetRootSpanNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RootSpanName, true
}

// SetRootSpanName sets field value
func (o *TraceOverview) SetRootSpanName(v string) {
	o.RootSpanName = v
}

// GetRootSpanKind returns the RootSpanKind field value if set, zero value otherwise.
func (o *TraceOverview) GetRootSpanKind() string {
	if o == nil || IsNil(o.RootSpanKind) {
		var ret string
		return ret
	}
	return *o.RootSpanKind
}

// GetRootSpanKindOk returns a tuple with the RootSpanKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetRootSpanKindOk() (*string, bool) {
	if o == nil || IsNil(o.RootSpanKind) {
		return nil, false
	}
	return o.RootSpanKind, true
}

// HasRootSpanKind returns a boolean if a field has been set.
func (o *TraceOverview) HasRootSpanKind() bool {
	if o != nil && !IsNil(o.RootSpanKind) {
		return true
	}

	return false
}

// SetRootSpanKind gets a reference to the given string and assigns it to the RootSpanKind field.
func (o *TraceOverview) SetRootSpanKind(v string) {
	o.RootSpanKind = &v
}

// GetStartTime returns the StartTime field value
func (o *TraceOverview) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *TraceOverview) SetStartTime(v time.Time) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
func (o *TraceOverview) GetEndTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *TraceOverview) SetEndTime(v time.Time) {
	o.EndTime = v
}

// GetDurationInNanos returns the DurationInNanos field value
func (o *TraceOverview) GetDurationInNanos() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DurationInNanos
}

// GetDurationInNanosOk returns a tuple with the DurationInNanos field value
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetDurationInNanosOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationInNanos, true
}

// SetDurationInNanos sets field value
func (o *TraceOverview) SetDurationInNanos(v int64) {
	o.DurationInNanos = v
}

// GetSpanCount returns the SpanCount field value
func (o *TraceOverview) GetSpanCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SpanCount
}

// GetSpanCountOk returns a tuple with the SpanCount field value
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetSpanCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpanCount, true
}

// SetSpanCount sets field value
func (o *TraceOverview) SetSpanCount(v int32) {
	o.SpanCount = v
}

// GetTokenUsage returns the TokenUsage field value if set, zero value otherwise.
func (o *TraceOverview) GetTokenUsage() TokenUsage {
	if o == nil || IsNil(o.TokenUsage) {
		var ret TokenUsage
		return ret
	}
	return *o.TokenUsage
}

// GetTokenUsageOk returns a tuple with the TokenUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetTokenUsageOk() (*TokenUsage, bool) {
	if o == nil || IsNil(o.TokenUsage) {
		return nil, false
	}
	return o.TokenUsage, true
}

// HasTokenUsage returns a boolean if a field has been set.
func (o *TraceOverview) HasTokenUsage() bool {
	if o != nil && !IsNil(o.TokenUsage) {
		return true
	}

	return false
}

// SetTokenUsage gets a reference to the given TokenUsage and assigns it to the TokenUsage field.
func (o *TraceOverview) SetTokenUsage(v TokenUsage) {
	o.TokenUsage = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TraceOverview) GetStatus() TraceStatus {
	if o == nil || IsNil(o.Status) {
		var ret TraceStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetStatusOk() (*TraceStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TraceOverview) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given TraceStatus and assigns it to the Status field.
func (o *TraceOverview) SetStatus(v TraceStatus) {
	o.Status = &v
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *TraceOverview) GetInput() string {
	if o == nil || IsNil(o.Input) {
		var ret string
		return ret
	}
	return *o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetInputOk() (*string, bool) {
	if o == nil || IsNil(o.Input) {
		return nil, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *TraceOverview) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given string and assigns it to the Input field.
func (o *TraceOverview) SetInput(v string) {
	o.Input = &v
}

// GetOutput returns the Output field value if set, zero value otherwise.
func (o *TraceOverview) GetOutput() string {
	if o == nil || IsNil(o.Output) {
		var ret string
		return ret
	}
	return *o.Output
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceOverview) GetOutputOk() (*string, bool) {
	if o == nil || IsNil(o.Output) {
		return nil, false
	}
	return o.Output, true
}

// HasOutput returns a boolean if a field has been set.
func (o *TraceOverview) HasOutput() bool {
	if o != nil && !IsNil(o.Output) {
		return true
	}

	return false
}

// SetOutput gets a reference to the given string and assigns it to the Output field.
func (o *TraceOverview) SetOutput(v string) {
	o.Output = &v
}

func (o TraceOverview) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TraceOverview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["traceId"] = o.TraceId
	toSerialize["rootSpanId"] = o.RootSpanId
	toSerialize["rootSpanName"] = o.RootSpanName
	if !IsNil(o.RootSpanKind) {
		toSerialize["rootSpanKind"] = o.RootSpanKind
	}
	toSerialize["startTime"] = o.StartTime
	toSerialize["endTime"] = o.EndTime
	toSerialize["durationInNanos"] = o.DurationInNanos
	toSerialize["spanCount"] = o.SpanCount
	if !IsNil(o.TokenUsage) {
		toSerialize["tokenUsage"] = o.TokenUsage
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	if !IsNil(o.Output) {
		toSerialize["output"] = o.Output
	}
	return toSerialize, nil
}

type NullableTraceOverview struct {
	value *TraceOverview
	isSet bool
}

func (v NullableTraceOverview) Get() *TraceOverview {
	return v.value
}

func (v *NullableTraceOverview) Set(val *TraceOverview) {
	v.value = val
	v.isSet = true
}

func (v NullableTraceOverview) IsSet() bool {
	return v.isSet
}

func (v *NullableTraceOverview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTraceOverview(val *TraceOverview) *NullableTraceOverview {
	return &NullableTraceOverview{value: val, isSet: true}
}

func (v NullableTraceOverview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTraceOverview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
