// Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package repositories

import (
	"errors"
	"time"

	"gorm.io/gorm"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"

	"github.com/wso2/ai-agent-management-platform/agent-manager-service/models"
)

// OrganizationRepository defines the interface for organization data access
// Organizations table only stores UUID mappings for organization names
type OrganizationRepository interface {
	CreateOrganization(org *models.Organization) error
	GetOrganizationByName(name string) (*models.Organization, error)
	GetOrganizationByUUID(orgId string) (*models.Organization, error)
	ListOrganizations(limit, offset int) ([]*models.Organization, error)
	GetOrCreateOrganization(name string) (*models.Organization, error)
}

// OrganizationRepo implements OrganizationRepository using GORM
type OrganizationRepo struct {
	db *gorm.DB
}

// NewOrganizationRepo creates a new organization repository
func NewOrganizationRepo(db *gorm.DB) OrganizationRepository {
	return &OrganizationRepo{db: db}
}

// CreateOrganization inserts a new organization
func (r *OrganizationRepo) CreateOrganization(org *models.Organization) error {
	if org.CreatedAt.IsZero() {
		org.CreatedAt = time.Now()
	}
	return r.db.Create(org).Error
}

// GetOrganizationByName retrieves an organization by name
func (r *OrganizationRepo) GetOrganizationByName(name string) (*models.Organization, error) {
	var org models.Organization
	err := r.db.Where("name = ?", name).First(&org).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, err
		}
		return nil, err
	}
	return &org, nil
}

// GetOrganizationByUUID retrieves an organization by UUID
func (r *OrganizationRepo) GetOrganizationByUUID(orgId string) (*models.Organization, error) {
	var org models.Organization
	err := r.db.Where("uuid = ?", orgId).First(&org).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, err
		}
		return nil, err
	}
	return &org, nil
}

// GetOrCreateOrganization gets an existing organization or creates a new one
// This is used for on-demand organization UUID generation
func (r *OrganizationRepo) GetOrCreateOrganization(name string) (*models.Organization, error) {
	// Try to get existing organization
	org, err := r.GetOrganizationByName(name)
	if err == nil {
		return org, nil
	}

	// If not found, create new organization with generated UUID
	if errors.Is(err, gorm.ErrRecordNotFound) {
		newOrg := &models.Organization{
			Name:      name,
			UUID:      uuid.New(),
			CreatedAt: time.Now(),
		}
		// UUID is auto-generated by database
		if err := r.CreateOrganization(newOrg); err != nil {
			// Check if it's a unique constraint violation (race condition)
			var pgErr *pgconn.PgError
			if errors.As(err, &pgErr) && pgErr.Code == "23505" { // unique_violation
				// Another goroutine created the organization, fetch it
				return r.GetOrganizationByName(name)
			}
			return nil, err
		}
		// Fetch the created organization to get the generated UUID
		return r.GetOrganizationByName(name)
	}

	return nil, err
}

// ListOrganizations retrieves organizations with pagination
func (r *OrganizationRepo) ListOrganizations(limit, offset int) ([]*models.Organization, error) {
	var organizations []*models.Organization
	err := r.db.Order("created_at DESC").
		Limit(limit).
		Offset(offset).
		Find(&organizations).Error
	return organizations, err
}
