apiVersion: gateway.api-platform.wso2.com/v1alpha1
kind: APIGateway
metadata:
  name: obs-gateway
  namespace: openchoreo-data-plane
spec:
  apiSelector:
    scope: Cluster
  infrastructure:
    labels:
      # NetworkPolicy now allows ingress only from pods with the openchoreo.dev/system-component
      openchoreo.dev/system-component: "true"
  configRef:
    name: obs-gateway-config
