apiVersion: api.api-platform.wso2.com/v1
kind: APIConfiguration
metadata:
  name: traces-api-v1.0
spec:
  displayName: traces-api
  version: v1.0
  context: /traces
  upstream:
    main:
      url : http://opentelemetry-collector.openchoreo-observability-plane.svc.cluster.local:4318
  policies:
    - name: jwt-auth
      version: v0.1.0
      params:
        issuers:
          - agent-manager-service
        claimMappings:
          sub: X-User-ID
          component-uid: x-user-component
          environment-uid: x-user-environment
  operations:
    - method: POST
      path: /v1/traces