apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: amp-monitor-evaluation
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "15"
  labels:
{{- include "amp-evaluation-extension.labels" . | nindent 4 }}
spec:
  entrypoint: run-monitor
  arguments:
    parameters:
      - name: monitor-name
      - name: agent-name
      - name: evaluator-names
      - name: sampling-rate
      - name: trace-start
      - name: trace-end
      - name: traces-api-endpoint
      - name: org-name
  templates:
    - name: run-monitor
      container:
        image: '{{ include "amp-evaluation-extension.image" . }}'
        imagePullPolicy: {{ .Values.ampEvaluation.image.pullPolicy }}
        command: ["python", "-m", "amp_evaluation.cli.monitor"]
        args:
          - '--monitor-name={{ "{{" }}workflow.parameters.monitor-name{{ "}}" }}'
          - '--agent-name={{ "{{" }}workflow.parameters.agent-name{{ "}}" }}'
          - '--evaluators={{ "{{" }}workflow.parameters.evaluator-names{{ "}}" }}'
          - '--sampling-rate={{ "{{" }}workflow.parameters.sampling-rate{{ "}}" }}'
          - '--trace-start={{ "{{" }}workflow.parameters.trace-start{{ "}}" }}'
          - '--trace-end={{ "{{" }}workflow.parameters.trace-end{{ "}}" }}'
          - '--traces-api-endpoint={{ "{{" }}workflow.parameters.traces-api-endpoint{{ "}}" }}'
          - '--org-name={{ "{{" }}workflow.parameters.org-name{{ "}}" }}'
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
  ttlStrategy:
    secondsAfterCompletion: 3600
