apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: amp-monitor-evaluation
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "15"
  labels:
{{- include "amp-evaluation-extension.labels" . | nindent 4 }}
spec:
  entrypoint: run-monitor
  arguments:
    parameters:
      - name: monitor-name
      - name: agent-id
      - name: environment-id
      - name: evaluators
      - name: sampling-rate
        value: "1.0"
      - name: trace-start
      - name: trace-end
      - name: traces-api-endpoint
      - name: monitor-id
      - name: run-id
      - name: publisher-endpoint
      - name: publisher-api-key
  templates:
    - name: run-monitor
      container:
        image: '{{ include "amp-evaluation-extension.image" . }}'
        imagePullPolicy: {{ .Values.ampEvaluation.image.pullPolicy }}
        command: ["python", "main.py"]
        args:
          - '--monitor-name={{ "{{" }}workflow.parameters.monitor-name{{ "}}" }}'
          - '--agent-id={{ "{{" }}workflow.parameters.agent-id{{ "}}" }}'
          - '--environment-id={{ "{{" }}workflow.parameters.environment-id{{ "}}" }}'
          - '--evaluators={{ "{{" }}workflow.parameters.evaluators{{ "}}" }}'
          - '--sampling-rate={{ "{{" }}workflow.parameters.sampling-rate{{ "}}" }}'
          - '--trace-start={{ "{{" }}workflow.parameters.trace-start{{ "}}" }}'
          - '--trace-end={{ "{{" }}workflow.parameters.trace-end{{ "}}" }}'
          - '--traces-api-endpoint={{ "{{" }}workflow.parameters.traces-api-endpoint{{ "}}" }}'
          - '--monitor-id={{ "{{" }}workflow.parameters.monitor-id{{ "}}" }}'
          - '--run-id={{ "{{" }}workflow.parameters.run-id{{ "}}" }}'
          - '--publisher-endpoint={{ "{{" }}workflow.parameters.publisher-endpoint{{ "}}" }}'
        env:
          - name: PUBLISHER_API_KEY
            value: '{{ "{{" }}workflow.parameters.publisher-api-key{{ "}}" }}'
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
  ttlStrategy:
    secondsAfterCompletion: 3600
