apiVersion: openchoreo.dev/v1alpha1
kind: ComponentType
metadata:
  name: agent-api
  namespace: default
  annotations:
    openchoreo.dev/display-name: Platform Hosted Agent API
    openchoreo.dev/description: Component type for deploying agent APIs in the AI Agent Management Platform.
spec:
  workloadType: deployment

  allowedWorkflows:
    - amp-google-cloud-buildpacks
    - amp-ballerina-buildpack
    - amp-docker
  allowedTraits:
    - python-otel-instrumentation-trait
  schema:
    types:
      ResourceRequirements:
        requests: "ResourceQuantity | default={}"
        limits: "ResourceQuantity | default={}"
      ResourceQuantity:
        cpu: "string | default=100m"
        memory: "string | default=256Mi"
      CORSConfig:
        allowOrigin: "[]string"
        allowMethods: "[]string"
        allowHeaders: "[]string"

    parameters:
      replicas: "integer | default=1"
      imagePullPolicy: "string | default=IfNotPresent"
      port: "integer | default=80"
      exposed: "boolean | default=false"
      containerName: "string | default=main"
      basePath: "string | default=/"
      cors: 'CORSConfig | default={"allowOrigin": ["http://localhost:3000"], "allowMethods": ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"], "allowHeaders": ["authorization", "Content-Type", "Origin"]}'

    envOverrides:
      resources: "ResourceRequirements | default={}"

  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${metadata.name}
          namespace: ${metadata.namespace}
          labels: ${metadata.labels}
        spec:
          replicas: ${parameters.replicas}
          selector:
            matchLabels: ${metadata.podSelectors}
          template:
            metadata:
              labels: ${metadata.podSelectors}
              annotations:
                openchoreo.dev/config-hash: |
                  ${has(configurations[parameters.containerName].configs.envs) && configurations[parameters.containerName].configs.envs.size() > 0 ? oc_hash(configurations[parameters.containerName].configs.envs.map(e, e.name + "=" + e.value).join(",")) : oc_hash("no-env")}
            spec:
              containers:
                - name: ${parameters.containerName}
                  image: ${workload.containers[parameters.containerName].image}
                  imagePullPolicy: ${parameters.imagePullPolicy}
                  command: |
                    ${has(workload.containers[parameters.containerName].command) ? workload.containers[parameters.containerName].command : oc_omit()}
                  args: |
                    ${has(workload.containers[parameters.containerName].args) ? workload.containers[parameters.containerName].args : oc_omit()}
                  ports:
                    - name: http
                      containerPort: ${parameters.port}
                      protocol: TCP
                  resources:
                    requests:
                      cpu: ${envOverrides.resources.requests.cpu}
                      memory: ${envOverrides.resources.requests.memory}
                    limits:
                      cpu: ${envOverrides.resources.limits.cpu}
                      memory: ${envOverrides.resources.limits.memory}
                  envFrom: ${configurations.toContainerEnvFrom(parameters.containerName)}
                  volumeMounts: ${configurations.toContainerVolumeMounts(parameters.containerName)}
              volumes: ${configurations.toVolumes()}

    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${metadata.componentName}
          namespace: ${metadata.namespace}
          labels: ${metadata.labels}
        spec:
          type: ClusterIP
          selector: ${metadata.podSelectors}
          ports:
            - name: http
              port: 80
              targetPort: ${parameters.port}
              protocol: TCP
    - id: httproute
      includeWhen: ${parameters.exposed == true}
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${metadata.name}
          namespace: ${metadata.namespace}
          labels: ${metadata.labels}
        spec:
          parentRefs:
            - name: gateway-default
              namespace: openchoreo-data-plane
          hostnames:
            - ${metadata.componentNamespace}.${metadata.environmentName}.${dataplane.publicVirtualHost}
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /${metadata.componentName}
              filters:
                - type: URLRewrite
                  urlRewrite:
                    path:
                      type: ReplacePrefixMatch
                      replacePrefixMatch: ${parameters.basePath}
                - type: CORS
                  cors:
                    allowOrigins: ${parameters.cors.allowOrigin}
                    allowMethods: ${parameters.cors.allowMethods}
                    allowHeaders: ${parameters.cors.allowHeaders}
              backendRefs:
                - name: ${metadata.componentName}
                  port: 80
    - id: env-config
      forEach: ${configurations.toConfigEnvsByContainer()}
      var: envConfig
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${envConfig.resourceName}
          namespace: ${metadata.namespace}
        data: |
          ${envConfig.envs.transformMapEntry(index, env, {env.name: env.value})}
