apiVersion: openchoreo.dev/v1alpha1
kind: ComponentWorkflow
metadata:
  name: ballerina-buildpack
  namespace: default
  annotations:
    openchoreo.dev/description: "Ballerina build workflow for containerized builds using Ballerina Buildpack"
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "7"
spec:
  # Schema definition for component workflows
  schema:
    types:
      Endpoint:
        name: "string | description='Endpoint name'"
        port: "integer | description='Port number'"
        type: "string | description='Endpoint type (e.g., HTTP, gRPC)' | default='HTTP'"
        schemaType: "string | description='Schema type (e.g., REST)' | default='REST'"
        schemaFilePath: "string | description='Path to schema file relative to app path (optional)' | default=''"
        schemaContent: "string | description='Inline schema content (optional)' | default=''"
      EnvironmentVariable:
        name: "string | description='Environment variable name'"
        value: "string | description='Environment variable value'"

    # System parameters - Required structured parameters for component builds
    # These fields are necessary for build-specific platform features (webhooks, auto-build, UI actions)
    # Platform Engineers can customize defaults, enums, and descriptions, but must maintain the field structure
    # Note: All systemParameters fields must be of type string to ensure compatibility with build automation
    systemParameters:
      repository:
        url: string | description="Git repository URL"
        revision:
          branch: string | default=main description="Git branch to checkout"
          commit: string | description="Git commit SHA or reference (optional, defaults to latest)"
        appPath: string | default=. description="Path to the Ballerina application directory within the repository"

    # Developer-configurable parameters - PE-defined schema for additional build configuration
    parameters:
      buildpackConfigs:
        language: string | default="" description="Programming language for the buildpack"
      endpoints: "[]Endpoint | description='List of endpoints exposed'"
      environmentVariables: "[]EnvironmentVariable | description='List of environment variables'"

  # Rendered workflow resource for ComponentWorkflowRun executions
  runTemplate:
    apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    metadata:
      name: ${metadata.workflowRunName}
      namespace: openchoreo-ci-${metadata.orgName}
    spec:
      arguments:
        parameters:
          - name: component-name
            value: ${metadata.componentName}
          - name: project-name
            value: ${metadata.projectName}
          # Parameters from system parameters (developer-facing)
          - name: git-repo
            value: ${systemParameters.repository.url}
          - name: branch
            value: ${systemParameters.repository.revision.branch}
          - name: commit
            value: ${systemParameters.repository.revision.commit}
          - name: app-path
            value: ${systemParameters.repository.appPath}
          # PE-controlled hardcoded parameters
          - name: image-name
            value: ${metadata.workflowRunName}-image
          - name: image-tag
            value: v1
          # Parameters from developer-configurable parameters
          - name: endpoints
            value: ${parameters.endpoints}
          - name: environment-variables
            value: ${parameters.environmentVariables}
          - name: language
            value: ${parameters.buildpackConfigs.language}
      serviceAccountName: workflow-sa
      workflowTemplateRef:
        clusterScope: true
        name: ballerina-buildpack-ci # ← References the ClusterWorkflowTemplate
