---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-default-namespace-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: label-default-namespace-role
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-default-namespace-rolebinding
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
  - kind: ServiceAccount
    name: label-default-namespace-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: label-default-namespace-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: label-default-namespace
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: label-default-namespace-sa
      containers:
        - name: label-namespace
          image: {{ .Values.kubectl.image }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "Waiting for RBAC permissions to propagate..."

              for i in $(seq 1 10); do
                if kubectl auth can-i patch namespaces default >/dev/null 2>&1; then
                  echo "RBAC is ready"
                  break
                fi
                echo "RBAC not ready yet, retrying..."
                sleep 2
              done

              echo "Labeling default namespace as OpenChoreo control plane namespace..."
              kubectl label namespace default \
                openchoreo.dev/controlplane-namespace=true \
                --overwrite

              echo "Successfully labeled default namespace"
      restartPolicy: Never
  backoffLimit: 3
