{{- if .Values.openbao.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
    {{- include "wso2-amp-secrets-extension.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider:
    vault:
      server: http://openbao.{{ .Release.Namespace }}.svc:8200
      path: {{ .Values.secretStore.path | quote }}
      version: {{ .Values.secretStore.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.secretStore.auth.kubernetes.mountPath }}
          role: {{ .Values.secretStore.auth.kubernetes.writerRole }}
          serviceAccountRef:
            name: {{ .Values.secretStore.auth.kubernetes.serviceAccountName }}
            namespace: {{ .Values.secretStore.auth.kubernetes.serviceAccountNamespace | default .Release.Namespace }}
{{- end }}
