{{- if .Values.openbao.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secretStore.auth.kubernetes.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wso2-amp-secrets-extension.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
