{{- if .Values.openbao.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openbao-wait-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wso2-amp-secrets-extension.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "7"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openbao-wait-role
subjects:
  - kind: ServiceAccount
    name: openbao-wait-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
