{{- if .Values.openbao.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openbao-wait-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wso2-amp-secrets-extension.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "6"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
{{- end }}
