// Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// UNIT tests for AgentTokenManagerService.
//
// Like agent_kind_service_unit_test.go (the reference for this package), this
// file carries NO `//go:build integration` tag, so it runs in the fast unit
// tier. The only external collaborator — the OpenChoreo client — is mocked with
// clientmocks.OpenChoreoClientMock. There is no DB dependency.
//
// The JWT signer needs real RSA keys on disk. The unit-test runner generates
// them at <repo-root>/keys/private.pem + keys/public.pem with a matching
// keys/public-keys-config.json (see scripts/gen_keys.sh). Because `go test`
// runs with the package directory (services/) as the working directory, the
// keys live at ../keys relative to cwd. testJWTConfig() points the config at
// those files so a fully-working signer can be constructed in-process — letting
// us assert the real signed-token happy path, not just validation gates.
package services

import (
	"context"
	"errors"
	"fmt"
	"os"
	"testing"

	"github.com/golang-jwt/jwt/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/wso2/agent-manager/agent-manager-service/clients/clientmocks"
	"github.com/wso2/agent-manager/agent-manager-service/config"
	"github.com/wso2/agent-manager/agent-manager-service/models"
	"github.com/wso2/agent-manager/agent-manager-service/utils"
)

// Note: discardLogger() is already declared in evaluator_manager_unit_test.go
// in this package, so we reuse it.

// testJWTConfig points the signer at the keys generated by scripts/gen_keys.sh.
// Paths are relative to the services/ package dir (the cwd during `go test`),
// so the repo-root keys/ directory is one level up.
func testJWTConfig() config.JWTSigningConfig {
	return config.JWTSigningConfig{
		PrivateKeyPath:        "../keys/private.pem",
		PublicKeysConfigPath:  "../keys/public-keys-config.json",
		ActiveKeyID:           "key-1",
		DefaultExpiryDuration: "8760h",
		Issuer:                "agent-manager-test",
	}
}

// newTokenManager constructs the service with the given client mock and a valid
// signing config. It skips the test if the signing keys are not present (the
// unit-test runner generates them; a bare `go test` without gen_keys.sh would
// otherwise fail with an unrelated file-not-found).
//
// testJWTConfig leaves DefaultEnvironment empty, so services built here have no
// configured fallback environment — use newTokenManagerWithConfig to exercise
// that fallback.
func newTokenManager(t *testing.T, oc *clientmocks.OpenChoreoClientMock) AgentTokenManagerService {
	t.Helper()
	return newTokenManagerWithConfig(t, oc, testJWTConfig())
}

// newTokenManagerWithConfig is newTokenManager with a caller-supplied signing
// config, for asserting config-driven defaults.
func newTokenManagerWithConfig(
	t *testing.T, oc *clientmocks.OpenChoreoClientMock, cfg config.JWTSigningConfig,
) AgentTokenManagerService {
	t.Helper()
	if _, err := os.Stat(cfg.PrivateKeyPath); err != nil {
		t.Skipf("signing keys not present (%v); run scripts/gen_keys.sh", err)
	}
	svc, err := NewAgentTokenManagerService(oc, cfg, discardLogger())
	require.NoError(t, err, "constructing the token manager with valid keys must succeed")
	return svc
}

// -----------------------------------------------------------------------------
// NewAgentTokenManagerService — constructor / key-loading branches.
// -----------------------------------------------------------------------------

func TestNewAgentTokenManagerService(t *testing.T) {
	oc := &clientmocks.OpenChoreoClientMock{}

	t.Run("succeeds with valid key configuration", func(t *testing.T) {
		cfg := testJWTConfig()
		if _, err := os.Stat(cfg.PrivateKeyPath); err != nil {
			t.Skipf("signing keys not present (%v); run scripts/gen_keys.sh", err)
		}
		svc, err := NewAgentTokenManagerService(oc, cfg, discardLogger())
		require.NoError(t, err)
		require.NotNil(t, svc)
	})

	t.Run("fails when the private key file is missing", func(t *testing.T) {
		cfg := testJWTConfig()
		cfg.PrivateKeyPath = "../keys/does-not-exist.pem"
		_, err := NewAgentTokenManagerService(oc, cfg, discardLogger())
		require.Error(t, err)
	})

	t.Run("fails when the public keys config is missing", func(t *testing.T) {
		cfg := testJWTConfig()
		if _, err := os.Stat(cfg.PrivateKeyPath); err != nil {
			t.Skipf("signing keys not present (%v); run scripts/gen_keys.sh", err)
		}
		cfg.PublicKeysConfigPath = "../keys/no-such-config.json"
		_, err := NewAgentTokenManagerService(oc, cfg, discardLogger())
		require.Error(t, err)
	})

	t.Run("fails when active key id is absent from loaded keys", func(t *testing.T) {
		cfg := testJWTConfig()
		if _, err := os.Stat(cfg.PrivateKeyPath); err != nil {
			t.Skipf("signing keys not present (%v); run scripts/gen_keys.sh", err)
		}
		cfg.ActiveKeyID = "key-does-not-exist"
		_, err := NewAgentTokenManagerService(oc, cfg, discardLogger())
		require.Error(t, err)
	})
}

// -----------------------------------------------------------------------------
// GenerateToken — validation gates, client error propagation, happy path,
// and verifiable claim construction.
// -----------------------------------------------------------------------------

func TestAgentTokenManager_GenerateToken_ValidationGates(t *testing.T) {
	t.Run("rejects empty org id with ErrInvalidInput", func(t *testing.T) {
		// GetComponent must NOT be reached — leaving the mock unconfigured asserts that.
		svc := newTokenManager(t, &clientmocks.OpenChoreoClientMock{})

		_, err := svc.GenerateToken(context.Background(), GenerateTokenRequest{
			OrgName:     "acme",
			ProjectName: "proj",
			AgentName:   "agent",
			Environment: "dev",
			// OrgId intentionally empty
		})

		assert.ErrorIs(t, err, utils.ErrInvalidInput)
	})

	t.Run("rejects empty environment name when no default is configured", func(t *testing.T) {
		// This is the only case where an omitted environment is fatal — testJWTConfig
		// leaves DefaultEnvironment empty, so there is nothing to fall back to. The
		// environment resolves entirely from the request and local config, so it must
		// fail before any OpenChoreo I/O: leaving every mock func nil asserts that
		// (a call on an unconfigured moq func panics), and the call recorders below
		// state it explicitly.
		oc := &clientmocks.OpenChoreoClientMock{}
		svc := newTokenManager(t, oc)

		_, err := svc.GenerateToken(context.Background(), GenerateTokenRequest{
			OrgName:     "acme",
			ProjectName: "proj",
			AgentName:   "agent",
			OrgId:       "org-123",
			// Environment intentionally empty
		})

		require.Error(t, err)
		assert.Contains(t, err.Error(), "JWT_SIGNING_DEFAULT_ENVIRONMENT",
			"the error must name the config knob the operator has to set")
		assert.Empty(t, oc.GetComponentCalls(), "no component lookup before the environment is resolved")
		assert.Empty(t, oc.GetEnvironmentCalls(), "no environment lookup without a resolved name")
		assert.Empty(t, oc.GetProjectCalls(), "no project lookup before the environment is resolved")
		assert.Empty(t, oc.ListOrganizationsCalls(), "no namespace resolution before the environment is resolved")
	})
}

func TestAgentTokenManager_GenerateToken_ClientErrors(t *testing.T) {
	base := GenerateTokenRequest{
		OrgName:     "acme",
		ProjectName: "proj",
		AgentName:   "agent",
		Environment: "dev",
		OrgId:       "org-123",
	}

	t.Run("propagates GetComponent error", func(t *testing.T) {
		boom := errors.New("component lookup failed")
		oc := &clientmocks.OpenChoreoClientMock{
			GetComponentFunc: func(_ context.Context, _, _, _ string) (*models.AgentResponse, error) {
				return nil, boom
			},
		}
		svc := newTokenManager(t, oc)

		_, err := svc.GenerateToken(context.Background(), base)

		require.Error(t, err)
		assert.ErrorIs(t, err, boom)
	})

	t.Run("propagates GetEnvironment error", func(t *testing.T) {
		boom := errors.New("environment lookup failed")
		oc := &clientmocks.OpenChoreoClientMock{
			GetComponentFunc: func(_ context.Context, _, _, _ string) (*models.AgentResponse, error) {
				return &models.AgentResponse{UUID: "comp-uuid"}, nil
			},
			GetEnvironmentFunc: func(_ context.Context, _, _ string) (*models.EnvironmentResponse, error) {
				return nil, boom
			},
		}
		svc := newTokenManager(t, oc)

		_, err := svc.GenerateToken(context.Background(), base)

		require.Error(t, err)
		assert.ErrorIs(t, err, boom)
	})

	t.Run("propagates GetProject error", func(t *testing.T) {
		boom := errors.New("project lookup failed")
		oc := &clientmocks.OpenChoreoClientMock{
			GetComponentFunc: func(_ context.Context, _, _, _ string) (*models.AgentResponse, error) {
				return &models.AgentResponse{UUID: "comp-uuid"}, nil
			},
			GetEnvironmentFunc: func(_ context.Context, _, _ string) (*models.EnvironmentResponse, error) {
				return &models.EnvironmentResponse{UUID: "env-uuid"}, nil
			},
			GetProjectFunc: func(_ context.Context, _, _ string) (*models.ProjectResponse, error) {
				return nil, boom
			},
		}
		svc := newTokenManager(t, oc)

		_, err := svc.GenerateToken(context.Background(), base)

		require.Error(t, err)
		assert.ErrorIs(t, err, boom)
	})
}

// fullClientMock returns a mock where all three lookups succeed with the given
// UUIDs, used to drive the happy path and expiry-validation branches.
func fullClientMock(compUID, envUID, projUID string) *clientmocks.OpenChoreoClientMock {
	return &clientmocks.OpenChoreoClientMock{
		GetComponentFunc: func(_ context.Context, _, _, _ string) (*models.AgentResponse, error) {
			return &models.AgentResponse{UUID: compUID}, nil
		},
		GetEnvironmentFunc: func(_ context.Context, _, _ string) (*models.EnvironmentResponse, error) {
			return &models.EnvironmentResponse{UUID: envUID}, nil
		},
		GetProjectFunc: func(_ context.Context, _, _ string) (*models.ProjectResponse, error) {
			return &models.ProjectResponse{UUID: projUID}, nil
		},
		ListOrganizationsFunc: func(_ context.Context) ([]*models.OrganizationResponse, error) {
			return []*models.OrganizationResponse{{Namespace: "acme-namespace"}}, nil
		},
	}
}

func TestAgentTokenManager_GenerateToken_ExpiryValidation(t *testing.T) {
	base := GenerateTokenRequest{
		OrgName:     "acme",
		ProjectName: "proj",
		AgentName:   "agent",
		Environment: "dev",
		OrgId:       "org-123",
	}

	t.Run("rejects malformed duration with ErrInvalidInput", func(t *testing.T) {
		svc := newTokenManager(t, fullClientMock("c", "e", "p"))
		req := base
		req.ExpiresIn = "not-a-duration"

		_, err := svc.GenerateToken(context.Background(), req)

		assert.ErrorIs(t, err, utils.ErrInvalidInput)
	})

	t.Run("rejects non-positive duration with ErrInvalidInput", func(t *testing.T) {
		svc := newTokenManager(t, fullClientMock("c", "e", "p"))
		req := base
		req.ExpiresIn = "-5h"

		_, err := svc.GenerateToken(context.Background(), req)

		assert.ErrorIs(t, err, utils.ErrInvalidInput)
	})

	t.Run("rejects duration exceeding the 10-year maximum", func(t *testing.T) {
		svc := newTokenManager(t, fullClientMock("c", "e", "p"))
		req := base
		req.ExpiresIn = "100000h" // > 10 years

		_, err := svc.GenerateToken(context.Background(), req)

		assert.ErrorIs(t, err, utils.ErrInvalidInput)
	})
}

func TestAgentTokenManager_GenerateToken_HappyPath(t *testing.T) {
	oc := fullClientMock("comp-uuid", "env-uuid", "proj-uuid")
	svc := newTokenManager(t, oc)

	req := GenerateTokenRequest{
		OrgName:     "acme",
		ProjectName: "proj",
		AgentName:   "my-agent",
		Environment: "dev",
		OrgId:       "org-123",
		ExpiresIn:   "1h",
	}

	resp, err := svc.GenerateToken(context.Background(), req)

	require.NoError(t, err)
	require.NotNil(t, resp)
	assert.Equal(t, "Bearer", resp.TokenType)
	assert.NotEmpty(t, resp.Token)
	assert.Greater(t, resp.ExpiresAt, resp.IssuedAt, "token must expire after it is issued")

	// Parse the token (without verifying the signature here) and assert that the
	// claims were assembled from the looked-up UUIDs and request fields.
	parser := jwt.NewParser()
	claims := &AgentTokenClaims{}
	parsed, _, err := parser.ParseUnverified(resp.Token, claims)
	require.NoError(t, err)

	assert.Equal(t, "comp-uuid", claims.ComponentUid)
	assert.Equal(t, "env-uuid", claims.EnvironmentUid)
	assert.Equal(t, "proj-uuid", claims.ProjectUid)
	assert.Equal(t, "org-123", claims.OrgId)
	assert.Equal(t, "acme-namespace", claims.Namespace, "namespace claim must come from GetOrganization, not the raw OU id")
	assert.Equal(t, "my-agent", claims.Subject)
	assert.Equal(t, "agent-manager-test", claims.Issuer)
	assert.NotEmpty(t, claims.ID, "jti claim must be set for forward-compatible revocation")
	assert.Equal(t, "key-1", parsed.Header["kid"])
	assert.Equal(t, "RS256", parsed.Method.Alg())
}

func TestAgentTokenManager_GenerateToken_DefaultExpiry(t *testing.T) {
	// Empty ExpiresIn should fall back to the config DefaultExpiryDuration and
	// still produce a valid token.
	oc := fullClientMock("c", "e", "p")
	svc := newTokenManager(t, oc)

	resp, err := svc.GenerateToken(context.Background(), GenerateTokenRequest{
		OrgName:     "acme",
		ProjectName: "proj",
		AgentName:   "agent",
		Environment: "dev",
		OrgId:       "org-123",
		// ExpiresIn empty -> default
	})

	require.NoError(t, err)
	require.NotNil(t, resp)
	assert.NotEmpty(t, resp.Token)
}

func TestAgentTokenManager_GenerateToken_DefaultEnvironment(t *testing.T) {
	// GenerateTokenRequest.Environment is documented as optional, falling back to
	// the configured default (JWT_SIGNING_DEFAULT_ENVIRONMENT). Callers rely on
	// that: the MCP create_external_agent tool always passes an empty
	// environment, and the token REST endpoint's ?environment= query parameter is
	// optional. Regression test for #1415, where an omitted environment failed
	// outright with "environment name cannot be empty".
	newMock := func(seen *string) *clientmocks.OpenChoreoClientMock {
		oc := fullClientMock("comp-uuid", "env-uuid", "proj-uuid")
		oc.GetEnvironmentFunc = func(_ context.Context, _, environmentName string) (*models.EnvironmentResponse, error) {
			*seen = environmentName
			return &models.EnvironmentResponse{UUID: "env-uuid"}, nil
		}
		return oc
	}

	base := GenerateTokenRequest{
		OrgName:     "acme",
		ProjectName: "proj",
		AgentName:   "agent",
		OrgId:       "org-123",
		ExpiresIn:   "1h",
	}

	cfg := testJWTConfig()
	cfg.DefaultEnvironment = "default"

	t.Run("omitted environment falls back to the configured default", func(t *testing.T) {
		var lookedUp string
		svc := newTokenManagerWithConfig(t, newMock(&lookedUp), cfg)

		resp, err := svc.GenerateToken(context.Background(), base)

		require.NoError(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, "default", lookedUp, "the configured default environment must be the one looked up")

		claims := &AgentTokenClaims{}
		_, _, err = jwt.NewParser().ParseUnverified(resp.Token, claims)
		require.NoError(t, err)
		assert.Equal(t, "env-uuid", claims.EnvironmentUid, "the resolved environment's UUID must reach the claims")
	})

	t.Run("request environment wins over the configured default", func(t *testing.T) {
		var lookedUp string
		svc := newTokenManagerWithConfig(t, newMock(&lookedUp), cfg)
		req := base
		req.Environment = "  staging  " // surrounding whitespace must not defeat the explicit value

		_, err := svc.GenerateToken(context.Background(), req)

		require.NoError(t, err)
		assert.Equal(t, "staging", lookedUp)
	})

	t.Run("blank-but-supplied environment is rejected, not defaulted", func(t *testing.T) {
		// A caller that names an environment gets that environment or an error — never a
		// silent substitution. Guards ?environment=%20 on the token REST endpoint, which
		// passes the raw query value through.
		oc := &clientmocks.OpenChoreoClientMock{}
		svc := newTokenManagerWithConfig(t, oc, cfg)
		req := base
		req.Environment = "   "

		_, err := svc.GenerateToken(context.Background(), req)

		assert.ErrorIs(t, err, utils.ErrInvalidInput)
		assert.Empty(t, oc.GetEnvironmentCalls(), "a blank environment must not be resolved against the default")
	})

	t.Run("missing environment maps to ErrEnvironmentNotFound", func(t *testing.T) {
		// The OpenChoreo client reports a 404 as the generic utils.ErrNotFound; the token
		// controller only maps utils.ErrEnvironmentNotFound to a 404 response. Without the
		// translation a configured default that does not exist in this install would
		// surface as an opaque 500.
		oc := fullClientMock("comp-uuid", "env-uuid", "proj-uuid")
		oc.GetEnvironmentFunc = func(_ context.Context, _, _ string) (*models.EnvironmentResponse, error) {
			return nil, fmt.Errorf("%w: environment not found", utils.ErrNotFound)
		}
		svc := newTokenManagerWithConfig(t, oc, cfg)

		_, err := svc.GenerateToken(context.Background(), base)

		require.Error(t, err)
		assert.ErrorIs(t, err, utils.ErrEnvironmentNotFound,
			"a 404 from GetEnvironment must reach the controller as ErrEnvironmentNotFound")
		assert.Contains(t, err.Error(), "default", "the error must name the environment that was not found")
	})
}

// -----------------------------------------------------------------------------
// GetJWKS — emits a JWK per loaded public key with the expected metadata.
// -----------------------------------------------------------------------------

func TestAgentTokenManager_GetJWKS(t *testing.T) {
	svc := newTokenManager(t, &clientmocks.OpenChoreoClientMock{})

	jwks, err := svc.GetJWKS(context.Background())

	require.NoError(t, err)
	require.NotNil(t, jwks)
	require.GreaterOrEqual(t, len(jwks.Keys), 1, "at least the active key must be exposed")

	found := false
	for _, k := range jwks.Keys {
		assert.Equal(t, "RSA", k.Kty)
		assert.Equal(t, "sig", k.Use)
		assert.NotEmpty(t, k.N)
		assert.NotEmpty(t, k.E)
		assert.NotEmpty(t, k.Kid)
		if k.Kid == "key-1" {
			found = true
			assert.Equal(t, "RS256", k.Alg)
		}
	}
	assert.True(t, found, "JWKS must include the active key-1")
}
