apiVersion: v1
kind: Secret
metadata:
  name: observer-idp-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  idpClientId: {{ .Values.tracesObserver.observer.idpClientId }}
  idpClientSecret: {{ .Values.tracesObserver.observer.idpClientSecret }}
